//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

export 'announcement.dart';
export 'automatic_popup.dart';
export 'automatic_popup_category.dart';
export 'automatic_push_category.dart';
export 'automatic_push_notification.dart';
export 'award_points.dart';
export 'award_points_transaction.dart';
export 'cart_item.dart';
export 'cart_item_option.dart';
export 'client_admin_notification.dart';
export 'comment_blocked.dart';
export 'comment_reported.dart';
export 'company.dart';
export 'cost_change_request.dart';
export 'department.dart';
export 'event.dart';
export 'event_comment.dart';
export 'faq.dart';
export 'faq_category.dart';
export 'inquiry.dart';
export 'inquiry_audit_log.dart';
export 'inquiry_comment.dart';
export 'inquiry_response.dart';
export 'integrated_admin_preferences.dart';
export 'lookbook.dart';
export 'lookbook_entry.dart';
export 'lookbook_product.dart';
export 'mission.dart';
export 'mission_click.dart';
export 'mission_impression.dart';
export 'mission_participation.dart';
export 'mission_photo_animation_completion.dart';
export 'mission_photo_not_allowed.dart';
export 'mission_photo_promotional.dart';
export 'mission_photo_task.dart';
export 'mission_request.dart';
export 'order.dart';
export 'order_item.dart';
export 'order_item_inquiry_message.dart';
export 'order_item_option.dart';
export 'organization.dart';
export 'payment.dart';
export 'popup.dart';
export 'product.dart';
export 'product_category.dart';
export 'product_image.dart';
export 'product_image_description.dart';
export 'product_option_color.dart';
export 'product_option_parameter.dart';
export 'product_option_value.dart';
export 'product_question.dart';
export 'product_question_reply.dart';
export 'product_review.dart';
export 'product_review_image.dart';
export 'product_subcategory.dart';
export 'product_wishlist.dart';
export 'push_notification.dart';
export 'push_notification_token.dart';
export 'push_notification_trigger.dart';
export 'report.dart';
export 'request_audit_log.dart';
export 'setting.dart';
export 'stamp.dart';
export 'story.dart';
export 'story_blocked.dart';
export 'story_comment.dart';
export 'story_like.dart';
export 'story_photo.dart';
export 'story_related_mission.dart';
export 'story_related_product.dart';
export 'story_tag.dart';
export 'sub_department.dart';
export 'trigger_event_log.dart';
export 'user.dart';
export 'user_organization.dart';
export 'user_profile.dart';
export 'user_setting_detail.dart';
export 'user_settings.dart';
export 'user_shipping_address.dart';

/// Tag: v2
/// Date: 2026-03-12 16:36:10.641466
