//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

export 'award_points.dart';
export 'award_points_transaction.dart';
export 'cart_item.dart';
export 'cart_item_option.dart';
export 'faq.dart';
export 'faq_category.dart';
export 'inquiry.dart';
export 'inquiry_response.dart';
export 'mission.dart';
export 'mission_participation.dart';
export 'mission_photo_animation_completion.dart';
export 'mission_photo_not_allowed.dart';
export 'mission_photo_promotional.dart';
export 'mission_photo_task.dart';
export 'mission_request.dart';
export 'organization.dart';
export 'popup.dart';
export 'product.dart';
export 'product_category.dart';
export 'product_image.dart';
export 'product_option_parameter.dart';
export 'product_option_value.dart';
export 'product_wishlist.dart';
export 'push_notification.dart';
export 'shipping_address.dart';
export 'stamp.dart';
export 'story.dart';
export 'story_comment.dart';
export 'story_like.dart';
export 'story_photo.dart';
export 'story_related_mission.dart';
export 'story_related_product.dart';
export 'story_tag.dart';
export 'trigger_event_log.dart';
export 'user.dart';
export 'user_organization.dart';
export 'user_shipping_address.dart';

/// Tag: v2
/// Date: 2025-12-03 16:25:28.163600
