//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Announcement Table
class AnnouncementTable extends SupabaseTable<AnnouncementRow> {
  /// Table Name
  @override
  String get tableName => 'announcement';

  /// Create a [AnnouncementRow] from the [data] provided
  @override
  AnnouncementRow createRow(Map<String, dynamic> data) =>
      AnnouncementRow.fromJson(data);
}

/// Announcement Row
class AnnouncementRow extends SupabaseDataRow {
  /// Announcement Row
  AnnouncementRow({
    String? id,
    String? title,
    String? body,
    bool? isPopup,
    bool? isDeleted,
    String? createdBy,
    DateTime? createdAt,
    int? views,
    List<String>? readBy,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (title != null) 'title': supaSerialize(title),
         if (body != null) 'body': supaSerialize(body),
         if (isPopup != null) 'is_popup': supaSerialize(isPopup),
         if (isDeleted != null) 'is_deleted': supaSerialize(isDeleted),
         if (createdBy != null) 'created_by': supaSerialize(createdBy),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (views != null) 'views': supaSerialize(views),
         if (readBy != null) 'read_by': supaSerialize(readBy),
       });

  /// Announcement Row
  const AnnouncementRow._(super.data);

  /// Create Announcement Row from a [data] map
  factory AnnouncementRow.fromJson(Map<String, dynamic> data) =>
      AnnouncementRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => AnnouncementTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Title field name
  static const String titleField = 'title';

  /// Title
  String? get title => getField<String>(titleField);
  set title(String? value) => setField<String>(titleField, value);

  /// Body field name
  static const String bodyField = 'body';

  /// Body
  String? get body => getField<String>(bodyField);
  set body(String? value) => setField<String>(bodyField, value);

  /// Is Popup field name
  static const String isPopupField = 'is_popup';

  /// Is Popup
  bool? get isPopup => getField<bool>(isPopupField);
  set isPopup(bool? value) => setField<bool>(isPopupField, value);

  /// Is Deleted field name
  static const String isDeletedField = 'is_deleted';

  /// Is Deleted
  bool get isDeleted => getField<bool>(isDeletedField, defaultValue: false)!;
  set isDeleted(bool value) => setField<bool>(isDeletedField, value);

  /// Created By field name
  static const String createdByField = 'created_by';

  /// Created By
  String? get createdBy => getField<String>(createdByField);
  set createdBy(String? value) => setField<String>(createdByField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Views field name
  static const String viewsField = 'views';

  /// Views
  int get views => getField<int>(viewsField, defaultValue: 0)!;
  set views(int value) => setField<int>(viewsField, value);

  /// Read By field name
  static const String readByField = 'read_by';

  /// Read By
  List<String> get readBy => getListField<String>(readByField);
  set readBy(List<String>? value) => setListField<String>(readByField, value);

  /// Make a copy of the current [AnnouncementRow]
  /// overriding the provided fields
  AnnouncementRow copyWith({
    String? id,
    String? title,
    String? body,
    bool? isPopup,
    bool? isDeleted,
    String? createdBy,
    DateTime? createdAt,
    int? views,
    List<String>? readBy,
  }) => AnnouncementRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'title': supaSerialize(title) ?? data['title'],
    'body': supaSerialize(body) ?? data['body'],
    'is_popup': supaSerialize(isPopup) ?? data['is_popup'],
    'is_deleted': supaSerialize(isDeleted) ?? data['is_deleted'],
    'created_by': supaSerialize(createdBy) ?? data['created_by'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'views': supaSerialize(views) ?? data['views'],
    'read_by': supaSerialize(readBy) ?? data['read_by'],
  });
}

/// Tag: v2
/// Date: 2026-02-04 11:46:32.433779
