//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Automatic Popup Table
class AutomaticPopupTable extends SupabaseTable<AutomaticPopupRow> {
  /// Table Name
  @override
  String get tableName => 'automatic_popup';

  /// Create a [AutomaticPopupRow] from the [data] provided
  @override
  AutomaticPopupRow createRow(Map<String, dynamic> data) =>
      AutomaticPopupRow.fromJson(data);
}

/// Automatic Popup Row
class AutomaticPopupRow extends SupabaseDataRow {
  /// Automatic Popup Row
  AutomaticPopupRow({
    required String categoryId,
    String? id,
    String? createdBy,
    String? title,
    String? body,
    bool? hasLinkButton,
    String? linkButtonText,
    String? linkButtonUrl,
    String? photoBucket,
    String? photoFileName,
    String? photoFolderPath,
    String? trigger,
    bool? isEnabled,
    DateTime? createdAt,
    DateTime? updatedAt,
    String? companyId,
  }) : super({
         'category_id': supaSerialize(categoryId),
         if (id != null) 'id': supaSerialize(id),
         if (createdBy != null) 'created_by': supaSerialize(createdBy),
         if (title != null) 'title': supaSerialize(title),
         if (body != null) 'body': supaSerialize(body),
         if (hasLinkButton != null)
           'has_link_button': supaSerialize(hasLinkButton),
         if (linkButtonText != null)
           'link_button_text': supaSerialize(linkButtonText),
         if (linkButtonUrl != null)
           'link_button_url': supaSerialize(linkButtonUrl),
         if (photoBucket != null) 'photo_bucket': supaSerialize(photoBucket),
         if (photoFileName != null)
           'photo_file_name': supaSerialize(photoFileName),
         if (photoFolderPath != null)
           'photo_folder_path': supaSerialize(photoFolderPath),
         if (trigger != null) 'trigger': supaSerialize(trigger),
         if (isEnabled != null) 'is_enabled': supaSerialize(isEnabled),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (updatedAt != null) 'updated_at': supaSerialize(updatedAt),
         if (companyId != null) 'company_id': supaSerialize(companyId),
       });

  /// Automatic Popup Row
  const AutomaticPopupRow._(super.data);

  /// Create Automatic Popup Row from a [data] map
  factory AutomaticPopupRow.fromJson(Map<String, dynamic> data) =>
      AutomaticPopupRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => AutomaticPopupTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Category Id field name
  static const String categoryIdField = 'category_id';

  /// Category Id
  String get categoryId => getField<String>(categoryIdField)!;
  set categoryId(String value) => setField<String>(categoryIdField, value);

  /// Created By field name
  static const String createdByField = 'created_by';

  /// Created By
  String? get createdBy => getField<String>(createdByField);
  set createdBy(String? value) => setField<String>(createdByField, value);

  /// Title field name
  static const String titleField = 'title';

  /// Title
  String? get title => getField<String>(titleField);
  set title(String? value) => setField<String>(titleField, value);

  /// Body field name
  static const String bodyField = 'body';

  /// Body
  String? get body => getField<String>(bodyField);
  set body(String? value) => setField<String>(bodyField, value);

  /// Has Link Button field name
  static const String hasLinkButtonField = 'has_link_button';

  /// Has Link Button
  bool get hasLinkButton =>
      getField<bool>(hasLinkButtonField, defaultValue: false)!;
  set hasLinkButton(bool value) => setField<bool>(hasLinkButtonField, value);

  /// Link Button Text field name
  static const String linkButtonTextField = 'link_button_text';

  /// Link Button Text
  String? get linkButtonText => getField<String>(linkButtonTextField);
  set linkButtonText(String? value) =>
      setField<String>(linkButtonTextField, value);

  /// Link Button Url field name
  static const String linkButtonUrlField = 'link_button_url';

  /// Link Button Url
  String? get linkButtonUrl => getField<String>(linkButtonUrlField);
  set linkButtonUrl(String? value) =>
      setField<String>(linkButtonUrlField, value);

  /// Photo Bucket field name
  static const String photoBucketField = 'photo_bucket';

  /// Photo Bucket
  String? get photoBucket => getField<String>(photoBucketField);
  set photoBucket(String? value) => setField<String>(photoBucketField, value);

  /// Photo File Name field name
  static const String photoFileNameField = 'photo_file_name';

  /// Photo File Name
  String? get photoFileName => getField<String>(photoFileNameField);
  set photoFileName(String? value) =>
      setField<String>(photoFileNameField, value);

  /// Photo Folder Path field name
  static const String photoFolderPathField = 'photo_folder_path';

  /// Photo Folder Path
  String? get photoFolderPath => getField<String>(photoFolderPathField);
  set photoFolderPath(String? value) =>
      setField<String>(photoFolderPathField, value);

  /// Trigger field name
  static const String triggerField = 'trigger';

  /// Trigger
  String? get trigger => getField<String>(triggerField);
  set trigger(String? value) => setField<String>(triggerField, value);

  /// Is Enabled field name
  static const String isEnabledField = 'is_enabled';

  /// Is Enabled
  bool get isEnabled => getField<bool>(isEnabledField, defaultValue: false)!;
  set isEnabled(bool value) => setField<bool>(isEnabledField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Updated At field name
  static const String updatedAtField = 'updated_at';

  /// Updated At
  DateTime get updatedAt =>
      getField<DateTime>(updatedAtField, defaultValue: DateTime.now())!;
  set updatedAt(DateTime value) => setField<DateTime>(updatedAtField, value);

  /// Company Id field name
  static const String companyIdField = 'company_id';

  /// Company Id
  String? get companyId => getField<String>(companyIdField);
  set companyId(String? value) => setField<String>(companyIdField, value);

  /// Make a copy of the current [AutomaticPopupRow]
  /// overriding the provided fields
  AutomaticPopupRow copyWith({
    String? categoryId,
    String? id,
    String? createdBy,
    String? title,
    String? body,
    bool? hasLinkButton,
    String? linkButtonText,
    String? linkButtonUrl,
    String? photoBucket,
    String? photoFileName,
    String? photoFolderPath,
    String? trigger,
    bool? isEnabled,
    DateTime? createdAt,
    DateTime? updatedAt,
    String? companyId,
  }) => AutomaticPopupRow.fromJson({
    'category_id': supaSerialize(categoryId) ?? data['category_id'],
    'id': supaSerialize(id) ?? data['id'],
    'created_by': supaSerialize(createdBy) ?? data['created_by'],
    'title': supaSerialize(title) ?? data['title'],
    'body': supaSerialize(body) ?? data['body'],
    'has_link_button': supaSerialize(hasLinkButton) ?? data['has_link_button'],
    'link_button_text':
        supaSerialize(linkButtonText) ?? data['link_button_text'],
    'link_button_url': supaSerialize(linkButtonUrl) ?? data['link_button_url'],
    'photo_bucket': supaSerialize(photoBucket) ?? data['photo_bucket'],
    'photo_file_name': supaSerialize(photoFileName) ?? data['photo_file_name'],
    'photo_folder_path':
        supaSerialize(photoFolderPath) ?? data['photo_folder_path'],
    'trigger': supaSerialize(trigger) ?? data['trigger'],
    'is_enabled': supaSerialize(isEnabled) ?? data['is_enabled'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'updated_at': supaSerialize(updatedAt) ?? data['updated_at'],
    'company_id': supaSerialize(companyId) ?? data['company_id'],
  });
}

/// Tag: v2
/// Date: 2026-01-08 15:39:59.995241
