//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Automatic Push Category Table
class AutomaticPushCategoryTable
    extends SupabaseTable<AutomaticPushCategoryRow> {
  /// Table Name
  @override
  String get tableName => 'automatic_push_category';

  /// Create a [AutomaticPushCategoryRow] from the [data] provided
  @override
  AutomaticPushCategoryRow createRow(Map<String, dynamic> data) =>
      AutomaticPushCategoryRow.fromJson(data);
}

/// Automatic Push Category Row
class AutomaticPushCategoryRow extends SupabaseDataRow {
  /// Automatic Push Category Row
  AutomaticPushCategoryRow({
    String? id,
    String? key,
    String? labelKo,
    DateTime? createdAt,
    AutomaticPushType? type,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (key != null) 'key': supaSerialize(key),
         if (labelKo != null) 'label_ko': supaSerialize(labelKo),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (type != null) 'type': supaSerialize(type),
       });

  /// Automatic Push Category Row
  const AutomaticPushCategoryRow._(super.data);

  /// Create Automatic Push Category Row from a [data] map
  factory AutomaticPushCategoryRow.fromJson(Map<String, dynamic> data) =>
      AutomaticPushCategoryRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => AutomaticPushCategoryTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Key field name
  static const String keyField = 'key';

  /// Key
  String? get key => getField<String>(keyField);
  set key(String? value) => setField<String>(keyField, value);

  /// Label Ko field name
  static const String labelKoField = 'label_ko';

  /// Label Ko
  String? get labelKo => getField<String>(labelKoField);
  set labelKo(String? value) => setField<String>(labelKoField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Type field name
  static const String typeField = 'type';

  /// Type
  AutomaticPushType? get type => getField<AutomaticPushType>(
    typeField,
    enumValues: AutomaticPushType.values,
  );
  set type(AutomaticPushType? value) =>
      setField<AutomaticPushType>(typeField, value);

  /// Make a copy of the current [AutomaticPushCategoryRow]
  /// overriding the provided fields
  AutomaticPushCategoryRow copyWith({
    String? id,
    String? key,
    String? labelKo,
    DateTime? createdAt,
    AutomaticPushType? type,
  }) => AutomaticPushCategoryRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'key': supaSerialize(key) ?? data['key'],
    'label_ko': supaSerialize(labelKo) ?? data['label_ko'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'type': supaSerialize(type) ?? data['type'],
  });
}

/// Tag: v2
/// Date: 2026-02-20 11:42:15.146626
