//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Award Points Table
class AwardPointsTable extends SupabaseTable<AwardPointsRow> {
  /// Table Name
  @override
  String get tableName => 'award_points';

  /// Create a [AwardPointsRow] from the [data] provided
  @override
  AwardPointsRow createRow(Map<String, dynamic> data) =>
      AwardPointsRow.fromJson(data);
}

/// Award Points Row
class AwardPointsRow extends SupabaseDataRow {
  /// Award Points Row
  AwardPointsRow({
    required String user,
    DateTime? createdAt,
    double? points,
    DateTime? updatedAt,
  }) : super({
         'user': supaSerialize(user),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (points != null) 'points': supaSerialize(points),
         if (updatedAt != null) 'updated_at': supaSerialize(updatedAt),
       });

  /// Award Points Row
  const AwardPointsRow._(super.data);

  /// Create Award Points Row from a [data] map
  factory AwardPointsRow.fromJson(Map<String, dynamic> data) =>
      AwardPointsRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => AwardPointsTable();

  /// User field name
  static const String userField = 'user';

  /// User
  String get user => getField<String>(userField)!;
  set user(String value) => setField<String>(userField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Points field name
  static const String pointsField = 'points';

  /// Points
  double get points => getField<double>(pointsField, defaultValue: 0)!;
  set points(double value) => setField<double>(pointsField, value);

  /// Updated At field name
  static const String updatedAtField = 'updated_at';

  /// Updated At
  DateTime get updatedAt =>
      getField<DateTime>(updatedAtField, defaultValue: DateTime.now())!;
  set updatedAt(DateTime value) => setField<DateTime>(updatedAtField, value);

  /// Make a copy of the current [AwardPointsRow]
  /// overriding the provided fields
  AwardPointsRow copyWith({
    String? user,
    DateTime? createdAt,
    double? points,
    DateTime? updatedAt,
  }) => AwardPointsRow.fromJson({
    'user': supaSerialize(user) ?? data['user'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'points': supaSerialize(points) ?? data['points'],
    'updated_at': supaSerialize(updatedAt) ?? data['updated_at'],
  });
}

/// Tag: v2
/// Date: 2026-01-07 17:49:51.863456
