//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Award Points Transaction Table
class AwardPointsTransactionTable
    extends SupabaseTable<AwardPointsTransactionRow> {
  /// Table Name
  @override
  String get tableName => 'award_points_transaction';

  /// Create a [AwardPointsTransactionRow] from the [data] provided
  @override
  AwardPointsTransactionRow createRow(Map<String, dynamic> data) =>
      AwardPointsTransactionRow.fromJson(data);
}

/// Award Points Transaction Row
class AwardPointsTransactionRow extends SupabaseDataRow {
  /// Award Points Transaction Row
  AwardPointsTransactionRow({
    required double awardAmount,
    required double newAmount,
    required String awardedUser,
    String? id,
    DateTime? createdAt,
    String? createdBy,
    String? transactionBy,
    double? previousAmount,
  }) : super({
         'award_amount': supaSerialize(awardAmount),
         'new_amount': supaSerialize(newAmount),
         'awarded_user': supaSerialize(awardedUser),
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (createdBy != null) 'created_by': supaSerialize(createdBy),
         if (transactionBy != null)
           'transaction_by': supaSerialize(transactionBy),
         if (previousAmount != null)
           'previous_amount': supaSerialize(previousAmount),
       });

  /// Award Points Transaction Row
  const AwardPointsTransactionRow._(super.data);

  /// Create Award Points Transaction Row from a [data] map
  factory AwardPointsTransactionRow.fromJson(Map<String, dynamic> data) =>
      AwardPointsTransactionRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => AwardPointsTransactionTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Created By field name
  static const String createdByField = 'created_by';

  /// Created By
  String get createdBy =>
      getField<String>(createdByField, defaultValue: 'auth.')!;
  set createdBy(String value) => setField<String>(createdByField, value);

  /// Transaction By field name
  static const String transactionByField = 'transaction_by';

  /// Transaction By
  String get transactionBy =>
      getField<String>(transactionByField, defaultValue: 'auth.')!;
  set transactionBy(String value) =>
      setField<String>(transactionByField, value);

  /// Award Amount field name
  static const String awardAmountField = 'award_amount';

  /// Award Amount
  double get awardAmount => getField<double>(awardAmountField)!;
  set awardAmount(double value) => setField<double>(awardAmountField, value);

  /// Previous Amount field name
  static const String previousAmountField = 'previous_amount';

  /// Previous Amount
  double get previousAmount =>
      getField<double>(previousAmountField, defaultValue: 0)!;
  set previousAmount(double value) =>
      setField<double>(previousAmountField, value);

  /// New Amount field name
  static const String newAmountField = 'new_amount';

  /// New Amount
  double get newAmount => getField<double>(newAmountField)!;
  set newAmount(double value) => setField<double>(newAmountField, value);

  /// Awarded User field name
  static const String awardedUserField = 'awarded_user';

  /// Awarded User
  String get awardedUser => getField<String>(awardedUserField)!;
  set awardedUser(String value) => setField<String>(awardedUserField, value);

  /// Make a copy of the current [AwardPointsTransactionRow]
  /// overriding the provided fields
  AwardPointsTransactionRow copyWith({
    double? awardAmount,
    double? newAmount,
    String? awardedUser,
    String? id,
    DateTime? createdAt,
    String? createdBy,
    String? transactionBy,
    double? previousAmount,
  }) => AwardPointsTransactionRow.fromJson({
    'award_amount': supaSerialize(awardAmount) ?? data['award_amount'],
    'new_amount': supaSerialize(newAmount) ?? data['new_amount'],
    'awarded_user': supaSerialize(awardedUser) ?? data['awarded_user'],
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'created_by': supaSerialize(createdBy) ?? data['created_by'],
    'transaction_by': supaSerialize(transactionBy) ?? data['transaction_by'],
    'previous_amount': supaSerialize(previousAmount) ?? data['previous_amount'],
  });
}

/// Tag: v2
/// Date: 2026-01-15 14:21:42.902549
