//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Banner Table
class BannerTable extends SupabaseTable<BannerRow> {
  /// Table Name
  @override
  String get tableName => 'banner';

  /// Create a [BannerRow] from the [data] provided
  @override
  BannerRow createRow(Map<String, dynamic> data) => BannerRow.fromJson(data);
}

/// Banner Row
class BannerRow extends SupabaseDataRow {
  /// Banner Row
  BannerRow({
    required String appType,
    String? id,
    String? imageBucket,
    String? imageFileName,
    String? imageFolderPath,
    bool? isActive,
    int? displayOrder,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) : super({
         'app_type': supaSerialize(appType),
         if (id != null) 'id': supaSerialize(id),
         if (imageBucket != null) 'image_bucket': supaSerialize(imageBucket),
         if (imageFileName != null)
           'image_file_name': supaSerialize(imageFileName),
         if (imageFolderPath != null)
           'image_folder_path': supaSerialize(imageFolderPath),
         if (isActive != null) 'is_active': supaSerialize(isActive),
         if (displayOrder != null) 'display_order': supaSerialize(displayOrder),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (updatedAt != null) 'updated_at': supaSerialize(updatedAt),
       });

  /// Banner Row
  const BannerRow._(super.data);

  /// Create Banner Row from a [data] map
  factory BannerRow.fromJson(Map<String, dynamic> data) =>
      BannerRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => BannerTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// App Type field name
  static const String appTypeField = 'app_type';

  /// App Type
  String get appType => getField<String>(appTypeField)!;
  set appType(String value) => setField<String>(appTypeField, value);

  /// Image Bucket field name
  static const String imageBucketField = 'image_bucket';

  /// Image Bucket
  String? get imageBucket => getField<String>(imageBucketField);
  set imageBucket(String? value) => setField<String>(imageBucketField, value);

  /// Image File Name field name
  static const String imageFileNameField = 'image_file_name';

  /// Image File Name
  String? get imageFileName => getField<String>(imageFileNameField);
  set imageFileName(String? value) =>
      setField<String>(imageFileNameField, value);

  /// Image Folder Path field name
  static const String imageFolderPathField = 'image_folder_path';

  /// Image Folder Path
  String? get imageFolderPath => getField<String>(imageFolderPathField);
  set imageFolderPath(String? value) =>
      setField<String>(imageFolderPathField, value);

  /// Is Active field name
  static const String isActiveField = 'is_active';

  /// Is Active
  bool get isActive => getField<bool>(isActiveField, defaultValue: false)!;
  set isActive(bool value) => setField<bool>(isActiveField, value);

  /// Display Order field name
  static const String displayOrderField = 'display_order';

  /// Display Order
  int get displayOrder => getField<int>(displayOrderField, defaultValue: 0)!;
  set displayOrder(int value) => setField<int>(displayOrderField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Updated At field name
  static const String updatedAtField = 'updated_at';

  /// Updated At
  DateTime get updatedAt =>
      getField<DateTime>(updatedAtField, defaultValue: DateTime.now())!;
  set updatedAt(DateTime value) => setField<DateTime>(updatedAtField, value);

  /// Make a copy of the current [BannerRow]
  /// overriding the provided fields
  BannerRow copyWith({
    String? appType,
    String? id,
    String? imageBucket,
    String? imageFileName,
    String? imageFolderPath,
    bool? isActive,
    int? displayOrder,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) => BannerRow.fromJson({
    'app_type': supaSerialize(appType) ?? data['app_type'],
    'id': supaSerialize(id) ?? data['id'],
    'image_bucket': supaSerialize(imageBucket) ?? data['image_bucket'],
    'image_file_name': supaSerialize(imageFileName) ?? data['image_file_name'],
    'image_folder_path':
        supaSerialize(imageFolderPath) ?? data['image_folder_path'],
    'is_active': supaSerialize(isActive) ?? data['is_active'],
    'display_order': supaSerialize(displayOrder) ?? data['display_order'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'updated_at': supaSerialize(updatedAt) ?? data['updated_at'],
  });
}

/// Tag: v2
/// Date: 2026-03-18 15:17:25.783274
