//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Cart Item Option Table
class CartItemOptionTable extends SupabaseTable<CartItemOptionRow> {
  /// Table Name
  @override
  String get tableName => 'cart_item_option';

  /// Create a [CartItemOptionRow] from the [data] provided
  @override
  CartItemOptionRow createRow(Map<String, dynamic> data) =>
      CartItemOptionRow.fromJson(data);
}

/// Cart Item Option Row
class CartItemOptionRow extends SupabaseDataRow {
  /// Cart Item Option Row
  CartItemOptionRow({
    String? id,
    DateTime? createdAt,
    String? option,
    String? value,
    String? cartItem,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (option != null) 'option': supaSerialize(option),
         if (value != null) 'value': supaSerialize(value),
         if (cartItem != null) 'cart_item': supaSerialize(cartItem),
       });

  /// Cart Item Option Row
  const CartItemOptionRow._(super.data);

  /// Create Cart Item Option Row from a [data] map
  factory CartItemOptionRow.fromJson(Map<String, dynamic> data) =>
      CartItemOptionRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => CartItemOptionTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Option field name
  static const String optionField = 'option';

  /// Option
  String? get option => getField<String>(optionField);
  set option(String? value) => setField<String>(optionField, value);

  /// Value field name
  static const String valueField = 'value';

  /// Value
  String? get value => getField<String>(valueField);
  set value(String? value) => setField<String>(valueField, value);

  /// Cart Item field name
  static const String cartItemField = 'cart_item';

  /// Cart Item
  String? get cartItem => getField<String>(cartItemField);
  set cartItem(String? value) => setField<String>(cartItemField, value);

  /// Make a copy of the current [CartItemOptionRow]
  /// overriding the provided fields
  CartItemOptionRow copyWith({
    String? id,
    DateTime? createdAt,
    String? option,
    String? value,
    String? cartItem,
  }) => CartItemOptionRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'option': supaSerialize(option) ?? data['option'],
    'value': supaSerialize(value) ?? data['value'],
    'cart_item': supaSerialize(cartItem) ?? data['cart_item'],
  });
}

/// Tag: v2
/// Date: 2026-03-13 16:11:42.571539
