//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Cart Item Table
class CartItemTable extends SupabaseTable<CartItemRow> {
  /// Table Name
  @override
  String get tableName => 'cart_item';

  /// Create a [CartItemRow] from the [data] provided
  @override
  CartItemRow createRow(Map<String, dynamic> data) =>
      CartItemRow.fromJson(data);
}

/// Cart Item Row
class CartItemRow extends SupabaseDataRow {
  /// Cart Item Row
  CartItemRow({
    String? id,
    DateTime? createdAt,
    String? product,
    double? quantity,
    String? customer,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (product != null) 'product': supaSerialize(product),
         if (quantity != null) 'quantity': supaSerialize(quantity),
         if (customer != null) 'customer': supaSerialize(customer),
       });

  /// Cart Item Row
  const CartItemRow._(super.data);

  /// Create Cart Item Row from a [data] map
  factory CartItemRow.fromJson(Map<String, dynamic> data) =>
      CartItemRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => CartItemTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Product field name
  static const String productField = 'product';

  /// Product
  String? get product => getField<String>(productField);
  set product(String? value) => setField<String>(productField, value);

  /// Quantity field name
  static const String quantityField = 'quantity';

  /// Quantity
  double get quantity => getField<double>(quantityField, defaultValue: 1)!;
  set quantity(double value) => setField<double>(quantityField, value);

  /// Customer field name
  static const String customerField = 'customer';

  /// Customer
  String? get customer => getField<String>(customerField);
  set customer(String? value) => setField<String>(customerField, value);

  /// Make a copy of the current [CartItemRow]
  /// overriding the provided fields
  CartItemRow copyWith({
    String? id,
    DateTime? createdAt,
    String? product,
    double? quantity,
    String? customer,
  }) => CartItemRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'product': supaSerialize(product) ?? data['product'],
    'quantity': supaSerialize(quantity) ?? data['quantity'],
    'customer': supaSerialize(customer) ?? data['customer'],
  });
}

/// Tag: v2
/// Date: 2025-12-01 17:41:38.039231
