//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Client Admin Notification Table
class ClientAdminNotificationTable
    extends SupabaseTable<ClientAdminNotificationRow> {
  /// Table Name
  @override
  String get tableName => 'client_admin_notification';

  /// Create a [ClientAdminNotificationRow] from the [data] provided
  @override
  ClientAdminNotificationRow createRow(Map<String, dynamic> data) =>
      ClientAdminNotificationRow.fromJson(data);
}

/// Client Admin Notification Row
class ClientAdminNotificationRow extends SupabaseDataRow {
  /// Client Admin Notification Row
  ClientAdminNotificationRow({
    required ClientAdminNotificationType notificationType,
    required String title,
    required String message,
    String? id,
    String? companyId,
    String? missionId,
    String? inquiryId,
    DateTime? createdAt,
    String? createdBy,
    List<String>? readBy,
  }) : super({
         'notification_type': supaSerialize(notificationType),
         'title': supaSerialize(title),
         'message': supaSerialize(message),
         if (id != null) 'id': supaSerialize(id),
         if (companyId != null) 'company_id': supaSerialize(companyId),
         if (missionId != null) 'mission_id': supaSerialize(missionId),
         if (inquiryId != null) 'inquiry_id': supaSerialize(inquiryId),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (createdBy != null) 'created_by': supaSerialize(createdBy),
         if (readBy != null) 'read_by': supaSerialize(readBy),
       });

  /// Client Admin Notification Row
  const ClientAdminNotificationRow._(super.data);

  /// Create Client Admin Notification Row from a [data] map
  factory ClientAdminNotificationRow.fromJson(Map<String, dynamic> data) =>
      ClientAdminNotificationRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => ClientAdminNotificationTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Company Id field name
  static const String companyIdField = 'company_id';

  /// Company Id
  String? get companyId => getField<String>(companyIdField);
  set companyId(String? value) => setField<String>(companyIdField, value);

  /// Notification Type field name
  static const String notificationTypeField = 'notification_type';

  /// Notification Type
  ClientAdminNotificationType get notificationType =>
      getField<ClientAdminNotificationType>(
        notificationTypeField,
        enumValues: ClientAdminNotificationType.values,
      )!;
  set notificationType(ClientAdminNotificationType value) =>
      setField<ClientAdminNotificationType>(notificationTypeField, value);

  /// Title field name
  static const String titleField = 'title';

  /// Title
  String get title => getField<String>(titleField)!;
  set title(String value) => setField<String>(titleField, value);

  /// Message field name
  static const String messageField = 'message';

  /// Message
  String get message => getField<String>(messageField)!;
  set message(String value) => setField<String>(messageField, value);

  /// Mission Id field name
  static const String missionIdField = 'mission_id';

  /// Mission Id
  String? get missionId => getField<String>(missionIdField);
  set missionId(String? value) => setField<String>(missionIdField, value);

  /// Inquiry Id field name
  static const String inquiryIdField = 'inquiry_id';

  /// Inquiry Id
  String? get inquiryId => getField<String>(inquiryIdField);
  set inquiryId(String? value) => setField<String>(inquiryIdField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Created By field name
  static const String createdByField = 'created_by';

  /// Created By
  String? get createdBy => getField<String>(createdByField);
  set createdBy(String? value) => setField<String>(createdByField, value);

  /// Read By field name
  static const String readByField = 'read_by';

  /// Read By
  List<String> get readBy =>
      getListField<String>(readByField, defaultValue: const <String>[]);
  set readBy(List<String>? value) => setListField<String>(readByField, value);

  /// Make a copy of the current [ClientAdminNotificationRow]
  /// overriding the provided fields
  ClientAdminNotificationRow copyWith({
    ClientAdminNotificationType? notificationType,
    String? title,
    String? message,
    String? id,
    String? companyId,
    String? missionId,
    String? inquiryId,
    DateTime? createdAt,
    String? createdBy,
    List<String>? readBy,
  }) => ClientAdminNotificationRow.fromJson({
    'notification_type':
        supaSerialize(notificationType) ?? data['notification_type'],
    'title': supaSerialize(title) ?? data['title'],
    'message': supaSerialize(message) ?? data['message'],
    'id': supaSerialize(id) ?? data['id'],
    'company_id': supaSerialize(companyId) ?? data['company_id'],
    'mission_id': supaSerialize(missionId) ?? data['mission_id'],
    'inquiry_id': supaSerialize(inquiryId) ?? data['inquiry_id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'created_by': supaSerialize(createdBy) ?? data['created_by'],
    'read_by': supaSerialize(readBy) ?? data['read_by'],
  });
}

/// Tag: v2
/// Date: 2026-03-20 19:41:33.359109
