//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Comment Blocked Table
class CommentBlockedTable extends SupabaseTable<CommentBlockedRow> {
  /// Table Name
  @override
  String get tableName => 'comment_blocked';

  /// Create a [CommentBlockedRow] from the [data] provided
  @override
  CommentBlockedRow createRow(Map<String, dynamic> data) =>
      CommentBlockedRow.fromJson(data);
}

/// Comment Blocked Row
class CommentBlockedRow extends SupabaseDataRow {
  /// Comment Blocked Row
  CommentBlockedRow({
    required String blocker,
    required String commentBlocked,
    String? id,
    DateTime? createdAt,
  }) : super({
         'blocker': supaSerialize(blocker),
         'comment_blocked': supaSerialize(commentBlocked),
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
       });

  /// Comment Blocked Row
  const CommentBlockedRow._(super.data);

  /// Create Comment Blocked Row from a [data] map
  factory CommentBlockedRow.fromJson(Map<String, dynamic> data) =>
      CommentBlockedRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => CommentBlockedTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Blocker field name
  static const String blockerField = 'blocker';

  /// Blocker
  String get blocker => getField<String>(blockerField)!;
  set blocker(String value) => setField<String>(blockerField, value);

  /// Comment Blocked field name
  static const String commentBlockedField = 'comment_blocked';

  /// Comment Blocked
  String get commentBlocked => getField<String>(commentBlockedField)!;
  set commentBlocked(String value) =>
      setField<String>(commentBlockedField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Make a copy of the current [CommentBlockedRow]
  /// overriding the provided fields
  CommentBlockedRow copyWith({
    String? blocker,
    String? commentBlocked,
    String? id,
    DateTime? createdAt,
  }) => CommentBlockedRow.fromJson({
    'blocker': supaSerialize(blocker) ?? data['blocker'],
    'comment_blocked': supaSerialize(commentBlocked) ?? data['comment_blocked'],
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
  });
}

/// Tag: v2
/// Date: 2026-03-24 15:11:23.913506
