//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Comment Reported Table
class CommentReportedTable extends SupabaseTable<CommentReportedRow> {
  /// Table Name
  @override
  String get tableName => 'comment_reported';

  /// Create a [CommentReportedRow] from the [data] provided
  @override
  CommentReportedRow createRow(Map<String, dynamic> data) =>
      CommentReportedRow.fromJson(data);
}

/// Comment Reported Row
class CommentReportedRow extends SupabaseDataRow {
  /// Comment Reported Row
  CommentReportedRow({
    required String reporter,
    required String commentReported,
    String? id,
    DateTime? createdAt,
  }) : super({
         'reporter': supaSerialize(reporter),
         'comment_reported': supaSerialize(commentReported),
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
       });

  /// Comment Reported Row
  const CommentReportedRow._(super.data);

  /// Create Comment Reported Row from a [data] map
  factory CommentReportedRow.fromJson(Map<String, dynamic> data) =>
      CommentReportedRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => CommentReportedTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Reporter field name
  static const String reporterField = 'reporter';

  /// Reporter
  String get reporter => getField<String>(reporterField)!;
  set reporter(String value) => setField<String>(reporterField, value);

  /// Comment Reported field name
  static const String commentReportedField = 'comment_reported';

  /// Comment Reported
  String get commentReported => getField<String>(commentReportedField)!;
  set commentReported(String value) =>
      setField<String>(commentReportedField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Make a copy of the current [CommentReportedRow]
  /// overriding the provided fields
  CommentReportedRow copyWith({
    String? reporter,
    String? commentReported,
    String? id,
    DateTime? createdAt,
  }) => CommentReportedRow.fromJson({
    'reporter': supaSerialize(reporter) ?? data['reporter'],
    'comment_reported':
        supaSerialize(commentReported) ?? data['comment_reported'],
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
  });
}

/// Tag: v2
/// Date: 2026-03-20 19:41:33.359863
