//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Company Email Domain Table
class CompanyEmailDomainTable extends SupabaseTable<CompanyEmailDomainRow> {
  /// Table Name
  @override
  String get tableName => 'company_email_domain';

  /// Create a [CompanyEmailDomainRow] from the [data] provided
  @override
  CompanyEmailDomainRow createRow(Map<String, dynamic> data) =>
      CompanyEmailDomainRow.fromJson(data);
}

/// Company Email Domain Row
class CompanyEmailDomainRow extends SupabaseDataRow {
  /// Company Email Domain Row
  CompanyEmailDomainRow({
    required String companyId,
    required String domain,
    String? id,
    bool? isActive,
    DateTime? createdAt,
    String? createdBy,
  }) : super({
         'company_id': supaSerialize(companyId),
         'domain': supaSerialize(domain),
         if (id != null) 'id': supaSerialize(id),
         if (isActive != null) 'is_active': supaSerialize(isActive),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (createdBy != null) 'created_by': supaSerialize(createdBy),
       });

  /// Company Email Domain Row
  const CompanyEmailDomainRow._(super.data);

  /// Create Company Email Domain Row from a [data] map
  factory CompanyEmailDomainRow.fromJson(Map<String, dynamic> data) =>
      CompanyEmailDomainRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => CompanyEmailDomainTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Company Id field name
  static const String companyIdField = 'company_id';

  /// Company Id
  String get companyId => getField<String>(companyIdField)!;
  set companyId(String value) => setField<String>(companyIdField, value);

  /// Domain field name
  static const String domainField = 'domain';

  /// Domain
  String get domain => getField<String>(domainField)!;
  set domain(String value) => setField<String>(domainField, value);

  /// Is Active field name
  static const String isActiveField = 'is_active';

  /// Is Active
  bool get isActive => getField<bool>(isActiveField, defaultValue: true)!;
  set isActive(bool value) => setField<bool>(isActiveField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Created By field name
  static const String createdByField = 'created_by';

  /// Created By
  String? get createdBy => getField<String>(createdByField);
  set createdBy(String? value) => setField<String>(createdByField, value);

  /// Make a copy of the current [CompanyEmailDomainRow]
  /// overriding the provided fields
  CompanyEmailDomainRow copyWith({
    String? companyId,
    String? domain,
    String? id,
    bool? isActive,
    DateTime? createdAt,
    String? createdBy,
  }) => CompanyEmailDomainRow.fromJson({
    'company_id': supaSerialize(companyId) ?? data['company_id'],
    'domain': supaSerialize(domain) ?? data['domain'],
    'id': supaSerialize(id) ?? data['id'],
    'is_active': supaSerialize(isActive) ?? data['is_active'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'created_by': supaSerialize(createdBy) ?? data['created_by'],
  });
}

/// Tag: v2
/// Date: 2026-03-24 15:11:23.915280
