//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Company Table
class CompanyTable extends SupabaseTable<CompanyRow> {
  /// Table Name
  @override
  String get tableName => 'company';

  /// Create a [CompanyRow] from the [data] provided
  @override
  CompanyRow createRow(Map<String, dynamic> data) => CompanyRow.fromJson(data);
}

/// Company Row
class CompanyRow extends SupabaseDataRow {
  /// Company Row
  CompanyRow({
    String? id,
    DateTime? createdAt,
    String? name,
    String? url,
    String? createdBy,
    String? ownedBy,
    VendorAdminType? vendorType,
    DateTime? deactivatedAt,
    double? costBudget,
    double? discountRate,
    double? contractedComissionRate,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (name != null) 'name': supaSerialize(name),
         if (url != null) 'url': supaSerialize(url),
         if (createdBy != null) 'created_by': supaSerialize(createdBy),
         if (ownedBy != null) 'owned_by': supaSerialize(ownedBy),
         if (vendorType != null) 'vendor_type': supaSerialize(vendorType),
         if (deactivatedAt != null)
           'deactivated_at': supaSerialize(deactivatedAt),
         if (costBudget != null) 'cost_budget': supaSerialize(costBudget),
         if (discountRate != null) 'discount_rate': supaSerialize(discountRate),
         if (contractedComissionRate != null)
           'contracted_comission_rate': supaSerialize(contractedComissionRate),
       });

  /// Company Row
  const CompanyRow._(super.data);

  /// Create Company Row from a [data] map
  factory CompanyRow.fromJson(Map<String, dynamic> data) =>
      CompanyRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => CompanyTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Name field name
  static const String nameField = 'name';

  /// Name
  String? get name => getField<String>(nameField);
  set name(String? value) => setField<String>(nameField, value);

  /// Url field name
  static const String urlField = 'url';

  /// Url
  String? get url => getField<String>(urlField);
  set url(String? value) => setField<String>(urlField, value);

  /// Created By field name
  static const String createdByField = 'created_by';

  /// Created By
  String get createdBy =>
      getField<String>(createdByField, defaultValue: 'auth.')!;
  set createdBy(String value) => setField<String>(createdByField, value);

  /// Owned By field name
  static const String ownedByField = 'owned_by';

  /// Owned By
  String get ownedBy => getField<String>(ownedByField, defaultValue: 'auth.')!;
  set ownedBy(String value) => setField<String>(ownedByField, value);

  /// Vendor Type field name
  static const String vendorTypeField = 'vendor_type';

  /// Vendor Type
  VendorAdminType get vendorType => getField<VendorAdminType>(
    vendorTypeField,
    enumValues: VendorAdminType.values,
    defaultValue: VendorAdminType.retailer,
  )!;
  set vendorType(VendorAdminType value) =>
      setField<VendorAdminType>(vendorTypeField, value);

  /// Deactivated At field name
  static const String deactivatedAtField = 'deactivated_at';

  /// Deactivated At
  DateTime? get deactivatedAt => getField<DateTime>(deactivatedAtField);
  set deactivatedAt(DateTime? value) =>
      setField<DateTime>(deactivatedAtField, value);

  /// Cost Budget field name
  static const String costBudgetField = 'cost_budget';

  /// Cost Budget
  double? get costBudget => getField<double>(costBudgetField);
  set costBudget(double? value) => setField<double>(costBudgetField, value);

  /// Discount Rate field name
  static const String discountRateField = 'discount_rate';

  /// Discount Rate
  double? get discountRate => getField<double>(discountRateField);
  set discountRate(double? value) => setField<double>(discountRateField, value);

  /// Contracted Comission Rate field name
  static const String contractedComissionRateField =
      'contracted_comission_rate';

  /// Contracted Comission Rate
  double? get contractedComissionRate =>
      getField<double>(contractedComissionRateField);
  set contractedComissionRate(double? value) =>
      setField<double>(contractedComissionRateField, value);

  /// Make a copy of the current [CompanyRow]
  /// overriding the provided fields
  CompanyRow copyWith({
    String? id,
    DateTime? createdAt,
    String? name,
    String? url,
    String? createdBy,
    String? ownedBy,
    VendorAdminType? vendorType,
    DateTime? deactivatedAt,
    double? costBudget,
    double? discountRate,
    double? contractedComissionRate,
  }) => CompanyRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'name': supaSerialize(name) ?? data['name'],
    'url': supaSerialize(url) ?? data['url'],
    'created_by': supaSerialize(createdBy) ?? data['created_by'],
    'owned_by': supaSerialize(ownedBy) ?? data['owned_by'],
    'vendor_type': supaSerialize(vendorType) ?? data['vendor_type'],
    'deactivated_at': supaSerialize(deactivatedAt) ?? data['deactivated_at'],
    'cost_budget': supaSerialize(costBudget) ?? data['cost_budget'],
    'discount_rate': supaSerialize(discountRate) ?? data['discount_rate'],
    'contracted_comission_rate':
        supaSerialize(contractedComissionRate) ??
        data['contracted_comission_rate'],
  });
}

/// Tag: v2
/// Date: 2026-03-13 09:30:01.671842
