//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Department Table
class DepartmentTable extends SupabaseTable<DepartmentRow> {
  /// Table Name
  @override
  String get tableName => 'department';

  /// Create a [DepartmentRow] from the [data] provided
  @override
  DepartmentRow createRow(Map<String, dynamic> data) =>
      DepartmentRow.fromJson(data);
}

/// Department Row
class DepartmentRow extends SupabaseDataRow {
  /// Department Row
  DepartmentRow({
    String? id,
    DateTime? createdAt,
    String? createdBy,
    String? name,
    String? company,
    double? discountRate,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (createdBy != null) 'created_by': supaSerialize(createdBy),
         if (name != null) 'name': supaSerialize(name),
         if (company != null) 'company': supaSerialize(company),
         if (discountRate != null) 'discount_rate': supaSerialize(discountRate),
       });

  /// Department Row
  const DepartmentRow._(super.data);

  /// Create Department Row from a [data] map
  factory DepartmentRow.fromJson(Map<String, dynamic> data) =>
      DepartmentRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => DepartmentTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Created By field name
  static const String createdByField = 'created_by';

  /// Created By
  String? get createdBy => getField<String>(createdByField);
  set createdBy(String? value) => setField<String>(createdByField, value);

  /// Name field name
  static const String nameField = 'name';

  /// Name
  String? get name => getField<String>(nameField);
  set name(String? value) => setField<String>(nameField, value);

  /// Company field name
  static const String companyField = 'company';

  /// Company
  String? get company => getField<String>(companyField);
  set company(String? value) => setField<String>(companyField, value);

  /// Discount Rate field name
  static const String discountRateField = 'discount_rate';

  /// Discount Rate
  double? get discountRate => getField<double>(discountRateField);
  set discountRate(double? value) => setField<double>(discountRateField, value);

  /// Make a copy of the current [DepartmentRow]
  /// overriding the provided fields
  DepartmentRow copyWith({
    String? id,
    DateTime? createdAt,
    String? createdBy,
    String? name,
    String? company,
    double? discountRate,
  }) => DepartmentRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'created_by': supaSerialize(createdBy) ?? data['created_by'],
    'name': supaSerialize(name) ?? data['name'],
    'company': supaSerialize(company) ?? data['company'],
    'discount_rate': supaSerialize(discountRate) ?? data['discount_rate'],
  });
}

/// Tag: v2
/// Date: 2026-02-04 11:46:32.443681
