//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Event Table
class EventTable extends SupabaseTable<EventRow> {
  /// Table Name
  @override
  String get tableName => 'event';

  /// Create a [EventRow] from the [data] provided
  @override
  EventRow createRow(Map<String, dynamic> data) => EventRow.fromJson(data);
}

/// Event Row
class EventRow extends SupabaseDataRow {
  /// Event Row
  EventRow({
    String? id,
    DateTime? createdAt,
    String? startDate,
    String? endDate,
    String? startTime,
    String? endTime,
    String? title,
    String? imageBucket,
    String? imageFolderPath,
    String? imageFileName,
    String? content,
    String? createdBy,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (startDate != null) 'start_date': supaSerialize(startDate),
         if (endDate != null) 'end_date': supaSerialize(endDate),
         if (startTime != null) 'start_time': supaSerialize(startTime),
         if (endTime != null) 'end_time': supaSerialize(endTime),
         if (title != null) 'title': supaSerialize(title),
         if (imageBucket != null) 'image_bucket': supaSerialize(imageBucket),
         if (imageFolderPath != null)
           'image_folder_path': supaSerialize(imageFolderPath),
         if (imageFileName != null)
           'image_file_name': supaSerialize(imageFileName),
         if (content != null) 'content': supaSerialize(content),
         if (createdBy != null) 'created_by': supaSerialize(createdBy),
       });

  /// Event Row
  const EventRow._(super.data);

  /// Create Event Row from a [data] map
  factory EventRow.fromJson(Map<String, dynamic> data) =>
      EventRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => EventTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Start Date field name
  static const String startDateField = 'start_date';

  /// Start Date
  String? get startDate => getField<String>(startDateField);
  set startDate(String? value) => setField<String>(startDateField, value);

  /// End Date field name
  static const String endDateField = 'end_date';

  /// End Date
  String? get endDate => getField<String>(endDateField);
  set endDate(String? value) => setField<String>(endDateField, value);

  /// Start Time field name
  static const String startTimeField = 'start_time';

  /// Start Time
  String? get startTime => getField<String>(startTimeField);
  set startTime(String? value) => setField<String>(startTimeField, value);

  /// End Time field name
  static const String endTimeField = 'end_time';

  /// End Time
  String? get endTime => getField<String>(endTimeField);
  set endTime(String? value) => setField<String>(endTimeField, value);

  /// Title field name
  static const String titleField = 'title';

  /// Title
  String? get title => getField<String>(titleField);
  set title(String? value) => setField<String>(titleField, value);

  /// Image Bucket field name
  static const String imageBucketField = 'image_bucket';

  /// Image Bucket
  String? get imageBucket => getField<String>(imageBucketField);
  set imageBucket(String? value) => setField<String>(imageBucketField, value);

  /// Image Folder Path field name
  static const String imageFolderPathField = 'image_folder_path';

  /// Image Folder Path
  String? get imageFolderPath => getField<String>(imageFolderPathField);
  set imageFolderPath(String? value) =>
      setField<String>(imageFolderPathField, value);

  /// Image File Name field name
  static const String imageFileNameField = 'image_file_name';

  /// Image File Name
  String? get imageFileName => getField<String>(imageFileNameField);
  set imageFileName(String? value) =>
      setField<String>(imageFileNameField, value);

  /// Content field name
  static const String contentField = 'content';

  /// Content
  String? get content => getField<String>(contentField);
  set content(String? value) => setField<String>(contentField, value);

  /// Created By field name
  static const String createdByField = 'created_by';

  /// Created By
  String? get createdBy => getField<String>(createdByField);
  set createdBy(String? value) => setField<String>(createdByField, value);

  /// Make a copy of the current [EventRow]
  /// overriding the provided fields
  EventRow copyWith({
    String? id,
    DateTime? createdAt,
    String? startDate,
    String? endDate,
    String? startTime,
    String? endTime,
    String? title,
    String? imageBucket,
    String? imageFolderPath,
    String? imageFileName,
    String? content,
    String? createdBy,
  }) => EventRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'start_date': supaSerialize(startDate) ?? data['start_date'],
    'end_date': supaSerialize(endDate) ?? data['end_date'],
    'start_time': supaSerialize(startTime) ?? data['start_time'],
    'end_time': supaSerialize(endTime) ?? data['end_time'],
    'title': supaSerialize(title) ?? data['title'],
    'image_bucket': supaSerialize(imageBucket) ?? data['image_bucket'],
    'image_folder_path':
        supaSerialize(imageFolderPath) ?? data['image_folder_path'],
    'image_file_name': supaSerialize(imageFileName) ?? data['image_file_name'],
    'content': supaSerialize(content) ?? data['content'],
    'created_by': supaSerialize(createdBy) ?? data['created_by'],
  });
}

/// Tag: v2
/// Date: 2026-03-12 16:36:10.604948
