//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Event Comment Table
class EventCommentTable extends SupabaseTable<EventCommentRow> {
  /// Table Name
  @override
  String get tableName => 'event_comment';

  /// Create a [EventCommentRow] from the [data] provided
  @override
  EventCommentRow createRow(Map<String, dynamic> data) =>
      EventCommentRow.fromJson(data);
}

/// Event Comment Row
class EventCommentRow extends SupabaseDataRow {
  /// Event Comment Row
  EventCommentRow({
    String? id,
    DateTime? createdAt,
    String? commentBy,
    String? comment,
    String? event,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (commentBy != null) 'comment_by': supaSerialize(commentBy),
         if (comment != null) 'comment': supaSerialize(comment),
         if (event != null) 'event': supaSerialize(event),
       });

  /// Event Comment Row
  const EventCommentRow._(super.data);

  /// Create Event Comment Row from a [data] map
  factory EventCommentRow.fromJson(Map<String, dynamic> data) =>
      EventCommentRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => EventCommentTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Comment By field name
  static const String commentByField = 'comment_by';

  /// Comment By
  String? get commentBy => getField<String>(commentByField);
  set commentBy(String? value) => setField<String>(commentByField, value);

  /// Comment field name
  static const String commentField = 'comment';

  /// Comment
  String? get comment => getField<String>(commentField);
  set comment(String? value) => setField<String>(commentField, value);

  /// Event field name
  static const String eventField = 'event';

  /// Event
  String? get event => getField<String>(eventField);
  set event(String? value) => setField<String>(eventField, value);

  /// Make a copy of the current [EventCommentRow]
  /// overriding the provided fields
  EventCommentRow copyWith({
    String? id,
    DateTime? createdAt,
    String? commentBy,
    String? comment,
    String? event,
  }) => EventCommentRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'comment_by': supaSerialize(commentBy) ?? data['comment_by'],
    'comment': supaSerialize(comment) ?? data['comment'],
    'event': supaSerialize(event) ?? data['event'],
  });
}

/// Tag: v2
/// Date: 2026-02-04 11:46:32.444671
