//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Faq Category Table
class FaqCategoryTable extends SupabaseTable<FaqCategoryRow> {
  /// Table Name
  @override
  String get tableName => 'faq_category';

  /// Create a [FaqCategoryRow] from the [data] provided
  @override
  FaqCategoryRow createRow(Map<String, dynamic> data) =>
      FaqCategoryRow.fromJson(data);
}

/// Faq Category Row
class FaqCategoryRow extends SupabaseDataRow {
  /// Faq Category Row
  FaqCategoryRow({
    String? id,
    String? value,
    DateTime? createdAt,
    String? createdBy,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (value != null) 'value': supaSerialize(value),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (createdBy != null) 'created_by': supaSerialize(createdBy),
       });

  /// Faq Category Row
  const FaqCategoryRow._(super.data);

  /// Create Faq Category Row from a [data] map
  factory FaqCategoryRow.fromJson(Map<String, dynamic> data) =>
      FaqCategoryRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => FaqCategoryTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Value field name
  static const String valueField = 'value';

  /// Value
  String? get value => getField<String>(valueField);
  set value(String? value) => setField<String>(valueField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Created By field name
  static const String createdByField = 'created_by';

  /// Created By
  String get createdBy =>
      getField<String>(createdByField, defaultValue: 'auth.')!;
  set createdBy(String value) => setField<String>(createdByField, value);

  /// Make a copy of the current [FaqCategoryRow]
  /// overriding the provided fields
  FaqCategoryRow copyWith({
    String? id,
    String? value,
    DateTime? createdAt,
    String? createdBy,
  }) => FaqCategoryRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'value': supaSerialize(value) ?? data['value'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'created_by': supaSerialize(createdBy) ?? data['created_by'],
  });
}

/// Tag: v2
/// Date: 2026-02-03 09:35:09.224435
