//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Featured Product Banner Table
class FeaturedProductBannerTable
    extends SupabaseTable<FeaturedProductBannerRow> {
  /// Table Name
  @override
  String get tableName => 'featured_product_banner';

  /// Create a [FeaturedProductBannerRow] from the [data] provided
  @override
  FeaturedProductBannerRow createRow(Map<String, dynamic> data) =>
      FeaturedProductBannerRow.fromJson(data);
}

/// Featured Product Banner Row
class FeaturedProductBannerRow extends SupabaseDataRow {
  /// Featured Product Banner Row
  FeaturedProductBannerRow({
    required String appType,
    required String productId,
    String? id,
    String? title,
    String? subtitle,
    String? buttonText,
    String? backgroundImageBucket,
    String? backgroundImageFileName,
    String? backgroundImageFolderPath,
    bool? isActive,
    int? displayOrder,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) : super({
         'app_type': supaSerialize(appType),
         'product_id': supaSerialize(productId),
         if (id != null) 'id': supaSerialize(id),
         if (title != null) 'title': supaSerialize(title),
         if (subtitle != null) 'subtitle': supaSerialize(subtitle),
         if (buttonText != null) 'button_text': supaSerialize(buttonText),
         if (backgroundImageBucket != null)
           'background_image_bucket': supaSerialize(backgroundImageBucket),
         if (backgroundImageFileName != null)
           'background_image_file_name': supaSerialize(backgroundImageFileName),
         if (backgroundImageFolderPath != null)
           'background_image_folder_path': supaSerialize(
             backgroundImageFolderPath,
           ),
         if (isActive != null) 'is_active': supaSerialize(isActive),
         if (displayOrder != null) 'display_order': supaSerialize(displayOrder),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (updatedAt != null) 'updated_at': supaSerialize(updatedAt),
       });

  /// Featured Product Banner Row
  const FeaturedProductBannerRow._(super.data);

  /// Create Featured Product Banner Row from a [data] map
  factory FeaturedProductBannerRow.fromJson(Map<String, dynamic> data) =>
      FeaturedProductBannerRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => FeaturedProductBannerTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// App Type field name
  static const String appTypeField = 'app_type';

  /// App Type
  String get appType => getField<String>(appTypeField)!;
  set appType(String value) => setField<String>(appTypeField, value);

  /// Title field name
  static const String titleField = 'title';

  /// Title
  String? get title => getField<String>(titleField);
  set title(String? value) => setField<String>(titleField, value);

  /// Subtitle field name
  static const String subtitleField = 'subtitle';

  /// Subtitle
  String? get subtitle => getField<String>(subtitleField);
  set subtitle(String? value) => setField<String>(subtitleField, value);

  /// Button Text field name
  static const String buttonTextField = 'button_text';

  /// Button Text
  String? get buttonText => getField<String>(buttonTextField);
  set buttonText(String? value) => setField<String>(buttonTextField, value);

  /// Product Id field name
  static const String productIdField = 'product_id';

  /// Product Id
  String get productId => getField<String>(productIdField)!;
  set productId(String value) => setField<String>(productIdField, value);

  /// Background Image Bucket field name
  static const String backgroundImageBucketField = 'background_image_bucket';

  /// Background Image Bucket
  String? get backgroundImageBucket =>
      getField<String>(backgroundImageBucketField);
  set backgroundImageBucket(String? value) =>
      setField<String>(backgroundImageBucketField, value);

  /// Background Image File Name field name
  static const String backgroundImageFileNameField =
      'background_image_file_name';

  /// Background Image File Name
  String? get backgroundImageFileName =>
      getField<String>(backgroundImageFileNameField);
  set backgroundImageFileName(String? value) =>
      setField<String>(backgroundImageFileNameField, value);

  /// Background Image Folder Path field name
  static const String backgroundImageFolderPathField =
      'background_image_folder_path';

  /// Background Image Folder Path
  String? get backgroundImageFolderPath =>
      getField<String>(backgroundImageFolderPathField);
  set backgroundImageFolderPath(String? value) =>
      setField<String>(backgroundImageFolderPathField, value);

  /// Is Active field name
  static const String isActiveField = 'is_active';

  /// Is Active
  bool get isActive => getField<bool>(isActiveField, defaultValue: true)!;
  set isActive(bool value) => setField<bool>(isActiveField, value);

  /// Display Order field name
  static const String displayOrderField = 'display_order';

  /// Display Order
  int get displayOrder => getField<int>(displayOrderField, defaultValue: 0)!;
  set displayOrder(int value) => setField<int>(displayOrderField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Updated At field name
  static const String updatedAtField = 'updated_at';

  /// Updated At
  DateTime get updatedAt =>
      getField<DateTime>(updatedAtField, defaultValue: DateTime.now())!;
  set updatedAt(DateTime value) => setField<DateTime>(updatedAtField, value);

  /// Make a copy of the current [FeaturedProductBannerRow]
  /// overriding the provided fields
  FeaturedProductBannerRow copyWith({
    String? appType,
    String? productId,
    String? id,
    String? title,
    String? subtitle,
    String? buttonText,
    String? backgroundImageBucket,
    String? backgroundImageFileName,
    String? backgroundImageFolderPath,
    bool? isActive,
    int? displayOrder,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) => FeaturedProductBannerRow.fromJson({
    'app_type': supaSerialize(appType) ?? data['app_type'],
    'product_id': supaSerialize(productId) ?? data['product_id'],
    'id': supaSerialize(id) ?? data['id'],
    'title': supaSerialize(title) ?? data['title'],
    'subtitle': supaSerialize(subtitle) ?? data['subtitle'],
    'button_text': supaSerialize(buttonText) ?? data['button_text'],
    'background_image_bucket':
        supaSerialize(backgroundImageBucket) ?? data['background_image_bucket'],
    'background_image_file_name':
        supaSerialize(backgroundImageFileName) ??
        data['background_image_file_name'],
    'background_image_folder_path':
        supaSerialize(backgroundImageFolderPath) ??
        data['background_image_folder_path'],
    'is_active': supaSerialize(isActive) ?? data['is_active'],
    'display_order': supaSerialize(displayOrder) ?? data['display_order'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'updated_at': supaSerialize(updatedAt) ?? data['updated_at'],
  });
}

/// Tag: v2
/// Date: 2026-03-18 15:17:25.798844
