//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Inquiry Table
class InquiryTable extends SupabaseTable<InquiryRow> {
  /// Table Name
  @override
  String get tableName => 'inquiry';

  /// Create a [InquiryRow] from the [data] provided
  @override
  InquiryRow createRow(Map<String, dynamic> data) => InquiryRow.fromJson(data);
}

/// Inquiry Row
class InquiryRow extends SupabaseDataRow {
  /// Inquiry Row
  InquiryRow({
    String? id,
    DateTime? createdAt,
    String? createdBy,
    String? content,
    String? title,
    bool? hasResponse,
    dynamic images,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (createdBy != null) 'created_by': supaSerialize(createdBy),
         if (content != null) 'content': supaSerialize(content),
         if (title != null) 'title': supaSerialize(title),
         if (hasResponse != null) 'has_response': supaSerialize(hasResponse),
         if (images != null) 'images': supaSerialize(images),
       });

  /// Inquiry Row
  const InquiryRow._(super.data);

  /// Create Inquiry Row from a [data] map
  factory InquiryRow.fromJson(Map<String, dynamic> data) =>
      InquiryRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => InquiryTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Created By field name
  static const String createdByField = 'created_by';

  /// Created By
  String get createdBy =>
      getField<String>(createdByField, defaultValue: 'auth.')!;
  set createdBy(String value) => setField<String>(createdByField, value);

  /// Content field name
  static const String contentField = 'content';

  /// Content
  String? get content => getField<String>(contentField);
  set content(String? value) => setField<String>(contentField, value);

  /// Title field name
  static const String titleField = 'title';

  /// Title
  String? get title => getField<String>(titleField);
  set title(String? value) => setField<String>(titleField, value);

  /// Has Response field name
  static const String hasResponseField = 'has_response';

  /// Has Response
  bool get hasResponse =>
      getField<bool>(hasResponseField, defaultValue: false)!;
  set hasResponse(bool value) => setField<bool>(hasResponseField, value);

  /// Images field name
  static const String imagesField = 'images';

  /// Images
  dynamic get images => getField<dynamic>(imagesField);
  set images(dynamic value) => setField<dynamic>(imagesField, value);

  /// Make a copy of the current [InquiryRow]
  /// overriding the provided fields
  InquiryRow copyWith({
    String? id,
    DateTime? createdAt,
    String? createdBy,
    String? content,
    String? title,
    bool? hasResponse,
    dynamic images,
  }) => InquiryRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'created_by': supaSerialize(createdBy) ?? data['created_by'],
    'content': supaSerialize(content) ?? data['content'],
    'title': supaSerialize(title) ?? data['title'],
    'has_response': supaSerialize(hasResponse) ?? data['has_response'],
    'images': supaSerialize(images) ?? data['images'],
  });
}

/// Tag: v2
/// Date: 2026-01-05 16:52:08.890066
