//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Inquiry Comment Table
class InquiryCommentTable extends SupabaseTable<InquiryCommentRow> {
  /// Table Name
  @override
  String get tableName => 'inquiry_comment';

  /// Create a [InquiryCommentRow] from the [data] provided
  @override
  InquiryCommentRow createRow(Map<String, dynamic> data) =>
      InquiryCommentRow.fromJson(data);
}

/// Inquiry Comment Row
class InquiryCommentRow extends SupabaseDataRow {
  /// Inquiry Comment Row
  InquiryCommentRow({
    String? id,
    String? inquiry,
    String? comment,
    String? commentBy,
    DateTime? createdAt,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (inquiry != null) 'inquiry': supaSerialize(inquiry),
         if (comment != null) 'comment': supaSerialize(comment),
         if (commentBy != null) 'comment_by': supaSerialize(commentBy),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
       });

  /// Inquiry Comment Row
  const InquiryCommentRow._(super.data);

  /// Create Inquiry Comment Row from a [data] map
  factory InquiryCommentRow.fromJson(Map<String, dynamic> data) =>
      InquiryCommentRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => InquiryCommentTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Inquiry field name
  static const String inquiryField = 'inquiry';

  /// Inquiry
  String? get inquiry => getField<String>(inquiryField);
  set inquiry(String? value) => setField<String>(inquiryField, value);

  /// Comment field name
  static const String commentField = 'comment';

  /// Comment
  String? get comment => getField<String>(commentField);
  set comment(String? value) => setField<String>(commentField, value);

  /// Comment By field name
  static const String commentByField = 'comment_by';

  /// Comment By
  String? get commentBy => getField<String>(commentByField);
  set commentBy(String? value) => setField<String>(commentByField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Make a copy of the current [InquiryCommentRow]
  /// overriding the provided fields
  InquiryCommentRow copyWith({
    String? id,
    String? inquiry,
    String? comment,
    String? commentBy,
    DateTime? createdAt,
  }) => InquiryCommentRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'inquiry': supaSerialize(inquiry) ?? data['inquiry'],
    'comment': supaSerialize(comment) ?? data['comment'],
    'comment_by': supaSerialize(commentBy) ?? data['comment_by'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
  });
}

/// Tag: v2
/// Date: 2026-02-04 11:46:32.447395
