//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Inquiry Table
class InquiryTable extends SupabaseTable<InquiryRow> {
  /// Table Name
  @override
  String get tableName => 'inquiry';

  /// Create a [InquiryRow] from the [data] provided
  @override
  InquiryRow createRow(Map<String, dynamic> data) => InquiryRow.fromJson(data);
}

/// Inquiry Row
class InquiryRow extends SupabaseDataRow {
  /// Inquiry Row
  InquiryRow({
    String? id,
    DateTime? createdAt,
    String? createdBy,
    String? content,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (createdBy != null) 'created_by': supaSerialize(createdBy),
         if (content != null) 'content': supaSerialize(content),
       });

  /// Inquiry Row
  const InquiryRow._(super.data);

  /// Create Inquiry Row from a [data] map
  factory InquiryRow.fromJson(Map<String, dynamic> data) =>
      InquiryRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => InquiryTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Created By field name
  static const String createdByField = 'created_by';

  /// Created By
  String get createdBy =>
      getField<String>(createdByField, defaultValue: 'auth.')!;
  set createdBy(String value) => setField<String>(createdByField, value);

  /// Content field name
  static const String contentField = 'content';

  /// Content
  String? get content => getField<String>(contentField);
  set content(String? value) => setField<String>(contentField, value);

  /// Make a copy of the current [InquiryRow]
  /// overriding the provided fields
  InquiryRow copyWith({
    String? id,
    DateTime? createdAt,
    String? createdBy,
    String? content,
  }) => InquiryRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'created_by': supaSerialize(createdBy) ?? data['created_by'],
    'content': supaSerialize(content) ?? data['content'],
  });
}

/// Tag: v2
/// Date: 2025-12-01 16:24:31.634823
