//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Integrated Admin Preferences Table
class IntegratedAdminPreferencesTable
    extends SupabaseTable<IntegratedAdminPreferencesRow> {
  /// Table Name
  @override
  String get tableName => 'integrated_admin_preferences';

  /// Create a [IntegratedAdminPreferencesRow] from the [data] provided
  @override
  IntegratedAdminPreferencesRow createRow(Map<String, dynamic> data) =>
      IntegratedAdminPreferencesRow.fromJson(data);
}

/// Integrated Admin Preferences Row
class IntegratedAdminPreferencesRow extends SupabaseDataRow {
  /// Integrated Admin Preferences Row
  IntegratedAdminPreferencesRow({
    required String userId,
    bool? costMissionParticipationBudgetLimit,
    DateTime? createdAt,
    DateTime? updatedAt,
    bool? performanceGlobalToggle,
    bool? performanceMissionExposure,
    bool? performanceMissionClicks,
    bool? performanceMissionClickRate,
    bool? performanceMissionCompletion,
    bool? performanceMissionConversion,
    bool? performanceAccumulatedMileage,
    bool? performanceProductPurchaseCount,
    bool? performanceProductPurchaseAmount,
    bool? costGlobalToggle,
    bool? costSolutionCost,
    bool? costEcoConsumptionPromotionCost,
    bool? costAverageSolutionCostPerSession,
    String? id,
    bool? costClientBurdenCost,
    bool? costGreensquareBurdenCost,
    bool? costClientBurdenAdditionalDiscountRate,
    bool? costFinalDiscountRate,
    bool? missionGlobalToggle,
    bool? missionCertificationPhoto,
    bool? notificationCostAdjustmentGlobalToggle,
    bool? notificationCostSolutionCostPerMission,
    bool? notificationCostEcoConsumptionPromotionBudgetLimit,
    bool? notificationCostDepartmentDiscountRate,
    bool? notificationMissionGlobalToggle,
    bool? notificationMissionActivation,
    bool? notificationMissionModification,
    bool? notificationMissionEnd,
    bool? notificationMissionDeletion,
    bool? notificationMissionActivatePast,
    bool? notificationMissionRestoreDeleted,
    bool? notificationPopupAutomaticActivation,
    bool? notificationPushCreation,
    bool? notificationPushSending,
    bool? notificationPushReservation,
    bool? notificationPushReservationCancellation,
    bool? notificationPushModification,
    bool? notificationPushDeletion,
    bool? notificationPushRestorePast,
    bool? notificationPushAutomaticActivation,
    bool? notificationPopupGlobalToggle,
    bool? notificationPopupCreation,
    bool? notificationPopupPosting,
    bool? notificationPopupReservation,
    bool? notificationPopupReservationCancellation,
    bool? notificationPopupModification,
    bool? notificationPopupDeletion,
    bool? notificationPopupEndPosted,
    bool? notificationPopupRestorePast,
    bool? notificationPushGlobalToggle,
  }) : super({
         'user_id': supaSerialize(userId),
         if (costMissionParticipationBudgetLimit != null)
           'cost_mission_participation_budget_limit': supaSerialize(
             costMissionParticipationBudgetLimit,
           ),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (updatedAt != null) 'updated_at': supaSerialize(updatedAt),
         if (performanceGlobalToggle != null)
           'performance_global_toggle': supaSerialize(performanceGlobalToggle),
         if (performanceMissionExposure != null)
           'performance_mission_exposure': supaSerialize(
             performanceMissionExposure,
           ),
         if (performanceMissionClicks != null)
           'performance_mission_clicks': supaSerialize(
             performanceMissionClicks,
           ),
         if (performanceMissionClickRate != null)
           'performance_mission_click_rate': supaSerialize(
             performanceMissionClickRate,
           ),
         if (performanceMissionCompletion != null)
           'performance_mission_completion': supaSerialize(
             performanceMissionCompletion,
           ),
         if (performanceMissionConversion != null)
           'performance_mission_conversion': supaSerialize(
             performanceMissionConversion,
           ),
         if (performanceAccumulatedMileage != null)
           'performance_accumulated_mileage': supaSerialize(
             performanceAccumulatedMileage,
           ),
         if (performanceProductPurchaseCount != null)
           'performance_product_purchase_count': supaSerialize(
             performanceProductPurchaseCount,
           ),
         if (performanceProductPurchaseAmount != null)
           'performance_product_purchase_amount': supaSerialize(
             performanceProductPurchaseAmount,
           ),
         if (costGlobalToggle != null)
           'cost_global_toggle': supaSerialize(costGlobalToggle),
         if (costSolutionCost != null)
           'cost_solution_cost': supaSerialize(costSolutionCost),
         if (costEcoConsumptionPromotionCost != null)
           'cost_eco_consumption_promotion_cost': supaSerialize(
             costEcoConsumptionPromotionCost,
           ),
         if (costAverageSolutionCostPerSession != null)
           'cost_average_solution_cost_per_session': supaSerialize(
             costAverageSolutionCostPerSession,
           ),
         if (id != null) 'id': supaSerialize(id),
         if (costClientBurdenCost != null)
           'cost_client_burden_cost': supaSerialize(costClientBurdenCost),
         if (costGreensquareBurdenCost != null)
           'cost_greensquare_burden_cost': supaSerialize(
             costGreensquareBurdenCost,
           ),
         if (costClientBurdenAdditionalDiscountRate != null)
           'cost_client_burden_additional_discount_rate': supaSerialize(
             costClientBurdenAdditionalDiscountRate,
           ),
         if (costFinalDiscountRate != null)
           'cost_final_discount_rate': supaSerialize(costFinalDiscountRate),
         if (missionGlobalToggle != null)
           'mission_global_toggle': supaSerialize(missionGlobalToggle),
         if (missionCertificationPhoto != null)
           'mission_certification_photo': supaSerialize(
             missionCertificationPhoto,
           ),
         if (notificationCostAdjustmentGlobalToggle != null)
           'notification_cost_adjustment_global_toggle': supaSerialize(
             notificationCostAdjustmentGlobalToggle,
           ),
         if (notificationCostSolutionCostPerMission != null)
           'notification_cost_solution_cost_per_mission': supaSerialize(
             notificationCostSolutionCostPerMission,
           ),
         if (notificationCostEcoConsumptionPromotionBudgetLimit != null)
           'notification_cost_eco_consumption_promotion_budget_limit':
               supaSerialize(
                 notificationCostEcoConsumptionPromotionBudgetLimit,
               ),
         if (notificationCostDepartmentDiscountRate != null)
           'notification_cost_department_discount_rate': supaSerialize(
             notificationCostDepartmentDiscountRate,
           ),
         if (notificationMissionGlobalToggle != null)
           'notification_mission_global_toggle': supaSerialize(
             notificationMissionGlobalToggle,
           ),
         if (notificationMissionActivation != null)
           'notification_mission_activation': supaSerialize(
             notificationMissionActivation,
           ),
         if (notificationMissionModification != null)
           'notification_mission_modification': supaSerialize(
             notificationMissionModification,
           ),
         if (notificationMissionEnd != null)
           'notification_mission_end': supaSerialize(notificationMissionEnd),
         if (notificationMissionDeletion != null)
           'notification_mission_deletion': supaSerialize(
             notificationMissionDeletion,
           ),
         if (notificationMissionActivatePast != null)
           'notification_mission_activate_past': supaSerialize(
             notificationMissionActivatePast,
           ),
         if (notificationMissionRestoreDeleted != null)
           'notification_mission_restore_deleted': supaSerialize(
             notificationMissionRestoreDeleted,
           ),
         if (notificationPopupAutomaticActivation != null)
           'notification_popup_automatic_activation': supaSerialize(
             notificationPopupAutomaticActivation,
           ),
         if (notificationPushCreation != null)
           'notification_push_creation': supaSerialize(
             notificationPushCreation,
           ),
         if (notificationPushSending != null)
           'notification_push_sending': supaSerialize(notificationPushSending),
         if (notificationPushReservation != null)
           'notification_push_reservation': supaSerialize(
             notificationPushReservation,
           ),
         if (notificationPushReservationCancellation != null)
           'notification_push_reservation_cancellation': supaSerialize(
             notificationPushReservationCancellation,
           ),
         if (notificationPushModification != null)
           'notification_push_modification': supaSerialize(
             notificationPushModification,
           ),
         if (notificationPushDeletion != null)
           'notification_push_deletion': supaSerialize(
             notificationPushDeletion,
           ),
         if (notificationPushRestorePast != null)
           'notification_push_restore_past': supaSerialize(
             notificationPushRestorePast,
           ),
         if (notificationPushAutomaticActivation != null)
           'notification_push_automatic_activation': supaSerialize(
             notificationPushAutomaticActivation,
           ),
         if (notificationPopupGlobalToggle != null)
           'notification_popup_global_toggle': supaSerialize(
             notificationPopupGlobalToggle,
           ),
         if (notificationPopupCreation != null)
           'notification_popup_creation': supaSerialize(
             notificationPopupCreation,
           ),
         if (notificationPopupPosting != null)
           'notification_popup_posting': supaSerialize(
             notificationPopupPosting,
           ),
         if (notificationPopupReservation != null)
           'notification_popup_reservation': supaSerialize(
             notificationPopupReservation,
           ),
         if (notificationPopupReservationCancellation != null)
           'notification_popup_reservation_cancellation': supaSerialize(
             notificationPopupReservationCancellation,
           ),
         if (notificationPopupModification != null)
           'notification_popup_modification': supaSerialize(
             notificationPopupModification,
           ),
         if (notificationPopupDeletion != null)
           'notification_popup_deletion': supaSerialize(
             notificationPopupDeletion,
           ),
         if (notificationPopupEndPosted != null)
           'notification_popup_end_posted': supaSerialize(
             notificationPopupEndPosted,
           ),
         if (notificationPopupRestorePast != null)
           'notification_popup_restore_past': supaSerialize(
             notificationPopupRestorePast,
           ),
         if (notificationPushGlobalToggle != null)
           'notification_push_global_toggle': supaSerialize(
             notificationPushGlobalToggle,
           ),
       });

  /// Integrated Admin Preferences Row
  const IntegratedAdminPreferencesRow._(super.data);

  /// Create Integrated Admin Preferences Row from a [data] map
  factory IntegratedAdminPreferencesRow.fromJson(Map<String, dynamic> data) =>
      IntegratedAdminPreferencesRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => IntegratedAdminPreferencesTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// User Id field name
  static const String userIdField = 'user_id';

  /// User Id
  String get userId => getField<String>(userIdField)!;
  set userId(String value) => setField<String>(userIdField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Updated At field name
  static const String updatedAtField = 'updated_at';

  /// Updated At
  DateTime get updatedAt =>
      getField<DateTime>(updatedAtField, defaultValue: DateTime.now())!;
  set updatedAt(DateTime value) => setField<DateTime>(updatedAtField, value);

  /// Performance Global Toggle field name
  static const String performanceGlobalToggleField =
      'performance_global_toggle';

  /// Performance Global Toggle
  bool get performanceGlobalToggle =>
      getField<bool>(performanceGlobalToggleField, defaultValue: true)!;
  set performanceGlobalToggle(bool value) =>
      setField<bool>(performanceGlobalToggleField, value);

  /// Performance Mission Exposure field name
  static const String performanceMissionExposureField =
      'performance_mission_exposure';

  /// Performance Mission Exposure
  bool get performanceMissionExposure =>
      getField<bool>(performanceMissionExposureField, defaultValue: true)!;
  set performanceMissionExposure(bool value) =>
      setField<bool>(performanceMissionExposureField, value);

  /// Performance Mission Clicks field name
  static const String performanceMissionClicksField =
      'performance_mission_clicks';

  /// Performance Mission Clicks
  bool get performanceMissionClicks =>
      getField<bool>(performanceMissionClicksField, defaultValue: false)!;
  set performanceMissionClicks(bool value) =>
      setField<bool>(performanceMissionClicksField, value);

  /// Performance Mission Click Rate field name
  static const String performanceMissionClickRateField =
      'performance_mission_click_rate';

  /// Performance Mission Click Rate
  bool get performanceMissionClickRate =>
      getField<bool>(performanceMissionClickRateField, defaultValue: true)!;
  set performanceMissionClickRate(bool value) =>
      setField<bool>(performanceMissionClickRateField, value);

  /// Performance Mission Completion field name
  static const String performanceMissionCompletionField =
      'performance_mission_completion';

  /// Performance Mission Completion
  bool get performanceMissionCompletion =>
      getField<bool>(performanceMissionCompletionField, defaultValue: true)!;
  set performanceMissionCompletion(bool value) =>
      setField<bool>(performanceMissionCompletionField, value);

  /// Performance Mission Conversion field name
  static const String performanceMissionConversionField =
      'performance_mission_conversion';

  /// Performance Mission Conversion
  bool get performanceMissionConversion =>
      getField<bool>(performanceMissionConversionField, defaultValue: true)!;
  set performanceMissionConversion(bool value) =>
      setField<bool>(performanceMissionConversionField, value);

  /// Performance Accumulated Mileage field name
  static const String performanceAccumulatedMileageField =
      'performance_accumulated_mileage';

  /// Performance Accumulated Mileage
  bool get performanceAccumulatedMileage =>
      getField<bool>(performanceAccumulatedMileageField, defaultValue: false)!;
  set performanceAccumulatedMileage(bool value) =>
      setField<bool>(performanceAccumulatedMileageField, value);

  /// Performance Product Purchase Count field name
  static const String performanceProductPurchaseCountField =
      'performance_product_purchase_count';

  /// Performance Product Purchase Count
  bool get performanceProductPurchaseCount =>
      getField<bool>(performanceProductPurchaseCountField, defaultValue: true)!;
  set performanceProductPurchaseCount(bool value) =>
      setField<bool>(performanceProductPurchaseCountField, value);

  /// Performance Product Purchase Amount field name
  static const String performanceProductPurchaseAmountField =
      'performance_product_purchase_amount';

  /// Performance Product Purchase Amount
  bool get performanceProductPurchaseAmount => getField<bool>(
    performanceProductPurchaseAmountField,
    defaultValue: true,
  )!;
  set performanceProductPurchaseAmount(bool value) =>
      setField<bool>(performanceProductPurchaseAmountField, value);

  /// Cost Global Toggle field name
  static const String costGlobalToggleField = 'cost_global_toggle';

  /// Cost Global Toggle
  bool get costGlobalToggle =>
      getField<bool>(costGlobalToggleField, defaultValue: true)!;
  set costGlobalToggle(bool value) =>
      setField<bool>(costGlobalToggleField, value);

  /// Cost Solution Cost field name
  static const String costSolutionCostField = 'cost_solution_cost';

  /// Cost Solution Cost
  bool get costSolutionCost =>
      getField<bool>(costSolutionCostField, defaultValue: true)!;
  set costSolutionCost(bool value) =>
      setField<bool>(costSolutionCostField, value);

  /// Cost Eco Consumption Promotion Cost field name
  static const String costEcoConsumptionPromotionCostField =
      'cost_eco_consumption_promotion_cost';

  /// Cost Eco Consumption Promotion Cost
  bool get costEcoConsumptionPromotionCost => getField<bool>(
    costEcoConsumptionPromotionCostField,
    defaultValue: false,
  )!;
  set costEcoConsumptionPromotionCost(bool value) =>
      setField<bool>(costEcoConsumptionPromotionCostField, value);

  /// Cost Average Solution Cost Per Session field name
  static const String costAverageSolutionCostPerSessionField =
      'cost_average_solution_cost_per_session';

  /// Cost Average Solution Cost Per Session
  bool get costAverageSolutionCostPerSession => getField<bool>(
    costAverageSolutionCostPerSessionField,
    defaultValue: true,
  )!;
  set costAverageSolutionCostPerSession(bool value) =>
      setField<bool>(costAverageSolutionCostPerSessionField, value);

  /// Cost Mission Participation Budget Limit field name
  static const String costMissionParticipationBudgetLimitField =
      'cost_mission_participation_budget_limit';

  /// Cost Mission Participation Budget Limit
  bool get costMissionParticipationBudgetLimit => getField<bool>(
    costMissionParticipationBudgetLimitField,
    defaultValue: true,
  )!;
  set costMissionParticipationBudgetLimit(bool value) =>
      setField<bool>(costMissionParticipationBudgetLimitField, value);

  /// Cost Client Burden Cost field name
  static const String costClientBurdenCostField = 'cost_client_burden_cost';

  /// Cost Client Burden Cost
  bool get costClientBurdenCost =>
      getField<bool>(costClientBurdenCostField, defaultValue: true)!;
  set costClientBurdenCost(bool value) =>
      setField<bool>(costClientBurdenCostField, value);

  /// Cost Greensquare Burden Cost field name
  static const String costGreensquareBurdenCostField =
      'cost_greensquare_burden_cost';

  /// Cost Greensquare Burden Cost
  bool get costGreensquareBurdenCost =>
      getField<bool>(costGreensquareBurdenCostField, defaultValue: false)!;
  set costGreensquareBurdenCost(bool value) =>
      setField<bool>(costGreensquareBurdenCostField, value);

  /// Cost Client Burden Additional Discount Rate field name
  static const String costClientBurdenAdditionalDiscountRateField =
      'cost_client_burden_additional_discount_rate';

  /// Cost Client Burden Additional Discount Rate
  bool get costClientBurdenAdditionalDiscountRate => getField<bool>(
    costClientBurdenAdditionalDiscountRateField,
    defaultValue: true,
  )!;
  set costClientBurdenAdditionalDiscountRate(bool value) =>
      setField<bool>(costClientBurdenAdditionalDiscountRateField, value);

  /// Cost Final Discount Rate field name
  static const String costFinalDiscountRateField = 'cost_final_discount_rate';

  /// Cost Final Discount Rate
  bool get costFinalDiscountRate =>
      getField<bool>(costFinalDiscountRateField, defaultValue: true)!;
  set costFinalDiscountRate(bool value) =>
      setField<bool>(costFinalDiscountRateField, value);

  /// Mission Global Toggle field name
  static const String missionGlobalToggleField = 'mission_global_toggle';

  /// Mission Global Toggle
  bool get missionGlobalToggle =>
      getField<bool>(missionGlobalToggleField, defaultValue: true)!;
  set missionGlobalToggle(bool value) =>
      setField<bool>(missionGlobalToggleField, value);

  /// Mission Certification Photo field name
  static const String missionCertificationPhotoField =
      'mission_certification_photo';

  /// Mission Certification Photo
  bool get missionCertificationPhoto =>
      getField<bool>(missionCertificationPhotoField, defaultValue: true)!;
  set missionCertificationPhoto(bool value) =>
      setField<bool>(missionCertificationPhotoField, value);

  /// Notification Cost Adjustment Global Toggle field name
  static const String notificationCostAdjustmentGlobalToggleField =
      'notification_cost_adjustment_global_toggle';

  /// Notification Cost Adjustment Global Toggle
  bool get notificationCostAdjustmentGlobalToggle => getField<bool>(
    notificationCostAdjustmentGlobalToggleField,
    defaultValue: true,
  )!;
  set notificationCostAdjustmentGlobalToggle(bool value) =>
      setField<bool>(notificationCostAdjustmentGlobalToggleField, value);

  /// Notification Cost Solution Cost Per Mission field name
  static const String notificationCostSolutionCostPerMissionField =
      'notification_cost_solution_cost_per_mission';

  /// Notification Cost Solution Cost Per Mission
  bool get notificationCostSolutionCostPerMission => getField<bool>(
    notificationCostSolutionCostPerMissionField,
    defaultValue: true,
  )!;
  set notificationCostSolutionCostPerMission(bool value) =>
      setField<bool>(notificationCostSolutionCostPerMissionField, value);

  /// Notification Cost Eco Consumption Promotion Budget Limit field name
  static const String notificationCostEcoConsumptionPromotionBudgetLimitField =
      'notification_cost_eco_consumption_promotion_budget_limit';

  /// Notification Cost Eco Consumption Promotion Budget Limit
  bool get notificationCostEcoConsumptionPromotionBudgetLimit => getField<bool>(
    notificationCostEcoConsumptionPromotionBudgetLimitField,
    defaultValue: false,
  )!;
  set notificationCostEcoConsumptionPromotionBudgetLimit(bool value) =>
      setField<bool>(
        notificationCostEcoConsumptionPromotionBudgetLimitField,
        value,
      );

  /// Notification Cost Department Discount Rate field name
  static const String notificationCostDepartmentDiscountRateField =
      'notification_cost_department_discount_rate';

  /// Notification Cost Department Discount Rate
  bool get notificationCostDepartmentDiscountRate => getField<bool>(
    notificationCostDepartmentDiscountRateField,
    defaultValue: true,
  )!;
  set notificationCostDepartmentDiscountRate(bool value) =>
      setField<bool>(notificationCostDepartmentDiscountRateField, value);

  /// Notification Mission Global Toggle field name
  static const String notificationMissionGlobalToggleField =
      'notification_mission_global_toggle';

  /// Notification Mission Global Toggle
  bool get notificationMissionGlobalToggle =>
      getField<bool>(notificationMissionGlobalToggleField, defaultValue: true)!;
  set notificationMissionGlobalToggle(bool value) =>
      setField<bool>(notificationMissionGlobalToggleField, value);

  /// Notification Mission Activation field name
  static const String notificationMissionActivationField =
      'notification_mission_activation';

  /// Notification Mission Activation
  bool get notificationMissionActivation =>
      getField<bool>(notificationMissionActivationField, defaultValue: true)!;
  set notificationMissionActivation(bool value) =>
      setField<bool>(notificationMissionActivationField, value);

  /// Notification Mission Modification field name
  static const String notificationMissionModificationField =
      'notification_mission_modification';

  /// Notification Mission Modification
  bool get notificationMissionModification => getField<bool>(
    notificationMissionModificationField,
    defaultValue: false,
  )!;
  set notificationMissionModification(bool value) =>
      setField<bool>(notificationMissionModificationField, value);

  /// Notification Mission End field name
  static const String notificationMissionEndField = 'notification_mission_end';

  /// Notification Mission End
  bool get notificationMissionEnd =>
      getField<bool>(notificationMissionEndField, defaultValue: true)!;
  set notificationMissionEnd(bool value) =>
      setField<bool>(notificationMissionEndField, value);

  /// Notification Mission Deletion field name
  static const String notificationMissionDeletionField =
      'notification_mission_deletion';

  /// Notification Mission Deletion
  bool get notificationMissionDeletion =>
      getField<bool>(notificationMissionDeletionField, defaultValue: true)!;
  set notificationMissionDeletion(bool value) =>
      setField<bool>(notificationMissionDeletionField, value);

  /// Notification Mission Activate Past field name
  static const String notificationMissionActivatePastField =
      'notification_mission_activate_past';

  /// Notification Mission Activate Past
  bool get notificationMissionActivatePast =>
      getField<bool>(notificationMissionActivatePastField, defaultValue: true)!;
  set notificationMissionActivatePast(bool value) =>
      setField<bool>(notificationMissionActivatePastField, value);

  /// Notification Mission Restore Deleted field name
  static const String notificationMissionRestoreDeletedField =
      'notification_mission_restore_deleted';

  /// Notification Mission Restore Deleted
  bool get notificationMissionRestoreDeleted => getField<bool>(
    notificationMissionRestoreDeletedField,
    defaultValue: false,
  )!;
  set notificationMissionRestoreDeleted(bool value) =>
      setField<bool>(notificationMissionRestoreDeletedField, value);

  /// Notification Push Global Toggle field name
  static const String notificationPushGlobalToggleField =
      'notification_push_global_toggle';

  /// Notification Push Global Toggle
  bool get notificationPushGlobalToggle =>
      getField<bool>(notificationPushGlobalToggleField, defaultValue: true)!;
  set notificationPushGlobalToggle(bool value) =>
      setField<bool>(notificationPushGlobalToggleField, value);

  /// Notification Push Creation field name
  static const String notificationPushCreationField =
      'notification_push_creation';

  /// Notification Push Creation
  bool get notificationPushCreation =>
      getField<bool>(notificationPushCreationField, defaultValue: true)!;
  set notificationPushCreation(bool value) =>
      setField<bool>(notificationPushCreationField, value);

  /// Notification Push Sending field name
  static const String notificationPushSendingField =
      'notification_push_sending';

  /// Notification Push Sending
  bool get notificationPushSending =>
      getField<bool>(notificationPushSendingField, defaultValue: false)!;
  set notificationPushSending(bool value) =>
      setField<bool>(notificationPushSendingField, value);

  /// Notification Push Reservation field name
  static const String notificationPushReservationField =
      'notification_push_reservation';

  /// Notification Push Reservation
  bool get notificationPushReservation =>
      getField<bool>(notificationPushReservationField, defaultValue: true)!;
  set notificationPushReservation(bool value) =>
      setField<bool>(notificationPushReservationField, value);

  /// Notification Push Reservation Cancellation field name
  static const String notificationPushReservationCancellationField =
      'notification_push_reservation_cancellation';

  /// Notification Push Reservation Cancellation
  bool get notificationPushReservationCancellation => getField<bool>(
    notificationPushReservationCancellationField,
    defaultValue: true,
  )!;
  set notificationPushReservationCancellation(bool value) =>
      setField<bool>(notificationPushReservationCancellationField, value);

  /// Notification Push Modification field name
  static const String notificationPushModificationField =
      'notification_push_modification';

  /// Notification Push Modification
  bool get notificationPushModification =>
      getField<bool>(notificationPushModificationField, defaultValue: true)!;
  set notificationPushModification(bool value) =>
      setField<bool>(notificationPushModificationField, value);

  /// Notification Push Deletion field name
  static const String notificationPushDeletionField =
      'notification_push_deletion';

  /// Notification Push Deletion
  bool get notificationPushDeletion =>
      getField<bool>(notificationPushDeletionField, defaultValue: false)!;
  set notificationPushDeletion(bool value) =>
      setField<bool>(notificationPushDeletionField, value);

  /// Notification Push Restore Past field name
  static const String notificationPushRestorePastField =
      'notification_push_restore_past';

  /// Notification Push Restore Past
  bool get notificationPushRestorePast =>
      getField<bool>(notificationPushRestorePastField, defaultValue: true)!;
  set notificationPushRestorePast(bool value) =>
      setField<bool>(notificationPushRestorePastField, value);

  /// Notification Push Automatic Activation field name
  static const String notificationPushAutomaticActivationField =
      'notification_push_automatic_activation';

  /// Notification Push Automatic Activation
  bool get notificationPushAutomaticActivation => getField<bool>(
    notificationPushAutomaticActivationField,
    defaultValue: true,
  )!;
  set notificationPushAutomaticActivation(bool value) =>
      setField<bool>(notificationPushAutomaticActivationField, value);

  /// Notification Popup Global Toggle field name
  static const String notificationPopupGlobalToggleField =
      'notification_popup_global_toggle';

  /// Notification Popup Global Toggle
  bool get notificationPopupGlobalToggle =>
      getField<bool>(notificationPopupGlobalToggleField, defaultValue: true)!;
  set notificationPopupGlobalToggle(bool value) =>
      setField<bool>(notificationPopupGlobalToggleField, value);

  /// Notification Popup Creation field name
  static const String notificationPopupCreationField =
      'notification_popup_creation';

  /// Notification Popup Creation
  bool get notificationPopupCreation =>
      getField<bool>(notificationPopupCreationField, defaultValue: true)!;
  set notificationPopupCreation(bool value) =>
      setField<bool>(notificationPopupCreationField, value);

  /// Notification Popup Posting field name
  static const String notificationPopupPostingField =
      'notification_popup_posting';

  /// Notification Popup Posting
  bool get notificationPopupPosting =>
      getField<bool>(notificationPopupPostingField, defaultValue: false)!;
  set notificationPopupPosting(bool value) =>
      setField<bool>(notificationPopupPostingField, value);

  /// Notification Popup Reservation field name
  static const String notificationPopupReservationField =
      'notification_popup_reservation';

  /// Notification Popup Reservation
  bool get notificationPopupReservation =>
      getField<bool>(notificationPopupReservationField, defaultValue: true)!;
  set notificationPopupReservation(bool value) =>
      setField<bool>(notificationPopupReservationField, value);

  /// Notification Popup Reservation Cancellation field name
  static const String notificationPopupReservationCancellationField =
      'notification_popup_reservation_cancellation';

  /// Notification Popup Reservation Cancellation
  bool get notificationPopupReservationCancellation => getField<bool>(
    notificationPopupReservationCancellationField,
    defaultValue: true,
  )!;
  set notificationPopupReservationCancellation(bool value) =>
      setField<bool>(notificationPopupReservationCancellationField, value);

  /// Notification Popup Modification field name
  static const String notificationPopupModificationField =
      'notification_popup_modification';

  /// Notification Popup Modification
  bool get notificationPopupModification =>
      getField<bool>(notificationPopupModificationField, defaultValue: true)!;
  set notificationPopupModification(bool value) =>
      setField<bool>(notificationPopupModificationField, value);

  /// Notification Popup Deletion field name
  static const String notificationPopupDeletionField =
      'notification_popup_deletion';

  /// Notification Popup Deletion
  bool get notificationPopupDeletion =>
      getField<bool>(notificationPopupDeletionField, defaultValue: false)!;
  set notificationPopupDeletion(bool value) =>
      setField<bool>(notificationPopupDeletionField, value);

  /// Notification Popup End Posted field name
  static const String notificationPopupEndPostedField =
      'notification_popup_end_posted';

  /// Notification Popup End Posted
  bool get notificationPopupEndPosted =>
      getField<bool>(notificationPopupEndPostedField, defaultValue: true)!;
  set notificationPopupEndPosted(bool value) =>
      setField<bool>(notificationPopupEndPostedField, value);

  /// Notification Popup Restore Past field name
  static const String notificationPopupRestorePastField =
      'notification_popup_restore_past';

  /// Notification Popup Restore Past
  bool get notificationPopupRestorePast =>
      getField<bool>(notificationPopupRestorePastField, defaultValue: true)!;
  set notificationPopupRestorePast(bool value) =>
      setField<bool>(notificationPopupRestorePastField, value);

  /// Notification Popup Automatic Activation field name
  static const String notificationPopupAutomaticActivationField =
      'notification_popup_automatic_activation';

  /// Notification Popup Automatic Activation
  bool get notificationPopupAutomaticActivation => getField<bool>(
    notificationPopupAutomaticActivationField,
    defaultValue: true,
  )!;
  set notificationPopupAutomaticActivation(bool value) =>
      setField<bool>(notificationPopupAutomaticActivationField, value);

  /// Make a copy of the current [IntegratedAdminPreferencesRow]
  /// overriding the provided fields
  IntegratedAdminPreferencesRow copyWith({
    String? userId,
    bool? costMissionParticipationBudgetLimit,
    DateTime? createdAt,
    DateTime? updatedAt,
    bool? performanceGlobalToggle,
    bool? performanceMissionExposure,
    bool? performanceMissionClicks,
    bool? performanceMissionClickRate,
    bool? performanceMissionCompletion,
    bool? performanceMissionConversion,
    bool? performanceAccumulatedMileage,
    bool? performanceProductPurchaseCount,
    bool? performanceProductPurchaseAmount,
    bool? costGlobalToggle,
    bool? costSolutionCost,
    bool? costEcoConsumptionPromotionCost,
    bool? costAverageSolutionCostPerSession,
    String? id,
    bool? costClientBurdenCost,
    bool? costGreensquareBurdenCost,
    bool? costClientBurdenAdditionalDiscountRate,
    bool? costFinalDiscountRate,
    bool? missionGlobalToggle,
    bool? missionCertificationPhoto,
    bool? notificationCostAdjustmentGlobalToggle,
    bool? notificationCostSolutionCostPerMission,
    bool? notificationCostEcoConsumptionPromotionBudgetLimit,
    bool? notificationCostDepartmentDiscountRate,
    bool? notificationMissionGlobalToggle,
    bool? notificationMissionActivation,
    bool? notificationMissionModification,
    bool? notificationMissionEnd,
    bool? notificationMissionDeletion,
    bool? notificationMissionActivatePast,
    bool? notificationMissionRestoreDeleted,
    bool? notificationPopupAutomaticActivation,
    bool? notificationPushCreation,
    bool? notificationPushSending,
    bool? notificationPushReservation,
    bool? notificationPushReservationCancellation,
    bool? notificationPushModification,
    bool? notificationPushDeletion,
    bool? notificationPushRestorePast,
    bool? notificationPushAutomaticActivation,
    bool? notificationPopupGlobalToggle,
    bool? notificationPopupCreation,
    bool? notificationPopupPosting,
    bool? notificationPopupReservation,
    bool? notificationPopupReservationCancellation,
    bool? notificationPopupModification,
    bool? notificationPopupDeletion,
    bool? notificationPopupEndPosted,
    bool? notificationPopupRestorePast,
    bool? notificationPushGlobalToggle,
  }) => IntegratedAdminPreferencesRow.fromJson({
    'user_id': supaSerialize(userId) ?? data['user_id'],
    'cost_mission_participation_budget_limit':
        supaSerialize(costMissionParticipationBudgetLimit) ??
        data['cost_mission_participation_budget_limit'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'updated_at': supaSerialize(updatedAt) ?? data['updated_at'],
    'performance_global_toggle':
        supaSerialize(performanceGlobalToggle) ??
        data['performance_global_toggle'],
    'performance_mission_exposure':
        supaSerialize(performanceMissionExposure) ??
        data['performance_mission_exposure'],
    'performance_mission_clicks':
        supaSerialize(performanceMissionClicks) ??
        data['performance_mission_clicks'],
    'performance_mission_click_rate':
        supaSerialize(performanceMissionClickRate) ??
        data['performance_mission_click_rate'],
    'performance_mission_completion':
        supaSerialize(performanceMissionCompletion) ??
        data['performance_mission_completion'],
    'performance_mission_conversion':
        supaSerialize(performanceMissionConversion) ??
        data['performance_mission_conversion'],
    'performance_accumulated_mileage':
        supaSerialize(performanceAccumulatedMileage) ??
        data['performance_accumulated_mileage'],
    'performance_product_purchase_count':
        supaSerialize(performanceProductPurchaseCount) ??
        data['performance_product_purchase_count'],
    'performance_product_purchase_amount':
        supaSerialize(performanceProductPurchaseAmount) ??
        data['performance_product_purchase_amount'],
    'cost_global_toggle':
        supaSerialize(costGlobalToggle) ?? data['cost_global_toggle'],
    'cost_solution_cost':
        supaSerialize(costSolutionCost) ?? data['cost_solution_cost'],
    'cost_eco_consumption_promotion_cost':
        supaSerialize(costEcoConsumptionPromotionCost) ??
        data['cost_eco_consumption_promotion_cost'],
    'cost_average_solution_cost_per_session':
        supaSerialize(costAverageSolutionCostPerSession) ??
        data['cost_average_solution_cost_per_session'],
    'id': supaSerialize(id) ?? data['id'],
    'cost_client_burden_cost':
        supaSerialize(costClientBurdenCost) ?? data['cost_client_burden_cost'],
    'cost_greensquare_burden_cost':
        supaSerialize(costGreensquareBurdenCost) ??
        data['cost_greensquare_burden_cost'],
    'cost_client_burden_additional_discount_rate':
        supaSerialize(costClientBurdenAdditionalDiscountRate) ??
        data['cost_client_burden_additional_discount_rate'],
    'cost_final_discount_rate':
        supaSerialize(costFinalDiscountRate) ??
        data['cost_final_discount_rate'],
    'mission_global_toggle':
        supaSerialize(missionGlobalToggle) ?? data['mission_global_toggle'],
    'mission_certification_photo':
        supaSerialize(missionCertificationPhoto) ??
        data['mission_certification_photo'],
    'notification_cost_adjustment_global_toggle':
        supaSerialize(notificationCostAdjustmentGlobalToggle) ??
        data['notification_cost_adjustment_global_toggle'],
    'notification_cost_solution_cost_per_mission':
        supaSerialize(notificationCostSolutionCostPerMission) ??
        data['notification_cost_solution_cost_per_mission'],
    'notification_cost_eco_consumption_promotion_budget_limit':
        supaSerialize(notificationCostEcoConsumptionPromotionBudgetLimit) ??
        data['notification_cost_eco_consumption_promotion_budget_limit'],
    'notification_cost_department_discount_rate':
        supaSerialize(notificationCostDepartmentDiscountRate) ??
        data['notification_cost_department_discount_rate'],
    'notification_mission_global_toggle':
        supaSerialize(notificationMissionGlobalToggle) ??
        data['notification_mission_global_toggle'],
    'notification_mission_activation':
        supaSerialize(notificationMissionActivation) ??
        data['notification_mission_activation'],
    'notification_mission_modification':
        supaSerialize(notificationMissionModification) ??
        data['notification_mission_modification'],
    'notification_mission_end':
        supaSerialize(notificationMissionEnd) ??
        data['notification_mission_end'],
    'notification_mission_deletion':
        supaSerialize(notificationMissionDeletion) ??
        data['notification_mission_deletion'],
    'notification_mission_activate_past':
        supaSerialize(notificationMissionActivatePast) ??
        data['notification_mission_activate_past'],
    'notification_mission_restore_deleted':
        supaSerialize(notificationMissionRestoreDeleted) ??
        data['notification_mission_restore_deleted'],
    'notification_popup_automatic_activation':
        supaSerialize(notificationPopupAutomaticActivation) ??
        data['notification_popup_automatic_activation'],
    'notification_push_creation':
        supaSerialize(notificationPushCreation) ??
        data['notification_push_creation'],
    'notification_push_sending':
        supaSerialize(notificationPushSending) ??
        data['notification_push_sending'],
    'notification_push_reservation':
        supaSerialize(notificationPushReservation) ??
        data['notification_push_reservation'],
    'notification_push_reservation_cancellation':
        supaSerialize(notificationPushReservationCancellation) ??
        data['notification_push_reservation_cancellation'],
    'notification_push_modification':
        supaSerialize(notificationPushModification) ??
        data['notification_push_modification'],
    'notification_push_deletion':
        supaSerialize(notificationPushDeletion) ??
        data['notification_push_deletion'],
    'notification_push_restore_past':
        supaSerialize(notificationPushRestorePast) ??
        data['notification_push_restore_past'],
    'notification_push_automatic_activation':
        supaSerialize(notificationPushAutomaticActivation) ??
        data['notification_push_automatic_activation'],
    'notification_popup_global_toggle':
        supaSerialize(notificationPopupGlobalToggle) ??
        data['notification_popup_global_toggle'],
    'notification_popup_creation':
        supaSerialize(notificationPopupCreation) ??
        data['notification_popup_creation'],
    'notification_popup_posting':
        supaSerialize(notificationPopupPosting) ??
        data['notification_popup_posting'],
    'notification_popup_reservation':
        supaSerialize(notificationPopupReservation) ??
        data['notification_popup_reservation'],
    'notification_popup_reservation_cancellation':
        supaSerialize(notificationPopupReservationCancellation) ??
        data['notification_popup_reservation_cancellation'],
    'notification_popup_modification':
        supaSerialize(notificationPopupModification) ??
        data['notification_popup_modification'],
    'notification_popup_deletion':
        supaSerialize(notificationPopupDeletion) ??
        data['notification_popup_deletion'],
    'notification_popup_end_posted':
        supaSerialize(notificationPopupEndPosted) ??
        data['notification_popup_end_posted'],
    'notification_popup_restore_past':
        supaSerialize(notificationPopupRestorePast) ??
        data['notification_popup_restore_past'],
    'notification_push_global_toggle':
        supaSerialize(notificationPushGlobalToggle) ??
        data['notification_push_global_toggle'],
  });
}

/// Tag: v2
/// Date: 2026-03-20 19:41:33.376670
