//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Lookbook Entry Table
class LookbookEntryTable extends SupabaseTable<LookbookEntryRow> {
  /// Table Name
  @override
  String get tableName => 'lookbook_entry';

  /// Create a [LookbookEntryRow] from the [data] provided
  @override
  LookbookEntryRow createRow(Map<String, dynamic> data) =>
      LookbookEntryRow.fromJson(data);
}

/// Lookbook Entry Row
class LookbookEntryRow extends SupabaseDataRow {
  /// Lookbook Entry Row
  LookbookEntryRow({
    required int id,
    DateTime? createdAt,
    String? bucket,
    String? folderPath,
    String? fileName,
    String? createdBy,
    int? order,
  }) : super({
         'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (bucket != null) 'bucket': supaSerialize(bucket),
         if (folderPath != null) 'folder_path': supaSerialize(folderPath),
         if (fileName != null) 'file_name': supaSerialize(fileName),
         if (createdBy != null) 'created_by': supaSerialize(createdBy),
         if (order != null) 'order': supaSerialize(order),
       });

  /// Lookbook Entry Row
  const LookbookEntryRow._(super.data);

  /// Create Lookbook Entry Row from a [data] map
  factory LookbookEntryRow.fromJson(Map<String, dynamic> data) =>
      LookbookEntryRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => LookbookEntryTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  int get id => getField<int>(idField)!;
  set id(int value) => setField<int>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Bucket field name
  static const String bucketField = 'bucket';

  /// Bucket
  String? get bucket => getField<String>(bucketField);
  set bucket(String? value) => setField<String>(bucketField, value);

  /// Folder Path field name
  static const String folderPathField = 'folder_path';

  /// Folder Path
  String? get folderPath => getField<String>(folderPathField);
  set folderPath(String? value) => setField<String>(folderPathField, value);

  /// File Name field name
  static const String fileNameField = 'file_name';

  /// File Name
  String? get fileName => getField<String>(fileNameField);
  set fileName(String? value) => setField<String>(fileNameField, value);

  /// Created By field name
  static const String createdByField = 'created_by';

  /// Created By
  String? get createdBy => getField<String>(createdByField);
  set createdBy(String? value) => setField<String>(createdByField, value);

  /// Order field name
  static const String orderField = 'order';

  /// Order
  int get order => getField<int>(orderField, defaultValue: 0)!;
  set order(int value) => setField<int>(orderField, value);

  /// Make a copy of the current [LookbookEntryRow]
  /// overriding the provided fields
  LookbookEntryRow copyWith({
    int? id,
    DateTime? createdAt,
    String? bucket,
    String? folderPath,
    String? fileName,
    String? createdBy,
    int? order,
  }) => LookbookEntryRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'bucket': supaSerialize(bucket) ?? data['bucket'],
    'folder_path': supaSerialize(folderPath) ?? data['folder_path'],
    'file_name': supaSerialize(fileName) ?? data['file_name'],
    'created_by': supaSerialize(createdBy) ?? data['created_by'],
    'order': supaSerialize(order) ?? data['order'],
  });
}

/// Tag: v2
/// Date: 2026-01-07 17:49:51.876662
