//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Lookbook Product Table
class LookbookProductTable extends SupabaseTable<LookbookProductRow> {
  /// Table Name
  @override
  String get tableName => 'lookbook_product';

  /// Create a [LookbookProductRow] from the [data] provided
  @override
  LookbookProductRow createRow(Map<String, dynamic> data) =>
      LookbookProductRow.fromJson(data);
}

/// Lookbook Product Row
class LookbookProductRow extends SupabaseDataRow {
  /// Lookbook Product Row
  LookbookProductRow({
    String? id,
    DateTime? createdAt,
    String? createdBy,
    String? product,
    double? x,
    double? y,
    String? lookbookEntry,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (createdBy != null) 'created_by': supaSerialize(createdBy),
         if (product != null) 'product': supaSerialize(product),
         if (x != null) 'x': supaSerialize(x),
         if (y != null) 'y': supaSerialize(y),
         if (lookbookEntry != null)
           'lookbook_entry': supaSerialize(lookbookEntry),
       });

  /// Lookbook Product Row
  const LookbookProductRow._(super.data);

  /// Create Lookbook Product Row from a [data] map
  factory LookbookProductRow.fromJson(Map<String, dynamic> data) =>
      LookbookProductRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => LookbookProductTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Created By field name
  static const String createdByField = 'created_by';

  /// Created By
  String? get createdBy => getField<String>(createdByField);
  set createdBy(String? value) => setField<String>(createdByField, value);

  /// Product field name
  static const String productField = 'product';

  /// Product
  String? get product => getField<String>(productField);
  set product(String? value) => setField<String>(productField, value);

  /// X field name
  static const String xField = 'x';

  /// X
  double? get x => getField<double>(xField);
  set x(double? value) => setField<double>(xField, value);

  /// Y field name
  static const String yField = 'y';

  /// Y
  double? get y => getField<double>(yField);
  set y(double? value) => setField<double>(yField, value);

  /// Lookbook Entry field name
  static const String lookbookEntryField = 'lookbook_entry';

  /// Lookbook Entry
  String? get lookbookEntry => getField<String>(lookbookEntryField);
  set lookbookEntry(String? value) =>
      setField<String>(lookbookEntryField, value);

  /// Make a copy of the current [LookbookProductRow]
  /// overriding the provided fields
  LookbookProductRow copyWith({
    String? id,
    DateTime? createdAt,
    String? createdBy,
    String? product,
    double? x,
    double? y,
    String? lookbookEntry,
  }) => LookbookProductRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'created_by': supaSerialize(createdBy) ?? data['created_by'],
    'product': supaSerialize(product) ?? data['product'],
    'x': supaSerialize(x) ?? data['x'],
    'y': supaSerialize(y) ?? data['y'],
    'lookbook_entry': supaSerialize(lookbookEntry) ?? data['lookbook_entry'],
  });
}

/// Tag: v2
/// Date: 2026-03-17 11:11:48.489994
