//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Lookbook Table
class LookbookTable extends SupabaseTable<LookbookRow> {
  /// Table Name
  @override
  String get tableName => 'lookbook';

  /// Create a [LookbookRow] from the [data] provided
  @override
  LookbookRow createRow(Map<String, dynamic> data) =>
      LookbookRow.fromJson(data);
}

/// Lookbook Row
class LookbookRow extends SupabaseDataRow {
  /// Lookbook Row
  LookbookRow({
    String? id,
    DateTime? createdAt,
    String? createdBy,
    String? name,
    String? description,
    String? coverBucket,
    String? coverFolderPath,
    String? coverFileName,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (createdBy != null) 'created_by': supaSerialize(createdBy),
         if (name != null) 'name': supaSerialize(name),
         if (description != null) 'description': supaSerialize(description),
         if (coverBucket != null) 'cover_bucket': supaSerialize(coverBucket),
         if (coverFolderPath != null)
           'cover_folder_path': supaSerialize(coverFolderPath),
         if (coverFileName != null)
           'cover_file_name': supaSerialize(coverFileName),
       });

  /// Lookbook Row
  const LookbookRow._(super.data);

  /// Create Lookbook Row from a [data] map
  factory LookbookRow.fromJson(Map<String, dynamic> data) =>
      LookbookRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => LookbookTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Created By field name
  static const String createdByField = 'created_by';

  /// Created By
  String get createdBy =>
      getField<String>(createdByField, defaultValue: 'auth.')!;
  set createdBy(String value) => setField<String>(createdByField, value);

  /// Name field name
  static const String nameField = 'name';

  /// Name
  String? get name => getField<String>(nameField);
  set name(String? value) => setField<String>(nameField, value);

  /// Description field name
  static const String descriptionField = 'description';

  /// Description
  String? get description => getField<String>(descriptionField);
  set description(String? value) => setField<String>(descriptionField, value);

  /// Cover Bucket field name
  static const String coverBucketField = 'cover_bucket';

  /// Cover Bucket
  String? get coverBucket => getField<String>(coverBucketField);
  set coverBucket(String? value) => setField<String>(coverBucketField, value);

  /// Cover Folder Path field name
  static const String coverFolderPathField = 'cover_folder_path';

  /// Cover Folder Path
  String? get coverFolderPath => getField<String>(coverFolderPathField);
  set coverFolderPath(String? value) =>
      setField<String>(coverFolderPathField, value);

  /// Cover File Name field name
  static const String coverFileNameField = 'cover_file_name';

  /// Cover File Name
  String? get coverFileName => getField<String>(coverFileNameField);
  set coverFileName(String? value) =>
      setField<String>(coverFileNameField, value);

  /// Make a copy of the current [LookbookRow]
  /// overriding the provided fields
  LookbookRow copyWith({
    String? id,
    DateTime? createdAt,
    String? createdBy,
    String? name,
    String? description,
    String? coverBucket,
    String? coverFolderPath,
    String? coverFileName,
  }) => LookbookRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'created_by': supaSerialize(createdBy) ?? data['created_by'],
    'name': supaSerialize(name) ?? data['name'],
    'description': supaSerialize(description) ?? data['description'],
    'cover_bucket': supaSerialize(coverBucket) ?? data['cover_bucket'],
    'cover_folder_path':
        supaSerialize(coverFolderPath) ?? data['cover_folder_path'],
    'cover_file_name': supaSerialize(coverFileName) ?? data['cover_file_name'],
  });
}

/// Tag: v2
/// Date: 2026-02-20 11:42:15.161056
