//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Mission Impression Table
class MissionImpressionTable extends SupabaseTable<MissionImpressionRow> {
  /// Table Name
  @override
  String get tableName => 'mission_impression';

  /// Create a [MissionImpressionRow] from the [data] provided
  @override
  MissionImpressionRow createRow(Map<String, dynamic> data) =>
      MissionImpressionRow.fromJson(data);
}

/// Mission Impression Row
class MissionImpressionRow extends SupabaseDataRow {
  /// Mission Impression Row
  MissionImpressionRow({
    String? id,
    DateTime? createdAt,
    String? mission,
    String? user,
    String? profileUsed,
    String? department,
    String? subDepartment,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (mission != null) 'mission': supaSerialize(mission),
         if (user != null) 'user': supaSerialize(user),
         if (profileUsed != null) 'profile_used': supaSerialize(profileUsed),
         if (department != null) 'department': supaSerialize(department),
         if (subDepartment != null)
           'sub_department': supaSerialize(subDepartment),
       });

  /// Mission Impression Row
  const MissionImpressionRow._(super.data);

  /// Create Mission Impression Row from a [data] map
  factory MissionImpressionRow.fromJson(Map<String, dynamic> data) =>
      MissionImpressionRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => MissionImpressionTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Mission field name
  static const String missionField = 'mission';

  /// Mission
  String? get mission => getField<String>(missionField);
  set mission(String? value) => setField<String>(missionField, value);

  /// User field name
  static const String userField = 'user';

  /// User
  String? get user => getField<String>(userField);
  set user(String? value) => setField<String>(userField, value);

  /// Profile Used field name
  static const String profileUsedField = 'profile_used';

  /// Profile Used
  String? get profileUsed => getField<String>(profileUsedField);
  set profileUsed(String? value) => setField<String>(profileUsedField, value);

  /// Department field name
  static const String departmentField = 'department';

  /// Department
  String? get department => getField<String>(departmentField);
  set department(String? value) => setField<String>(departmentField, value);

  /// Sub Department field name
  static const String subDepartmentField = 'sub_department';

  /// Sub Department
  String? get subDepartment => getField<String>(subDepartmentField);
  set subDepartment(String? value) =>
      setField<String>(subDepartmentField, value);

  /// Make a copy of the current [MissionImpressionRow]
  /// overriding the provided fields
  MissionImpressionRow copyWith({
    String? id,
    DateTime? createdAt,
    String? mission,
    String? user,
    String? profileUsed,
    String? department,
    String? subDepartment,
  }) => MissionImpressionRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'mission': supaSerialize(mission) ?? data['mission'],
    'user': supaSerialize(user) ?? data['user'],
    'profile_used': supaSerialize(profileUsed) ?? data['profile_used'],
    'department': supaSerialize(department) ?? data['department'],
    'sub_department': supaSerialize(subDepartment) ?? data['sub_department'],
  });
}

/// Tag: v2
/// Date: 2026-03-12 16:36:10.618288
