//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Mission Table
class MissionTable extends SupabaseTable<MissionRow> {
  /// Table Name
  @override
  String get tableName => 'mission';

  /// Create a [MissionRow] from the [data] provided
  @override
  MissionRow createRow(Map<String, dynamic> data) => MissionRow.fromJson(data);
}

/// Mission Row
class MissionRow extends SupabaseDataRow {
  /// Mission Row
  MissionRow({
    String? id,
    DateTime? createdAt,
    String? createdBy,
    MissionType? type,
    String? title,
    String? text,
    String? thumbnailBucket,
    String? thumbnailFolderPath,
    String? thumbnailFilename,
    int? awardPoints,
    int? order,
    String? taskExplanation,
    String? doNotDoExplanation,
    String? participationButtonText,
    String? name,
    double? carbonEmissionsReductionPerParticipationG,
    String? startActiveDate,
    String? lastActiveDate,
    MissionPublicity? publicity,
    bool? isPublished,
    String? stamp,
    DateTime? submittedForReviewAt,
    DateTime? approvedAt,
    String? approvedBy,
    DateTime? rejectedAt,
    String? rejectedBy,
    bool? isDeleted,
    String? rejectedReason,
    String? companyId,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (createdBy != null) 'created_by': supaSerialize(createdBy),
         if (type != null) 'type': supaSerialize(type),
         if (title != null) 'title': supaSerialize(title),
         if (text != null) 'text': supaSerialize(text),
         if (thumbnailBucket != null)
           'thumbnail_bucket': supaSerialize(thumbnailBucket),
         if (thumbnailFolderPath != null)
           'thumbnail_folder_path': supaSerialize(thumbnailFolderPath),
         if (thumbnailFilename != null)
           'thumbnail_filename': supaSerialize(thumbnailFilename),
         if (awardPoints != null) 'award_points': supaSerialize(awardPoints),
         if (order != null) 'order': supaSerialize(order),
         if (taskExplanation != null)
           'task_explanation': supaSerialize(taskExplanation),
         if (doNotDoExplanation != null)
           'do_not_do_explanation': supaSerialize(doNotDoExplanation),
         if (participationButtonText != null)
           'participation_button_text': supaSerialize(participationButtonText),
         if (name != null) 'name': supaSerialize(name),
         if (carbonEmissionsReductionPerParticipationG != null)
           'carbon_emissions_reduction_per_participation_g': supaSerialize(
             carbonEmissionsReductionPerParticipationG,
           ),
         if (startActiveDate != null)
           'start_active_date': supaSerialize(startActiveDate),
         if (lastActiveDate != null)
           'last_active_date': supaSerialize(lastActiveDate),
         if (publicity != null) 'publicity': supaSerialize(publicity),
         if (isPublished != null) 'is_published': supaSerialize(isPublished),
         if (stamp != null) 'stamp': supaSerialize(stamp),
         if (submittedForReviewAt != null)
           'submitted_for_review_at': supaSerialize(submittedForReviewAt),
         if (approvedAt != null) 'approved_at': supaSerialize(approvedAt),
         if (approvedBy != null) 'approved_by': supaSerialize(approvedBy),
         if (rejectedAt != null) 'rejected_at': supaSerialize(rejectedAt),
         if (rejectedBy != null) 'rejected_by': supaSerialize(rejectedBy),
         if (isDeleted != null) 'is_deleted': supaSerialize(isDeleted),
         if (rejectedReason != null)
           'rejected_reason': supaSerialize(rejectedReason),
         if (companyId != null) 'company_id': supaSerialize(companyId),
       });

  /// Mission Row
  const MissionRow._(super.data);

  /// Create Mission Row from a [data] map
  factory MissionRow.fromJson(Map<String, dynamic> data) =>
      MissionRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => MissionTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Created By field name
  static const String createdByField = 'created_by';

  /// Created By
  String get createdBy =>
      getField<String>(createdByField, defaultValue: 'auth.')!;
  set createdBy(String value) => setField<String>(createdByField, value);

  /// Type field name
  static const String typeField = 'type';

  /// Type
  MissionType get type => getField<MissionType>(
    typeField,
    enumValues: MissionType.values,
    defaultValue: MissionType.general,
  )!;
  set type(MissionType value) => setField<MissionType>(typeField, value);

  /// Title field name
  static const String titleField = 'title';

  /// Title
  String? get title => getField<String>(titleField);
  set title(String? value) => setField<String>(titleField, value);

  /// Text field name
  static const String textField = 'text';

  /// Text
  String? get text => getField<String>(textField);
  set text(String? value) => setField<String>(textField, value);

  /// Thumbnail Bucket field name
  static const String thumbnailBucketField = 'thumbnail_bucket';

  /// Thumbnail Bucket
  String? get thumbnailBucket => getField<String>(thumbnailBucketField);
  set thumbnailBucket(String? value) =>
      setField<String>(thumbnailBucketField, value);

  /// Thumbnail Folder Path field name
  static const String thumbnailFolderPathField = 'thumbnail_folder_path';

  /// Thumbnail Folder Path
  String? get thumbnailFolderPath => getField<String>(thumbnailFolderPathField);
  set thumbnailFolderPath(String? value) =>
      setField<String>(thumbnailFolderPathField, value);

  /// Thumbnail Filename field name
  static const String thumbnailFilenameField = 'thumbnail_filename';

  /// Thumbnail Filename
  String? get thumbnailFilename => getField<String>(thumbnailFilenameField);
  set thumbnailFilename(String? value) =>
      setField<String>(thumbnailFilenameField, value);

  /// Award Points field name
  static const String awardPointsField = 'award_points';

  /// Award Points
  int get awardPoints => getField<int>(awardPointsField, defaultValue: 0)!;
  set awardPoints(int value) => setField<int>(awardPointsField, value);

  /// Order field name
  static const String orderField = 'order';

  /// Order
  int get order => getField<int>(orderField, defaultValue: 0)!;
  set order(int value) => setField<int>(orderField, value);

  /// Task Explanation field name
  static const String taskExplanationField = 'task_explanation';

  /// Task Explanation
  String? get taskExplanation => getField<String>(taskExplanationField);
  set taskExplanation(String? value) =>
      setField<String>(taskExplanationField, value);

  /// Do Not Do Explanation field name
  static const String doNotDoExplanationField = 'do_not_do_explanation';

  /// Do Not Do Explanation
  String? get doNotDoExplanation => getField<String>(doNotDoExplanationField);
  set doNotDoExplanation(String? value) =>
      setField<String>(doNotDoExplanationField, value);

  /// Participation Button Text field name
  static const String participationButtonTextField =
      'participation_button_text';

  /// Participation Button Text
  String? get participationButtonText =>
      getField<String>(participationButtonTextField);
  set participationButtonText(String? value) =>
      setField<String>(participationButtonTextField, value);

  /// Name field name
  static const String nameField = 'name';

  /// Name
  String? get name => getField<String>(nameField);
  set name(String? value) => setField<String>(nameField, value);

  /// Carbon Emissions Reduction Per Participation G field name
  static const String carbonEmissionsReductionPerParticipationGField =
      'carbon_emissions_reduction_per_participation_g';

  /// Carbon Emissions Reduction Per Participation G
  double get carbonEmissionsReductionPerParticipationG => getField<double>(
    carbonEmissionsReductionPerParticipationGField,
    defaultValue: 0,
  )!;
  set carbonEmissionsReductionPerParticipationG(double value) =>
      setField<double>(carbonEmissionsReductionPerParticipationGField, value);

  /// Start Active Date field name
  static const String startActiveDateField = 'start_active_date';

  /// Start Active Date
  String? get startActiveDate => getField<String>(startActiveDateField);
  set startActiveDate(String? value) =>
      setField<String>(startActiveDateField, value);

  /// Last Active Date field name
  static const String lastActiveDateField = 'last_active_date';

  /// Last Active Date
  String? get lastActiveDate => getField<String>(lastActiveDateField);
  set lastActiveDate(String? value) =>
      setField<String>(lastActiveDateField, value);

  /// Publicity field name
  static const String publicityField = 'publicity';

  /// Publicity
  MissionPublicity get publicity => getField<MissionPublicity>(
    publicityField,
    enumValues: MissionPublicity.values,
    defaultValue: MissionPublicity.public,
  )!;
  set publicity(MissionPublicity value) =>
      setField<MissionPublicity>(publicityField, value);

  /// Is Published field name
  static const String isPublishedField = 'is_published';

  /// Is Published
  bool get isPublished =>
      getField<bool>(isPublishedField, defaultValue: false)!;
  set isPublished(bool value) => setField<bool>(isPublishedField, value);

  /// Stamp field name
  static const String stampField = 'stamp';

  /// Stamp
  String? get stamp => getField<String>(stampField);
  set stamp(String? value) => setField<String>(stampField, value);

  /// Submitted For Review At field name
  static const String submittedForReviewAtField = 'submitted_for_review_at';

  /// Submitted For Review At
  DateTime? get submittedForReviewAt =>
      getField<DateTime>(submittedForReviewAtField);
  set submittedForReviewAt(DateTime? value) =>
      setField<DateTime>(submittedForReviewAtField, value);

  /// Approved At field name
  static const String approvedAtField = 'approved_at';

  /// Approved At
  DateTime? get approvedAt => getField<DateTime>(approvedAtField);
  set approvedAt(DateTime? value) => setField<DateTime>(approvedAtField, value);

  /// Approved By field name
  static const String approvedByField = 'approved_by';

  /// Approved By
  String? get approvedBy => getField<String>(approvedByField);
  set approvedBy(String? value) => setField<String>(approvedByField, value);

  /// Rejected At field name
  static const String rejectedAtField = 'rejected_at';

  /// Rejected At
  DateTime? get rejectedAt => getField<DateTime>(rejectedAtField);
  set rejectedAt(DateTime? value) => setField<DateTime>(rejectedAtField, value);

  /// Rejected By field name
  static const String rejectedByField = 'rejected_by';

  /// Rejected By
  String? get rejectedBy => getField<String>(rejectedByField);
  set rejectedBy(String? value) => setField<String>(rejectedByField, value);

  /// Is Deleted field name
  static const String isDeletedField = 'is_deleted';

  /// Is Deleted
  bool get isDeleted => getField<bool>(isDeletedField, defaultValue: false)!;
  set isDeleted(bool value) => setField<bool>(isDeletedField, value);

  /// Rejected Reason field name
  static const String rejectedReasonField = 'rejected_reason';

  /// Rejected Reason
  String? get rejectedReason => getField<String>(rejectedReasonField);
  set rejectedReason(String? value) =>
      setField<String>(rejectedReasonField, value);

  /// Company Id field name
  static const String companyIdField = 'company_id';

  /// Company Id
  String? get companyId => getField<String>(companyIdField);
  set companyId(String? value) => setField<String>(companyIdField, value);

  /// Make a copy of the current [MissionRow]
  /// overriding the provided fields
  MissionRow copyWith({
    String? id,
    DateTime? createdAt,
    String? createdBy,
    MissionType? type,
    String? title,
    String? text,
    String? thumbnailBucket,
    String? thumbnailFolderPath,
    String? thumbnailFilename,
    int? awardPoints,
    int? order,
    String? taskExplanation,
    String? doNotDoExplanation,
    String? participationButtonText,
    String? name,
    double? carbonEmissionsReductionPerParticipationG,
    String? startActiveDate,
    String? lastActiveDate,
    MissionPublicity? publicity,
    bool? isPublished,
    String? stamp,
    DateTime? submittedForReviewAt,
    DateTime? approvedAt,
    String? approvedBy,
    DateTime? rejectedAt,
    String? rejectedBy,
    bool? isDeleted,
    String? rejectedReason,
    String? companyId,
  }) => MissionRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'created_by': supaSerialize(createdBy) ?? data['created_by'],
    'type': supaSerialize(type) ?? data['type'],
    'title': supaSerialize(title) ?? data['title'],
    'text': supaSerialize(text) ?? data['text'],
    'thumbnail_bucket':
        supaSerialize(thumbnailBucket) ?? data['thumbnail_bucket'],
    'thumbnail_folder_path':
        supaSerialize(thumbnailFolderPath) ?? data['thumbnail_folder_path'],
    'thumbnail_filename':
        supaSerialize(thumbnailFilename) ?? data['thumbnail_filename'],
    'award_points': supaSerialize(awardPoints) ?? data['award_points'],
    'order': supaSerialize(order) ?? data['order'],
    'task_explanation':
        supaSerialize(taskExplanation) ?? data['task_explanation'],
    'do_not_do_explanation':
        supaSerialize(doNotDoExplanation) ?? data['do_not_do_explanation'],
    'participation_button_text':
        supaSerialize(participationButtonText) ??
        data['participation_button_text'],
    'name': supaSerialize(name) ?? data['name'],
    'carbon_emissions_reduction_per_participation_g':
        supaSerialize(carbonEmissionsReductionPerParticipationG) ??
        data['carbon_emissions_reduction_per_participation_g'],
    'start_active_date':
        supaSerialize(startActiveDate) ?? data['start_active_date'],
    'last_active_date':
        supaSerialize(lastActiveDate) ?? data['last_active_date'],
    'publicity': supaSerialize(publicity) ?? data['publicity'],
    'is_published': supaSerialize(isPublished) ?? data['is_published'],
    'stamp': supaSerialize(stamp) ?? data['stamp'],
    'submitted_for_review_at':
        supaSerialize(submittedForReviewAt) ?? data['submitted_for_review_at'],
    'approved_at': supaSerialize(approvedAt) ?? data['approved_at'],
    'approved_by': supaSerialize(approvedBy) ?? data['approved_by'],
    'rejected_at': supaSerialize(rejectedAt) ?? data['rejected_at'],
    'rejected_by': supaSerialize(rejectedBy) ?? data['rejected_by'],
    'is_deleted': supaSerialize(isDeleted) ?? data['is_deleted'],
    'rejected_reason': supaSerialize(rejectedReason) ?? data['rejected_reason'],
    'company_id': supaSerialize(companyId) ?? data['company_id'],
  });
}

/// Tag: v2
/// Date: 2025-12-23 14:25:57.797914
