//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Mission Photo Promotional Table
class MissionPhotoPromotionalTable
    extends SupabaseTable<MissionPhotoPromotionalRow> {
  /// Table Name
  @override
  String get tableName => 'mission_photo_promotional';

  /// Create a [MissionPhotoPromotionalRow] from the [data] provided
  @override
  MissionPhotoPromotionalRow createRow(Map<String, dynamic> data) =>
      MissionPhotoPromotionalRow.fromJson(data);
}

/// Mission Photo Promotional Row
class MissionPhotoPromotionalRow extends SupabaseDataRow {
  /// Mission Photo Promotional Row
  MissionPhotoPromotionalRow({
    required String folderPath,
    required String fileName,
    required String mission,
    String? id,
    String? bucket,
    DateTime? createdAt,
    String? createdBy,
    int? order,
  }) : super({
         'folder_path': supaSerialize(folderPath),
         'file_name': supaSerialize(fileName),
         'mission': supaSerialize(mission),
         if (id != null) 'id': supaSerialize(id),
         if (bucket != null) 'bucket': supaSerialize(bucket),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (createdBy != null) 'created_by': supaSerialize(createdBy),
         if (order != null) 'order': supaSerialize(order),
       });

  /// Mission Photo Promotional Row
  const MissionPhotoPromotionalRow._(super.data);

  /// Create Mission Photo Promotional Row from a [data] map
  factory MissionPhotoPromotionalRow.fromJson(Map<String, dynamic> data) =>
      MissionPhotoPromotionalRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => MissionPhotoPromotionalTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Bucket field name
  static const String bucketField = 'bucket';

  /// Bucket
  String get bucket => getField<String>(bucketField, defaultValue: 'mission')!;
  set bucket(String value) => setField<String>(bucketField, value);

  /// Folder Path field name
  static const String folderPathField = 'folder_path';

  /// Folder Path
  String get folderPath => getField<String>(folderPathField)!;
  set folderPath(String value) => setField<String>(folderPathField, value);

  /// File Name field name
  static const String fileNameField = 'file_name';

  /// File Name
  String get fileName => getField<String>(fileNameField)!;
  set fileName(String value) => setField<String>(fileNameField, value);

  /// Mission field name
  static const String missionField = 'mission';

  /// Mission
  String get mission => getField<String>(missionField)!;
  set mission(String value) => setField<String>(missionField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Created By field name
  static const String createdByField = 'created_by';

  /// Created By
  String get createdBy =>
      getField<String>(createdByField, defaultValue: 'auth.')!;
  set createdBy(String value) => setField<String>(createdByField, value);

  /// Order field name
  static const String orderField = 'order';

  /// Order
  int get order => getField<int>(orderField, defaultValue: 0)!;
  set order(int value) => setField<int>(orderField, value);

  /// Make a copy of the current [MissionPhotoPromotionalRow]
  /// overriding the provided fields
  MissionPhotoPromotionalRow copyWith({
    String? folderPath,
    String? fileName,
    String? mission,
    String? id,
    String? bucket,
    DateTime? createdAt,
    String? createdBy,
    int? order,
  }) => MissionPhotoPromotionalRow.fromJson({
    'folder_path': supaSerialize(folderPath) ?? data['folder_path'],
    'file_name': supaSerialize(fileName) ?? data['file_name'],
    'mission': supaSerialize(mission) ?? data['mission'],
    'id': supaSerialize(id) ?? data['id'],
    'bucket': supaSerialize(bucket) ?? data['bucket'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'created_by': supaSerialize(createdBy) ?? data['created_by'],
    'order': supaSerialize(order) ?? data['order'],
  });
}

/// Tag: v2
/// Date: 2025-11-25 09:28:17.055874
