//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Mission Request Table
class MissionRequestTable extends SupabaseTable<MissionRequestRow> {
  /// Table Name
  @override
  String get tableName => 'mission_request';

  /// Create a [MissionRequestRow] from the [data] provided
  @override
  MissionRequestRow createRow(Map<String, dynamic> data) =>
      MissionRequestRow.fromJson(data);
}

/// Mission Request Row
class MissionRequestRow extends SupabaseDataRow {
  /// Mission Request Row
  MissionRequestRow({
    String? id,
    DateTime? createdAt,
    String? mission,
    String? createdBy,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (mission != null) 'mission': supaSerialize(mission),
         if (createdBy != null) 'created_by': supaSerialize(createdBy),
       });

  /// Mission Request Row
  const MissionRequestRow._(super.data);

  /// Create Mission Request Row from a [data] map
  factory MissionRequestRow.fromJson(Map<String, dynamic> data) =>
      MissionRequestRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => MissionRequestTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Mission field name
  static const String missionField = 'mission';

  /// Mission
  String? get mission => getField<String>(missionField);
  set mission(String? value) => setField<String>(missionField, value);

  /// Created By field name
  static const String createdByField = 'created_by';

  /// Created By
  String get createdBy =>
      getField<String>(createdByField, defaultValue: 'auth.')!;
  set createdBy(String value) => setField<String>(createdByField, value);

  /// Make a copy of the current [MissionRequestRow]
  /// overriding the provided fields
  MissionRequestRow copyWith({
    String? id,
    DateTime? createdAt,
    String? mission,
    String? createdBy,
  }) => MissionRequestRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'mission': supaSerialize(mission) ?? data['mission'],
    'created_by': supaSerialize(createdBy) ?? data['created_by'],
  });
}

/// Tag: v2
/// Date: 2025-12-17 14:31:24.999033
