//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Mission Participation Table
class MissionParticipationTable extends SupabaseTable<MissionParticipationRow> {
  /// Table Name
  @override
  String get tableName => 'mission_participation';

  /// Create a [MissionParticipationRow] from the [data] provided
  @override
  MissionParticipationRow createRow(Map<String, dynamic> data) =>
      MissionParticipationRow.fromJson(data);
}

/// Mission Participation Row
class MissionParticipationRow extends SupabaseDataRow {
  /// Mission Participation Row
  MissionParticipationRow({
    String? id,
    String? participatedBy,
    String? mission,
    DateTime? approvedAt,
    String? approvedBy,
    DateTime? rejectedAt,
    String? rejectedBy,
    String? rejectionReason,
    DateTime? createdAt,
    String? photoBucket,
    String? photoFolderPath,
    String? photoFileName,
    double? awardPoints,
    double? cost,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (participatedBy != null)
           'participated_by': supaSerialize(participatedBy),
         if (mission != null) 'mission': supaSerialize(mission),
         if (approvedAt != null) 'approved_at': supaSerialize(approvedAt),
         if (approvedBy != null) 'approved_by': supaSerialize(approvedBy),
         if (rejectedAt != null) 'rejected_at': supaSerialize(rejectedAt),
         if (rejectedBy != null) 'rejected_by': supaSerialize(rejectedBy),
         if (rejectionReason != null)
           'rejection_reason': supaSerialize(rejectionReason),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (photoBucket != null) 'photo_bucket': supaSerialize(photoBucket),
         if (photoFolderPath != null)
           'photo_folder_path': supaSerialize(photoFolderPath),
         if (photoFileName != null)
           'photo_file_name': supaSerialize(photoFileName),
         if (awardPoints != null) 'award_points': supaSerialize(awardPoints),
         if (cost != null) 'cost': supaSerialize(cost),
       });

  /// Mission Participation Row
  const MissionParticipationRow._(super.data);

  /// Create Mission Participation Row from a [data] map
  factory MissionParticipationRow.fromJson(Map<String, dynamic> data) =>
      MissionParticipationRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => MissionParticipationTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Participated By field name
  static const String participatedByField = 'participated_by';

  /// Participated By
  String get participatedBy =>
      getField<String>(participatedByField, defaultValue: '')!;
  set participatedBy(String value) =>
      setField<String>(participatedByField, value);

  /// Mission field name
  static const String missionField = 'mission';

  /// Mission
  String? get mission => getField<String>(missionField);
  set mission(String? value) => setField<String>(missionField, value);

  /// Approved At field name
  static const String approvedAtField = 'approved_at';

  /// Approved At
  DateTime? get approvedAt => getField<DateTime>(approvedAtField);
  set approvedAt(DateTime? value) => setField<DateTime>(approvedAtField, value);

  /// Approved By field name
  static const String approvedByField = 'approved_by';

  /// Approved By
  String? get approvedBy => getField<String>(approvedByField);
  set approvedBy(String? value) => setField<String>(approvedByField, value);

  /// Rejected At field name
  static const String rejectedAtField = 'rejected_at';

  /// Rejected At
  DateTime get rejectedAt =>
      getField<DateTime>(rejectedAtField, defaultValue: DateTime.now())!;
  set rejectedAt(DateTime value) => setField<DateTime>(rejectedAtField, value);

  /// Rejected By field name
  static const String rejectedByField = 'rejected_by';

  /// Rejected By
  String? get rejectedBy => getField<String>(rejectedByField);
  set rejectedBy(String? value) => setField<String>(rejectedByField, value);

  /// Rejection Reason field name
  static const String rejectionReasonField = 'rejection_reason';

  /// Rejection Reason
  String? get rejectionReason => getField<String>(rejectionReasonField);
  set rejectionReason(String? value) =>
      setField<String>(rejectionReasonField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Photo Bucket field name
  static const String photoBucketField = 'photo_bucket';

  /// Photo Bucket
  String? get photoBucket => getField<String>(photoBucketField);
  set photoBucket(String? value) => setField<String>(photoBucketField, value);

  /// Photo Folder Path field name
  static const String photoFolderPathField = 'photo_folder_path';

  /// Photo Folder Path
  String? get photoFolderPath => getField<String>(photoFolderPathField);
  set photoFolderPath(String? value) =>
      setField<String>(photoFolderPathField, value);

  /// Photo File Name field name
  static const String photoFileNameField = 'photo_file_name';

  /// Photo File Name
  String? get photoFileName => getField<String>(photoFileNameField);
  set photoFileName(String? value) =>
      setField<String>(photoFileNameField, value);

  /// Award Points field name
  static const String awardPointsField = 'award_points';

  /// Award Points
  double? get awardPoints => getField<double>(awardPointsField);
  set awardPoints(double? value) => setField<double>(awardPointsField, value);

  /// Cost field name
  static const String costField = 'cost';

  /// Cost
  double? get cost => getField<double>(costField);
  set cost(double? value) => setField<double>(costField, value);

  /// Make a copy of the current [MissionParticipationRow]
  /// overriding the provided fields
  MissionParticipationRow copyWith({
    String? id,
    String? participatedBy,
    String? mission,
    DateTime? approvedAt,
    String? approvedBy,
    DateTime? rejectedAt,
    String? rejectedBy,
    String? rejectionReason,
    DateTime? createdAt,
    String? photoBucket,
    String? photoFolderPath,
    String? photoFileName,
    double? awardPoints,
    double? cost,
  }) => MissionParticipationRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'participated_by': supaSerialize(participatedBy) ?? data['participated_by'],
    'mission': supaSerialize(mission) ?? data['mission'],
    'approved_at': supaSerialize(approvedAt) ?? data['approved_at'],
    'approved_by': supaSerialize(approvedBy) ?? data['approved_by'],
    'rejected_at': supaSerialize(rejectedAt) ?? data['rejected_at'],
    'rejected_by': supaSerialize(rejectedBy) ?? data['rejected_by'],
    'rejection_reason':
        supaSerialize(rejectionReason) ?? data['rejection_reason'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'photo_bucket': supaSerialize(photoBucket) ?? data['photo_bucket'],
    'photo_folder_path':
        supaSerialize(photoFolderPath) ?? data['photo_folder_path'],
    'photo_file_name': supaSerialize(photoFileName) ?? data['photo_file_name'],
    'award_points': supaSerialize(awardPoints) ?? data['award_points'],
    'cost': supaSerialize(cost) ?? data['cost'],
  });
}

/// Tag: v2
/// Date: 2026-01-27 15:18:18.827732
