//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Mission Clicks Table
class MissionClicksTable extends SupabaseTable<MissionClicksRow> {
  /// Table Name
  @override
  String get tableName => 'mission_clicks';

  /// Create a [MissionClicksRow] from the [data] provided
  @override
  MissionClicksRow createRow(Map<String, dynamic> data) =>
      MissionClicksRow.fromJson(data);
}

/// Mission Clicks Row
class MissionClicksRow extends SupabaseDataRow {
  /// Mission Clicks Row
  MissionClicksRow({
    String? id,
    DateTime? createdAt,
    String? mission,
    String? user,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (mission != null) 'mission': supaSerialize(mission),
         if (user != null) 'user': supaSerialize(user),
       });

  /// Mission Clicks Row
  const MissionClicksRow._(super.data);

  /// Create Mission Clicks Row from a [data] map
  factory MissionClicksRow.fromJson(Map<String, dynamic> data) =>
      MissionClicksRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => MissionClicksTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Mission field name
  static const String missionField = 'mission';

  /// Mission
  String? get mission => getField<String>(missionField);
  set mission(String? value) => setField<String>(missionField, value);

  /// User field name
  static const String userField = 'user';

  /// User
  String? get user => getField<String>(userField);
  set user(String? value) => setField<String>(userField, value);

  /// Make a copy of the current [MissionClicksRow]
  /// overriding the provided fields
  MissionClicksRow copyWith({
    String? id,
    DateTime? createdAt,
    String? mission,
    String? user,
  }) => MissionClicksRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'mission': supaSerialize(mission) ?? data['mission'],
    'user': supaSerialize(user) ?? data['user'],
  });
}

/// Tag: v2
/// Date: 2026-01-12 14:27:53.913887
