//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Order Item Table
class OrderItemTable extends SupabaseTable<OrderItemRow> {
  /// Table Name
  @override
  String get tableName => 'order_item';

  /// Create a [OrderItemRow] from the [data] provided
  @override
  OrderItemRow createRow(Map<String, dynamic> data) =>
      OrderItemRow.fromJson(data);
}

/// Order Item Row
class OrderItemRow extends SupabaseDataRow {
  /// Order Item Row
  OrderItemRow({
    String? id,
    DateTime? createdAt,
    String? product,
    double? quantity,
    String? order,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (product != null) 'product': supaSerialize(product),
         if (quantity != null) 'quantity': supaSerialize(quantity),
         if (order != null) 'order': supaSerialize(order),
       });

  /// Order Item Row
  const OrderItemRow._(super.data);

  /// Create Order Item Row from a [data] map
  factory OrderItemRow.fromJson(Map<String, dynamic> data) =>
      OrderItemRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => OrderItemTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Product field name
  static const String productField = 'product';

  /// Product
  String? get product => getField<String>(productField);
  set product(String? value) => setField<String>(productField, value);

  /// Quantity field name
  static const String quantityField = 'quantity';

  /// Quantity
  double? get quantity => getField<double>(quantityField);
  set quantity(double? value) => setField<double>(quantityField, value);

  /// Order field name
  static const String orderField = 'order';

  /// Order
  String? get order => getField<String>(orderField);
  set order(String? value) => setField<String>(orderField, value);

  /// Make a copy of the current [OrderItemRow]
  /// overriding the provided fields
  OrderItemRow copyWith({
    String? id,
    DateTime? createdAt,
    String? product,
    double? quantity,
    String? order,
  }) => OrderItemRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'product': supaSerialize(product) ?? data['product'],
    'quantity': supaSerialize(quantity) ?? data['quantity'],
    'order': supaSerialize(order) ?? data['order'],
  });
}

/// Tag: v2
/// Date: 2025-12-17 14:31:24.999591
