//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Order Table
class OrderTable extends SupabaseTable<OrderRow> {
  /// Table Name
  @override
  String get tableName => 'order';

  /// Create a [OrderRow] from the [data] provided
  @override
  OrderRow createRow(Map<String, dynamic> data) => OrderRow.fromJson(data);
}

/// Order Row
class OrderRow extends SupabaseDataRow {
  /// Order Row
  OrderRow({
    String? id,
    DateTime? createdAt,
    String? orderBy,
    String? shippingAddress,
    String? payment,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (orderBy != null) 'order_by': supaSerialize(orderBy),
         if (shippingAddress != null)
           'shipping_address': supaSerialize(shippingAddress),
         if (payment != null) 'payment': supaSerialize(payment),
       });

  /// Order Row
  const OrderRow._(super.data);

  /// Create Order Row from a [data] map
  factory OrderRow.fromJson(Map<String, dynamic> data) =>
      OrderRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => OrderTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Order By field name
  static const String orderByField = 'order_by';

  /// Order By
  String? get orderBy => getField<String>(orderByField);
  set orderBy(String? value) => setField<String>(orderByField, value);

  /// Shipping Address field name
  static const String shippingAddressField = 'shipping_address';

  /// Shipping Address
  String? get shippingAddress => getField<String>(shippingAddressField);
  set shippingAddress(String? value) =>
      setField<String>(shippingAddressField, value);

  /// Payment field name
  static const String paymentField = 'payment';

  /// Payment
  String? get payment => getField<String>(paymentField);
  set payment(String? value) => setField<String>(paymentField, value);

  /// Make a copy of the current [OrderRow]
  /// overriding the provided fields
  OrderRow copyWith({
    String? id,
    DateTime? createdAt,
    String? orderBy,
    String? shippingAddress,
    String? payment,
  }) => OrderRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'order_by': supaSerialize(orderBy) ?? data['order_by'],
    'shipping_address':
        supaSerialize(shippingAddress) ?? data['shipping_address'],
    'payment': supaSerialize(payment) ?? data['payment'],
  });
}

/// Tag: v2
/// Date: 2026-01-05 16:52:08.903995
