//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Order Item Option Table
class OrderItemOptionTable extends SupabaseTable<OrderItemOptionRow> {
  /// Table Name
  @override
  String get tableName => 'order_item_option';

  /// Create a [OrderItemOptionRow] from the [data] provided
  @override
  OrderItemOptionRow createRow(Map<String, dynamic> data) =>
      OrderItemOptionRow.fromJson(data);
}

/// Order Item Option Row
class OrderItemOptionRow extends SupabaseDataRow {
  /// Order Item Option Row
  OrderItemOptionRow({
    required int id,
    DateTime? createdAt,
    String? orderItem,
    String? optionParameter,
    String? optionValue,
  }) : super({
         'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (orderItem != null) 'order_item': supaSerialize(orderItem),
         if (optionParameter != null)
           'option_parameter': supaSerialize(optionParameter),
         if (optionValue != null) 'option_value': supaSerialize(optionValue),
       });

  /// Order Item Option Row
  const OrderItemOptionRow._(super.data);

  /// Create Order Item Option Row from a [data] map
  factory OrderItemOptionRow.fromJson(Map<String, dynamic> data) =>
      OrderItemOptionRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => OrderItemOptionTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  int get id => getField<int>(idField)!;
  set id(int value) => setField<int>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Order Item field name
  static const String orderItemField = 'order_item';

  /// Order Item
  String? get orderItem => getField<String>(orderItemField);
  set orderItem(String? value) => setField<String>(orderItemField, value);

  /// Option Parameter field name
  static const String optionParameterField = 'option_parameter';

  /// Option Parameter
  String? get optionParameter => getField<String>(optionParameterField);
  set optionParameter(String? value) =>
      setField<String>(optionParameterField, value);

  /// Option Value field name
  static const String optionValueField = 'option_value';

  /// Option Value
  String? get optionValue => getField<String>(optionValueField);
  set optionValue(String? value) => setField<String>(optionValueField, value);

  /// Make a copy of the current [OrderItemOptionRow]
  /// overriding the provided fields
  OrderItemOptionRow copyWith({
    int? id,
    DateTime? createdAt,
    String? orderItem,
    String? optionParameter,
    String? optionValue,
  }) => OrderItemOptionRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'order_item': supaSerialize(orderItem) ?? data['order_item'],
    'option_parameter':
        supaSerialize(optionParameter) ?? data['option_parameter'],
    'option_value': supaSerialize(optionValue) ?? data['option_value'],
  });
}

/// Tag: v2
/// Date: 2026-02-20 11:42:15.171157
