//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Order Item Inquiry Message Table
class OrderItemInquiryMessageTable
    extends SupabaseTable<OrderItemInquiryMessageRow> {
  /// Table Name
  @override
  String get tableName => 'order_item_inquiry_message';

  /// Create a [OrderItemInquiryMessageRow] from the [data] provided
  @override
  OrderItemInquiryMessageRow createRow(Map<String, dynamic> data) =>
      OrderItemInquiryMessageRow.fromJson(data);
}

/// Order Item Inquiry Message Row
class OrderItemInquiryMessageRow extends SupabaseDataRow {
  /// Order Item Inquiry Message Row
  OrderItemInquiryMessageRow({
    String? id,
    String? orderItem,
    String? text,
    String? createdBy,
    DateTime? createdAt,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (orderItem != null) 'order_item': supaSerialize(orderItem),
         if (text != null) 'text': supaSerialize(text),
         if (createdBy != null) 'created_by': supaSerialize(createdBy),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
       });

  /// Order Item Inquiry Message Row
  const OrderItemInquiryMessageRow._(super.data);

  /// Create Order Item Inquiry Message Row from a [data] map
  factory OrderItemInquiryMessageRow.fromJson(Map<String, dynamic> data) =>
      OrderItemInquiryMessageRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => OrderItemInquiryMessageTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Order Item field name
  static const String orderItemField = 'order_item';

  /// Order Item
  String? get orderItem => getField<String>(orderItemField);
  set orderItem(String? value) => setField<String>(orderItemField, value);

  /// Text field name
  static const String textField = 'text';

  /// Text
  String? get text => getField<String>(textField);
  set text(String? value) => setField<String>(textField, value);

  /// Created By field name
  static const String createdByField = 'created_by';

  /// Created By
  String? get createdBy => getField<String>(createdByField);
  set createdBy(String? value) => setField<String>(createdByField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Make a copy of the current [OrderItemInquiryMessageRow]
  /// overriding the provided fields
  OrderItemInquiryMessageRow copyWith({
    String? id,
    String? orderItem,
    String? text,
    String? createdBy,
    DateTime? createdAt,
  }) => OrderItemInquiryMessageRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'order_item': supaSerialize(orderItem) ?? data['order_item'],
    'text': supaSerialize(text) ?? data['text'],
    'created_by': supaSerialize(createdBy) ?? data['created_by'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
  });
}

/// Tag: v2
/// Date: 2026-03-13 15:28:25.392753
