//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Organization Table
class OrganizationTable extends SupabaseTable<OrganizationRow> {
  /// Table Name
  @override
  String get tableName => 'organization';

  /// Create a [OrganizationRow] from the [data] provided
  @override
  OrganizationRow createRow(Map<String, dynamic> data) =>
      OrganizationRow.fromJson(data);
}

/// Organization Row
class OrganizationRow extends SupabaseDataRow {
  /// Organization Row
  OrganizationRow({
    String? id,
    DateTime? createdAt,
    String? name,
    String? createdBy,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (name != null) 'name': supaSerialize(name),
         if (createdBy != null) 'created_by': supaSerialize(createdBy),
       });

  /// Organization Row
  const OrganizationRow._(super.data);

  /// Create Organization Row from a [data] map
  factory OrganizationRow.fromJson(Map<String, dynamic> data) =>
      OrganizationRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => OrganizationTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Name field name
  static const String nameField = 'name';

  /// Name
  String? get name => getField<String>(nameField);
  set name(String? value) => setField<String>(nameField, value);

  /// Created By field name
  static const String createdByField = 'created_by';

  /// Created By
  String get createdBy =>
      getField<String>(createdByField, defaultValue: 'auth.')!;
  set createdBy(String value) => setField<String>(createdByField, value);

  /// Make a copy of the current [OrganizationRow]
  /// overriding the provided fields
  OrganizationRow copyWith({
    String? id,
    DateTime? createdAt,
    String? name,
    String? createdBy,
  }) => OrganizationRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'name': supaSerialize(name) ?? data['name'],
    'created_by': supaSerialize(createdBy) ?? data['created_by'],
  });
}

/// Tag: v2
/// Date: 2026-01-08 15:40:00.020953
