//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Payment Table
class PaymentTable extends SupabaseTable<PaymentRow> {
  /// Table Name
  @override
  String get tableName => 'payment';

  /// Create a [PaymentRow] from the [data] provided
  @override
  PaymentRow createRow(Map<String, dynamic> data) => PaymentRow.fromJson(data);
}

/// Payment Row
class PaymentRow extends SupabaseDataRow {
  /// Payment Row
  PaymentRow({
    String? id,
    String? paymentBy,
    String? platformId,
    DateTime? paidAt,
    DateTime? createdAt,
    double? amount,
    String? status,
    dynamic otherData,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (paymentBy != null) 'payment_by': supaSerialize(paymentBy),
         if (platformId != null) 'platform_id': supaSerialize(platformId),
         if (paidAt != null) 'paid_at': supaSerialize(paidAt),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (amount != null) 'amount': supaSerialize(amount),
         if (status != null) 'status': supaSerialize(status),
         if (otherData != null) 'other_data': supaSerialize(otherData),
       });

  /// Payment Row
  const PaymentRow._(super.data);

  /// Create Payment Row from a [data] map
  factory PaymentRow.fromJson(Map<String, dynamic> data) =>
      PaymentRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => PaymentTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Payment By field name
  static const String paymentByField = 'payment_by';

  /// Payment By
  String? get paymentBy => getField<String>(paymentByField);
  set paymentBy(String? value) => setField<String>(paymentByField, value);

  /// Platform Id field name
  static const String platformIdField = 'platform_id';

  /// Platform Id
  String? get platformId => getField<String>(platformIdField);
  set platformId(String? value) => setField<String>(platformIdField, value);

  /// Paid At field name
  static const String paidAtField = 'paid_at';

  /// Paid At
  DateTime? get paidAt => getField<DateTime>(paidAtField);
  set paidAt(DateTime? value) => setField<DateTime>(paidAtField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Amount field name
  static const String amountField = 'amount';

  /// Amount
  double? get amount => getField<double>(amountField);
  set amount(double? value) => setField<double>(amountField, value);

  /// Status field name
  static const String statusField = 'status';

  /// Status
  String? get status => getField<String>(statusField);
  set status(String? value) => setField<String>(statusField, value);

  /// Other Data field name
  static const String otherDataField = 'other_data';

  /// Other Data
  dynamic get otherData => getField<dynamic>(otherDataField);
  set otherData(dynamic value) => setField<dynamic>(otherDataField, value);

  /// Make a copy of the current [PaymentRow]
  /// overriding the provided fields
  PaymentRow copyWith({
    String? id,
    String? paymentBy,
    String? platformId,
    DateTime? paidAt,
    DateTime? createdAt,
    double? amount,
    String? status,
    dynamic otherData,
  }) => PaymentRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'payment_by': supaSerialize(paymentBy) ?? data['payment_by'],
    'platform_id': supaSerialize(platformId) ?? data['platform_id'],
    'paid_at': supaSerialize(paidAt) ?? data['paid_at'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'amount': supaSerialize(amount) ?? data['amount'],
    'status': supaSerialize(status) ?? data['status'],
    'other_data': supaSerialize(otherData) ?? data['other_data'],
  });
}

/// Tag: v2
/// Date: 2026-01-16 16:59:29.532645
