//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Popup Table
class PopupTable extends SupabaseTable<PopupRow> {
  /// Table Name
  @override
  String get tableName => 'popup';

  /// Create a [PopupRow] from the [data] provided
  @override
  PopupRow createRow(Map<String, dynamic> data) => PopupRow.fromJson(data);
}

/// Popup Row
class PopupRow extends SupabaseDataRow {
  /// Popup Row
  PopupRow({
    String? id,
    DateTime? createdAt,
    String? createdBy,
    String? title,
    String? body,
    String? photoBucket,
    String? photoFolderPath,
    String? photoFileName,
    bool? hasLinkButton,
    String? linkButtonText,
    String? linkButtonUrl,
    DateTime? scheduleStartAt,
    DateTime? scheduleEndAfter,
    bool? isDraft,
    bool? isDeleted,
    String? companyId,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (createdBy != null) 'created_by': supaSerialize(createdBy),
         if (title != null) 'title': supaSerialize(title),
         if (body != null) 'body': supaSerialize(body),
         if (photoBucket != null) 'photo_bucket': supaSerialize(photoBucket),
         if (photoFolderPath != null)
           'photo_folder_path': supaSerialize(photoFolderPath),
         if (photoFileName != null)
           'photo_file_name': supaSerialize(photoFileName),
         if (hasLinkButton != null)
           'has_link_button': supaSerialize(hasLinkButton),
         if (linkButtonText != null)
           'link_button_text': supaSerialize(linkButtonText),
         if (linkButtonUrl != null)
           'link_button_url': supaSerialize(linkButtonUrl),
         if (scheduleStartAt != null)
           'schedule_start_at': supaSerialize(scheduleStartAt),
         if (scheduleEndAfter != null)
           'schedule_end_after': supaSerialize(scheduleEndAfter),
         if (isDraft != null) 'is_draft': supaSerialize(isDraft),
         if (isDeleted != null) 'is_deleted': supaSerialize(isDeleted),
         if (companyId != null) 'company_id': supaSerialize(companyId),
       });

  /// Popup Row
  const PopupRow._(super.data);

  /// Create Popup Row from a [data] map
  factory PopupRow.fromJson(Map<String, dynamic> data) =>
      PopupRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => PopupTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Created By field name
  static const String createdByField = 'created_by';

  /// Created By
  String get createdBy =>
      getField<String>(createdByField, defaultValue: 'auth.')!;
  set createdBy(String value) => setField<String>(createdByField, value);

  /// Title field name
  static const String titleField = 'title';

  /// Title
  String? get title => getField<String>(titleField);
  set title(String? value) => setField<String>(titleField, value);

  /// Body field name
  static const String bodyField = 'body';

  /// Body
  String? get body => getField<String>(bodyField);
  set body(String? value) => setField<String>(bodyField, value);

  /// Photo Bucket field name
  static const String photoBucketField = 'photo_bucket';

  /// Photo Bucket
  String? get photoBucket => getField<String>(photoBucketField);
  set photoBucket(String? value) => setField<String>(photoBucketField, value);

  /// Photo Folder Path field name
  static const String photoFolderPathField = 'photo_folder_path';

  /// Photo Folder Path
  String? get photoFolderPath => getField<String>(photoFolderPathField);
  set photoFolderPath(String? value) =>
      setField<String>(photoFolderPathField, value);

  /// Photo File Name field name
  static const String photoFileNameField = 'photo_file_name';

  /// Photo File Name
  String? get photoFileName => getField<String>(photoFileNameField);
  set photoFileName(String? value) =>
      setField<String>(photoFileNameField, value);

  /// Has Link Button field name
  static const String hasLinkButtonField = 'has_link_button';

  /// Has Link Button
  bool? get hasLinkButton => getField<bool>(hasLinkButtonField);
  set hasLinkButton(bool? value) => setField<bool>(hasLinkButtonField, value);

  /// Link Button Text field name
  static const String linkButtonTextField = 'link_button_text';

  /// Link Button Text
  String? get linkButtonText => getField<String>(linkButtonTextField);
  set linkButtonText(String? value) =>
      setField<String>(linkButtonTextField, value);

  /// Link Button Url field name
  static const String linkButtonUrlField = 'link_button_url';

  /// Link Button Url
  String? get linkButtonUrl => getField<String>(linkButtonUrlField);
  set linkButtonUrl(String? value) =>
      setField<String>(linkButtonUrlField, value);

  /// Schedule Start At field name
  static const String scheduleStartAtField = 'schedule_start_at';

  /// Schedule Start At
  DateTime? get scheduleStartAt => getField<DateTime>(scheduleStartAtField);
  set scheduleStartAt(DateTime? value) =>
      setField<DateTime>(scheduleStartAtField, value);

  /// Schedule End After field name
  static const String scheduleEndAfterField = 'schedule_end_after';

  /// Schedule End After
  DateTime? get scheduleEndAfter => getField<DateTime>(scheduleEndAfterField);
  set scheduleEndAfter(DateTime? value) =>
      setField<DateTime>(scheduleEndAfterField, value);

  /// Is Draft field name
  static const String isDraftField = 'is_draft';

  /// Is Draft
  bool get isDraft => getField<bool>(isDraftField, defaultValue: true)!;
  set isDraft(bool value) => setField<bool>(isDraftField, value);

  /// Is Deleted field name
  static const String isDeletedField = 'is_deleted';

  /// Is Deleted
  bool get isDeleted => getField<bool>(isDeletedField, defaultValue: false)!;
  set isDeleted(bool value) => setField<bool>(isDeletedField, value);

  /// Company Id field name
  static const String companyIdField = 'company_id';

  /// Company Id
  String? get companyId => getField<String>(companyIdField);
  set companyId(String? value) => setField<String>(companyIdField, value);

  /// Make a copy of the current [PopupRow]
  /// overriding the provided fields
  PopupRow copyWith({
    String? id,
    DateTime? createdAt,
    String? createdBy,
    String? title,
    String? body,
    String? photoBucket,
    String? photoFolderPath,
    String? photoFileName,
    bool? hasLinkButton,
    String? linkButtonText,
    String? linkButtonUrl,
    DateTime? scheduleStartAt,
    DateTime? scheduleEndAfter,
    bool? isDraft,
    bool? isDeleted,
    String? companyId,
  }) => PopupRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'created_by': supaSerialize(createdBy) ?? data['created_by'],
    'title': supaSerialize(title) ?? data['title'],
    'body': supaSerialize(body) ?? data['body'],
    'photo_bucket': supaSerialize(photoBucket) ?? data['photo_bucket'],
    'photo_folder_path':
        supaSerialize(photoFolderPath) ?? data['photo_folder_path'],
    'photo_file_name': supaSerialize(photoFileName) ?? data['photo_file_name'],
    'has_link_button': supaSerialize(hasLinkButton) ?? data['has_link_button'],
    'link_button_text':
        supaSerialize(linkButtonText) ?? data['link_button_text'],
    'link_button_url': supaSerialize(linkButtonUrl) ?? data['link_button_url'],
    'schedule_start_at':
        supaSerialize(scheduleStartAt) ?? data['schedule_start_at'],
    'schedule_end_after':
        supaSerialize(scheduleEndAfter) ?? data['schedule_end_after'],
    'is_draft': supaSerialize(isDraft) ?? data['is_draft'],
    'is_deleted': supaSerialize(isDeleted) ?? data['is_deleted'],
    'company_id': supaSerialize(companyId) ?? data['company_id'],
  });
}

/// Tag: v2
/// Date: 2026-03-12 10:37:49.571828
