//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Product Option Parameter Table
class ProductOptionParameterTable
    extends SupabaseTable<ProductOptionParameterRow> {
  /// Table Name
  @override
  String get tableName => 'product_option_parameter';

  /// Create a [ProductOptionParameterRow] from the [data] provided
  @override
  ProductOptionParameterRow createRow(Map<String, dynamic> data) =>
      ProductOptionParameterRow.fromJson(data);
}

/// Product Option Parameter Row
class ProductOptionParameterRow extends SupabaseDataRow {
  /// Product Option Parameter Row
  ProductOptionParameterRow({
    required String product,
    String? id,
    DateTime? createdAt,
    String? createdBy,
    String? optionParameter,
  }) : super({
         'product': supaSerialize(product),
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (createdBy != null) 'created_by': supaSerialize(createdBy),
         if (optionParameter != null)
           'option_parameter': supaSerialize(optionParameter),
       });

  /// Product Option Parameter Row
  const ProductOptionParameterRow._(super.data);

  /// Create Product Option Parameter Row from a [data] map
  factory ProductOptionParameterRow.fromJson(Map<String, dynamic> data) =>
      ProductOptionParameterRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => ProductOptionParameterTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Created By field name
  static const String createdByField = 'created_by';

  /// Created By
  String? get createdBy => getField<String>(createdByField);
  set createdBy(String? value) => setField<String>(createdByField, value);

  /// Product field name
  static const String productField = 'product';

  /// Product
  String get product => getField<String>(productField)!;
  set product(String value) => setField<String>(productField, value);

  /// Option Parameter field name
  static const String optionParameterField = 'option_parameter';

  /// Option Parameter
  String? get optionParameter => getField<String>(optionParameterField);
  set optionParameter(String? value) =>
      setField<String>(optionParameterField, value);

  /// Make a copy of the current [ProductOptionParameterRow]
  /// overriding the provided fields
  ProductOptionParameterRow copyWith({
    String? product,
    String? id,
    DateTime? createdAt,
    String? createdBy,
    String? optionParameter,
  }) => ProductOptionParameterRow.fromJson({
    'product': supaSerialize(product) ?? data['product'],
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'created_by': supaSerialize(createdBy) ?? data['created_by'],
    'option_parameter':
        supaSerialize(optionParameter) ?? data['option_parameter'],
  });
}

/// Tag: v2
/// Date: 2025-12-01 17:41:38.057573
