//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Product Table
class ProductTable extends SupabaseTable<ProductRow> {
  /// Table Name
  @override
  String get tableName => 'product';

  /// Create a [ProductRow] from the [data] provided
  @override
  ProductRow createRow(Map<String, dynamic> data) => ProductRow.fromJson(data);
}

/// Product Row
class ProductRow extends SupabaseDataRow {
  /// Product Row
  ProductRow({
    DateTime? createdAt,
    String? createdBy,
    String? productBy,
    String? category,
    double? regularPrice,
    String? mainImageBucket,
    String? mainImageFolderPath,
    String? mainImageFileName,
    String? description,
    ProductMaterial? type,
    ProductStyle? style,
    VendorAdminType? vendor,
    String? name,
    String? title,
    String? company,
    String? id,
    bool? isCuration,
    double? additionalDiscountRate,
  }) : super({
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (createdBy != null) 'created_by': supaSerialize(createdBy),
         if (productBy != null) 'product_by': supaSerialize(productBy),
         if (category != null) 'category': supaSerialize(category),
         if (regularPrice != null) 'regular_price': supaSerialize(regularPrice),
         if (mainImageBucket != null)
           'main_image_bucket': supaSerialize(mainImageBucket),
         if (mainImageFolderPath != null)
           'main_image_folder_path': supaSerialize(mainImageFolderPath),
         if (mainImageFileName != null)
           'main_image_file_name': supaSerialize(mainImageFileName),
         if (description != null) 'description': supaSerialize(description),
         if (type != null) 'type': supaSerialize(type),
         if (style != null) 'style': supaSerialize(style),
         if (vendor != null) 'vendor': supaSerialize(vendor),
         if (name != null) 'name': supaSerialize(name),
         if (title != null) 'title': supaSerialize(title),
         if (company != null) 'company': supaSerialize(company),
         if (id != null) 'id': supaSerialize(id),
         if (isCuration != null) 'is_curation': supaSerialize(isCuration),
         if (additionalDiscountRate != null)
           'additional_discount_rate': supaSerialize(additionalDiscountRate),
       });

  /// Product Row
  const ProductRow._(super.data);

  /// Create Product Row from a [data] map
  factory ProductRow.fromJson(Map<String, dynamic> data) =>
      ProductRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => ProductTable();

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Created By field name
  static const String createdByField = 'created_by';

  /// Created By
  String get createdBy =>
      getField<String>(createdByField, defaultValue: 'auth.')!;
  set createdBy(String value) => setField<String>(createdByField, value);

  /// Product By field name
  static const String productByField = 'product_by';

  /// Product By
  String get productBy =>
      getField<String>(productByField, defaultValue: 'auth.')!;
  set productBy(String value) => setField<String>(productByField, value);

  /// Category field name
  static const String categoryField = 'category';

  /// Category
  String? get category => getField<String>(categoryField);
  set category(String? value) => setField<String>(categoryField, value);

  /// Regular Price field name
  static const String regularPriceField = 'regular_price';

  /// Regular Price
  double? get regularPrice => getField<double>(regularPriceField);
  set regularPrice(double? value) => setField<double>(regularPriceField, value);

  /// Main Image Bucket field name
  static const String mainImageBucketField = 'main_image_bucket';

  /// Main Image Bucket
  String? get mainImageBucket => getField<String>(mainImageBucketField);
  set mainImageBucket(String? value) =>
      setField<String>(mainImageBucketField, value);

  /// Main Image Folder Path field name
  static const String mainImageFolderPathField = 'main_image_folder_path';

  /// Main Image Folder Path
  String? get mainImageFolderPath => getField<String>(mainImageFolderPathField);
  set mainImageFolderPath(String? value) =>
      setField<String>(mainImageFolderPathField, value);

  /// Main Image File Name field name
  static const String mainImageFileNameField = 'main_image_file_name';

  /// Main Image File Name
  String? get mainImageFileName => getField<String>(mainImageFileNameField);
  set mainImageFileName(String? value) =>
      setField<String>(mainImageFileNameField, value);

  /// Description field name
  static const String descriptionField = 'description';

  /// Description
  String? get description => getField<String>(descriptionField);
  set description(String? value) => setField<String>(descriptionField, value);

  /// Type field name
  static const String typeField = 'type';

  /// Type
  ProductMaterial? get type =>
      getField<ProductMaterial>(typeField, enumValues: ProductMaterial.values);
  set type(ProductMaterial? value) =>
      setField<ProductMaterial>(typeField, value);

  /// Style field name
  static const String styleField = 'style';

  /// Style
  ProductStyle? get style =>
      getField<ProductStyle>(styleField, enumValues: ProductStyle.values);
  set style(ProductStyle? value) => setField<ProductStyle>(styleField, value);

  /// Vendor field name
  static const String vendorField = 'vendor';

  /// Vendor
  VendorAdminType get vendor => getField<VendorAdminType>(
    vendorField,
    enumValues: VendorAdminType.values,
    defaultValue: VendorAdminType.retailer,
  )!;
  set vendor(VendorAdminType value) =>
      setField<VendorAdminType>(vendorField, value);

  /// Name field name
  static const String nameField = 'name';

  /// Name
  String? get name => getField<String>(nameField);
  set name(String? value) => setField<String>(nameField, value);

  /// Title field name
  static const String titleField = 'title';

  /// Title
  String? get title => getField<String>(titleField);
  set title(String? value) => setField<String>(titleField, value);

  /// Company field name
  static const String companyField = 'company';

  /// Company
  String? get company => getField<String>(companyField);
  set company(String? value) => setField<String>(companyField, value);

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Is Curation field name
  static const String isCurationField = 'is_curation';

  /// Is Curation
  bool get isCuration => getField<bool>(isCurationField, defaultValue: false)!;
  set isCuration(bool value) => setField<bool>(isCurationField, value);

  /// Additional Discount Rate field name
  static const String additionalDiscountRateField = 'additional_discount_rate';

  /// Additional Discount Rate
  double get additionalDiscountRate =>
      getField<double>(additionalDiscountRateField, defaultValue: 0)!;
  set additionalDiscountRate(double value) =>
      setField<double>(additionalDiscountRateField, value);

  /// Make a copy of the current [ProductRow]
  /// overriding the provided fields
  ProductRow copyWith({
    DateTime? createdAt,
    String? createdBy,
    String? productBy,
    String? category,
    double? regularPrice,
    String? mainImageBucket,
    String? mainImageFolderPath,
    String? mainImageFileName,
    String? description,
    ProductMaterial? type,
    ProductStyle? style,
    VendorAdminType? vendor,
    String? name,
    String? title,
    String? company,
    String? id,
    bool? isCuration,
    double? additionalDiscountRate,
  }) => ProductRow.fromJson({
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'created_by': supaSerialize(createdBy) ?? data['created_by'],
    'product_by': supaSerialize(productBy) ?? data['product_by'],
    'category': supaSerialize(category) ?? data['category'],
    'regular_price': supaSerialize(regularPrice) ?? data['regular_price'],
    'main_image_bucket':
        supaSerialize(mainImageBucket) ?? data['main_image_bucket'],
    'main_image_folder_path':
        supaSerialize(mainImageFolderPath) ?? data['main_image_folder_path'],
    'main_image_file_name':
        supaSerialize(mainImageFileName) ?? data['main_image_file_name'],
    'description': supaSerialize(description) ?? data['description'],
    'type': supaSerialize(type) ?? data['type'],
    'style': supaSerialize(style) ?? data['style'],
    'vendor': supaSerialize(vendor) ?? data['vendor'],
    'name': supaSerialize(name) ?? data['name'],
    'title': supaSerialize(title) ?? data['title'],
    'company': supaSerialize(company) ?? data['company'],
    'id': supaSerialize(id) ?? data['id'],
    'is_curation': supaSerialize(isCuration) ?? data['is_curation'],
    'additional_discount_rate':
        supaSerialize(additionalDiscountRate) ??
        data['additional_discount_rate'],
  });
}

/// Tag: v2
/// Date: 2026-01-16 16:22:11.175966
