//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Product Question Reply Table
class ProductQuestionReplyTable extends SupabaseTable<ProductQuestionReplyRow> {
  /// Table Name
  @override
  String get tableName => 'product_question_reply';

  /// Create a [ProductQuestionReplyRow] from the [data] provided
  @override
  ProductQuestionReplyRow createRow(Map<String, dynamic> data) =>
      ProductQuestionReplyRow.fromJson(data);
}

/// Product Question Reply Row
class ProductQuestionReplyRow extends SupabaseDataRow {
  /// Product Question Reply Row
  ProductQuestionReplyRow({
    String? id,
    DateTime? createdAt,
    String? replyBy,
    String? reply,
    String? replyingTo,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (replyBy != null) 'reply_by': supaSerialize(replyBy),
         if (reply != null) 'reply': supaSerialize(reply),
         if (replyingTo != null) 'replying_to': supaSerialize(replyingTo),
       });

  /// Product Question Reply Row
  const ProductQuestionReplyRow._(super.data);

  /// Create Product Question Reply Row from a [data] map
  factory ProductQuestionReplyRow.fromJson(Map<String, dynamic> data) =>
      ProductQuestionReplyRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => ProductQuestionReplyTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Reply By field name
  static const String replyByField = 'reply_by';

  /// Reply By
  String? get replyBy => getField<String>(replyByField);
  set replyBy(String? value) => setField<String>(replyByField, value);

  /// Reply field name
  static const String replyField = 'reply';

  /// Reply
  String? get reply => getField<String>(replyField);
  set reply(String? value) => setField<String>(replyField, value);

  /// Replying To field name
  static const String replyingToField = 'replying_to';

  /// Replying To
  String? get replyingTo => getField<String>(replyingToField);
  set replyingTo(String? value) => setField<String>(replyingToField, value);

  /// Make a copy of the current [ProductQuestionReplyRow]
  /// overriding the provided fields
  ProductQuestionReplyRow copyWith({
    String? id,
    DateTime? createdAt,
    String? replyBy,
    String? reply,
    String? replyingTo,
  }) => ProductQuestionReplyRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'reply_by': supaSerialize(replyBy) ?? data['reply_by'],
    'reply': supaSerialize(reply) ?? data['reply'],
    'replying_to': supaSerialize(replyingTo) ?? data['replying_to'],
  });
}

/// Tag: v2
/// Date: 2026-03-20 19:41:33.399076
