//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Product Review Image Table
class ProductReviewImageTable extends SupabaseTable<ProductReviewImageRow> {
  /// Table Name
  @override
  String get tableName => 'product_review_image';

  /// Create a [ProductReviewImageRow] from the [data] provided
  @override
  ProductReviewImageRow createRow(Map<String, dynamic> data) =>
      ProductReviewImageRow.fromJson(data);
}

/// Product Review Image Row
class ProductReviewImageRow extends SupabaseDataRow {
  /// Product Review Image Row
  ProductReviewImageRow({
    String? id,
    DateTime? createdAt,
    String? uploadedBy,
    String? review,
    String? bucket,
    String? folderPath,
    String? fileName,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (uploadedBy != null) 'uploaded_by': supaSerialize(uploadedBy),
         if (review != null) 'review': supaSerialize(review),
         if (bucket != null) 'bucket': supaSerialize(bucket),
         if (folderPath != null) 'folder_path': supaSerialize(folderPath),
         if (fileName != null) 'file_name': supaSerialize(fileName),
       });

  /// Product Review Image Row
  const ProductReviewImageRow._(super.data);

  /// Create Product Review Image Row from a [data] map
  factory ProductReviewImageRow.fromJson(Map<String, dynamic> data) =>
      ProductReviewImageRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => ProductReviewImageTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Uploaded By field name
  static const String uploadedByField = 'uploaded_by';

  /// Uploaded By
  String? get uploadedBy => getField<String>(uploadedByField);
  set uploadedBy(String? value) => setField<String>(uploadedByField, value);

  /// Review field name
  static const String reviewField = 'review';

  /// Review
  String? get review => getField<String>(reviewField);
  set review(String? value) => setField<String>(reviewField, value);

  /// Bucket field name
  static const String bucketField = 'bucket';

  /// Bucket
  String? get bucket => getField<String>(bucketField);
  set bucket(String? value) => setField<String>(bucketField, value);

  /// Folder Path field name
  static const String folderPathField = 'folder_path';

  /// Folder Path
  String? get folderPath => getField<String>(folderPathField);
  set folderPath(String? value) => setField<String>(folderPathField, value);

  /// File Name field name
  static const String fileNameField = 'file_name';

  /// File Name
  String? get fileName => getField<String>(fileNameField);
  set fileName(String? value) => setField<String>(fileNameField, value);

  /// Make a copy of the current [ProductReviewImageRow]
  /// overriding the provided fields
  ProductReviewImageRow copyWith({
    String? id,
    DateTime? createdAt,
    String? uploadedBy,
    String? review,
    String? bucket,
    String? folderPath,
    String? fileName,
  }) => ProductReviewImageRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'uploaded_by': supaSerialize(uploadedBy) ?? data['uploaded_by'],
    'review': supaSerialize(review) ?? data['review'],
    'bucket': supaSerialize(bucket) ?? data['bucket'],
    'folder_path': supaSerialize(folderPath) ?? data['folder_path'],
    'file_name': supaSerialize(fileName) ?? data['file_name'],
  });
}

/// Tag: v2
/// Date: 2026-01-27 15:18:18.842383
