//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Product Option Value Table
class ProductOptionValueTable extends SupabaseTable<ProductOptionValueRow> {
  /// Table Name
  @override
  String get tableName => 'product_option_value';

  /// Create a [ProductOptionValueRow] from the [data] provided
  @override
  ProductOptionValueRow createRow(Map<String, dynamic> data) =>
      ProductOptionValueRow.fromJson(data);
}

/// Product Option Value Row
class ProductOptionValueRow extends SupabaseDataRow {
  /// Product Option Value Row
  ProductOptionValueRow({
    String? id,
    DateTime? createdAt,
    String? createdBy,
    String? optionParameter,
    String? value,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (createdBy != null) 'created_by': supaSerialize(createdBy),
         if (optionParameter != null)
           'option_parameter': supaSerialize(optionParameter),
         if (value != null) 'value': supaSerialize(value),
       });

  /// Product Option Value Row
  const ProductOptionValueRow._(super.data);

  /// Create Product Option Value Row from a [data] map
  factory ProductOptionValueRow.fromJson(Map<String, dynamic> data) =>
      ProductOptionValueRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => ProductOptionValueTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Created By field name
  static const String createdByField = 'created_by';

  /// Created By
  String get createdBy =>
      getField<String>(createdByField, defaultValue: 'auth.')!;
  set createdBy(String value) => setField<String>(createdByField, value);

  /// Option Parameter field name
  static const String optionParameterField = 'option_parameter';

  /// Option Parameter
  String? get optionParameter => getField<String>(optionParameterField);
  set optionParameter(String? value) =>
      setField<String>(optionParameterField, value);

  /// Value field name
  static const String valueField = 'value';

  /// Value
  String? get value => getField<String>(valueField);
  set value(String? value) => setField<String>(valueField, value);

  /// Make a copy of the current [ProductOptionValueRow]
  /// overriding the provided fields
  ProductOptionValueRow copyWith({
    String? id,
    DateTime? createdAt,
    String? createdBy,
    String? optionParameter,
    String? value,
  }) => ProductOptionValueRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'created_by': supaSerialize(createdBy) ?? data['created_by'],
    'option_parameter':
        supaSerialize(optionParameter) ?? data['option_parameter'],
    'value': supaSerialize(value) ?? data['value'],
  });
}

/// Tag: v2
/// Date: 2025-12-01 17:41:38.058348
