//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Product Option Color Table
class ProductOptionColorTable extends SupabaseTable<ProductOptionColorRow> {
  /// Table Name
  @override
  String get tableName => 'product_option_color';

  /// Create a [ProductOptionColorRow] from the [data] provided
  @override
  ProductOptionColorRow createRow(Map<String, dynamic> data) =>
      ProductOptionColorRow.fromJson(data);
}

/// Product Option Color Row
class ProductOptionColorRow extends SupabaseDataRow {
  /// Product Option Color Row
  ProductOptionColorRow({
    String? id,
    DateTime? createdAt,
    String? createdBy,
    String? value,
    String? coloredProductBucket,
    String? coloredProductFolderPath,
    String? coloredProductFileName,
    String? product,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (createdBy != null) 'created_by': supaSerialize(createdBy),
         if (value != null) 'value': supaSerialize(value),
         if (coloredProductBucket != null)
           'colored_product_bucket': supaSerialize(coloredProductBucket),
         if (coloredProductFolderPath != null)
           'colored_product_folder_path': supaSerialize(
             coloredProductFolderPath,
           ),
         if (coloredProductFileName != null)
           'colored_product_file_name': supaSerialize(coloredProductFileName),
         if (product != null) 'product': supaSerialize(product),
       });

  /// Product Option Color Row
  const ProductOptionColorRow._(super.data);

  /// Create Product Option Color Row from a [data] map
  factory ProductOptionColorRow.fromJson(Map<String, dynamic> data) =>
      ProductOptionColorRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => ProductOptionColorTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Created By field name
  static const String createdByField = 'created_by';

  /// Created By
  String get createdBy =>
      getField<String>(createdByField, defaultValue: 'auth.')!;
  set createdBy(String value) => setField<String>(createdByField, value);

  /// Value field name
  static const String valueField = 'value';

  /// Value
  String? get value => getField<String>(valueField);
  set value(String? value) => setField<String>(valueField, value);

  /// Colored Product Bucket field name
  static const String coloredProductBucketField = 'colored_product_bucket';

  /// Colored Product Bucket
  String? get coloredProductBucket =>
      getField<String>(coloredProductBucketField);
  set coloredProductBucket(String? value) =>
      setField<String>(coloredProductBucketField, value);

  /// Colored Product Folder Path field name
  static const String coloredProductFolderPathField =
      'colored_product_folder_path';

  /// Colored Product Folder Path
  String? get coloredProductFolderPath =>
      getField<String>(coloredProductFolderPathField);
  set coloredProductFolderPath(String? value) =>
      setField<String>(coloredProductFolderPathField, value);

  /// Colored Product File Name field name
  static const String coloredProductFileNameField = 'colored_product_file_name';

  /// Colored Product File Name
  String? get coloredProductFileName =>
      getField<String>(coloredProductFileNameField);
  set coloredProductFileName(String? value) =>
      setField<String>(coloredProductFileNameField, value);

  /// Product field name
  static const String productField = 'product';

  /// Product
  String? get product => getField<String>(productField);
  set product(String? value) => setField<String>(productField, value);

  /// Make a copy of the current [ProductOptionColorRow]
  /// overriding the provided fields
  ProductOptionColorRow copyWith({
    String? id,
    DateTime? createdAt,
    String? createdBy,
    String? value,
    String? coloredProductBucket,
    String? coloredProductFolderPath,
    String? coloredProductFileName,
    String? product,
  }) => ProductOptionColorRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'created_by': supaSerialize(createdBy) ?? data['created_by'],
    'value': supaSerialize(value) ?? data['value'],
    'colored_product_bucket':
        supaSerialize(coloredProductBucket) ?? data['colored_product_bucket'],
    'colored_product_folder_path':
        supaSerialize(coloredProductFolderPath) ??
        data['colored_product_folder_path'],
    'colored_product_file_name':
        supaSerialize(coloredProductFileName) ??
        data['colored_product_file_name'],
    'product': supaSerialize(product) ?? data['product'],
  });
}

/// Tag: v2
/// Date: 2026-03-17 16:20:06.116751
