//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Product Subcategory Table
class ProductSubcategoryTable extends SupabaseTable<ProductSubcategoryRow> {
  /// Table Name
  @override
  String get tableName => 'product_subcategory';

  /// Create a [ProductSubcategoryRow] from the [data] provided
  @override
  ProductSubcategoryRow createRow(Map<String, dynamic> data) =>
      ProductSubcategoryRow.fromJson(data);
}

/// Product Subcategory Row
class ProductSubcategoryRow extends SupabaseDataRow {
  /// Product Subcategory Row
  ProductSubcategoryRow({
    String? id,
    DateTime? createdAt,
    String? createdBy,
    String? category,
    String? name,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (createdBy != null) 'created_by': supaSerialize(createdBy),
         if (category != null) 'category': supaSerialize(category),
         if (name != null) 'name': supaSerialize(name),
       });

  /// Product Subcategory Row
  const ProductSubcategoryRow._(super.data);

  /// Create Product Subcategory Row from a [data] map
  factory ProductSubcategoryRow.fromJson(Map<String, dynamic> data) =>
      ProductSubcategoryRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => ProductSubcategoryTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Created By field name
  static const String createdByField = 'created_by';

  /// Created By
  String? get createdBy => getField<String>(createdByField);
  set createdBy(String? value) => setField<String>(createdByField, value);

  /// Category field name
  static const String categoryField = 'category';

  /// Category
  String? get category => getField<String>(categoryField);
  set category(String? value) => setField<String>(categoryField, value);

  /// Name field name
  static const String nameField = 'name';

  /// Name
  String? get name => getField<String>(nameField);
  set name(String? value) => setField<String>(nameField, value);

  /// Make a copy of the current [ProductSubcategoryRow]
  /// overriding the provided fields
  ProductSubcategoryRow copyWith({
    String? id,
    DateTime? createdAt,
    String? createdBy,
    String? category,
    String? name,
  }) => ProductSubcategoryRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'created_by': supaSerialize(createdBy) ?? data['created_by'],
    'category': supaSerialize(category) ?? data['category'],
    'name': supaSerialize(name) ?? data['name'],
  });
}

/// Tag: v2
/// Date: 2026-01-21 21:59:57.938360
