//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Product Category Table
class ProductCategoryTable extends SupabaseTable<ProductCategoryRow> {
  /// Table Name
  @override
  String get tableName => 'product_category';

  /// Create a [ProductCategoryRow] from the [data] provided
  @override
  ProductCategoryRow createRow(Map<String, dynamic> data) =>
      ProductCategoryRow.fromJson(data);
}

/// Product Category Row
class ProductCategoryRow extends SupabaseDataRow {
  /// Product Category Row
  ProductCategoryRow({
    required String name,
    String? id,
    DateTime? createdAt,
    String? createdBy,
  }) : super({
         'name': supaSerialize(name),
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (createdBy != null) 'created_by': supaSerialize(createdBy),
       });

  /// Product Category Row
  const ProductCategoryRow._(super.data);

  /// Create Product Category Row from a [data] map
  factory ProductCategoryRow.fromJson(Map<String, dynamic> data) =>
      ProductCategoryRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => ProductCategoryTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Created By field name
  static const String createdByField = 'created_by';

  /// Created By
  String? get createdBy => getField<String>(createdByField);
  set createdBy(String? value) => setField<String>(createdByField, value);

  /// Name field name
  static const String nameField = 'name';

  /// Name
  String get name => getField<String>(nameField)!;
  set name(String value) => setField<String>(nameField, value);

  /// Make a copy of the current [ProductCategoryRow]
  /// overriding the provided fields
  ProductCategoryRow copyWith({
    String? name,
    String? id,
    DateTime? createdAt,
    String? createdBy,
  }) => ProductCategoryRow.fromJson({
    'name': supaSerialize(name) ?? data['name'],
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'created_by': supaSerialize(createdBy) ?? data['created_by'],
  });
}

/// Tag: v2
/// Date: 2026-01-15 14:21:42.923082
