//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Product Question Table
class ProductQuestionTable extends SupabaseTable<ProductQuestionRow> {
  /// Table Name
  @override
  String get tableName => 'product_question';

  /// Create a [ProductQuestionRow] from the [data] provided
  @override
  ProductQuestionRow createRow(Map<String, dynamic> data) =>
      ProductQuestionRow.fromJson(data);
}

/// Product Question Row
class ProductQuestionRow extends SupabaseDataRow {
  /// Product Question Row
  ProductQuestionRow({
    String? id,
    DateTime? createdAt,
    String? questionBy,
    String? question,
    String? product,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (questionBy != null) 'question_by': supaSerialize(questionBy),
         if (question != null) 'question': supaSerialize(question),
         if (product != null) 'product': supaSerialize(product),
       });

  /// Product Question Row
  const ProductQuestionRow._(super.data);

  /// Create Product Question Row from a [data] map
  factory ProductQuestionRow.fromJson(Map<String, dynamic> data) =>
      ProductQuestionRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => ProductQuestionTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Question By field name
  static const String questionByField = 'question_by';

  /// Question By
  String? get questionBy => getField<String>(questionByField);
  set questionBy(String? value) => setField<String>(questionByField, value);

  /// Question field name
  static const String questionField = 'question';

  /// Question
  String? get question => getField<String>(questionField);
  set question(String? value) => setField<String>(questionField, value);

  /// Product field name
  static const String productField = 'product';

  /// Product
  String? get product => getField<String>(productField);
  set product(String? value) => setField<String>(productField, value);

  /// Make a copy of the current [ProductQuestionRow]
  /// overriding the provided fields
  ProductQuestionRow copyWith({
    String? id,
    DateTime? createdAt,
    String? questionBy,
    String? question,
    String? product,
  }) => ProductQuestionRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'question_by': supaSerialize(questionBy) ?? data['question_by'],
    'question': supaSerialize(question) ?? data['question'],
    'product': supaSerialize(product) ?? data['product'],
  });
}

/// Tag: v2
/// Date: 2026-02-04 11:46:32.472995
