//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Product Image Description Table
class ProductImageDescriptionTable
    extends SupabaseTable<ProductImageDescriptionRow> {
  /// Table Name
  @override
  String get tableName => 'product_image_description';

  /// Create a [ProductImageDescriptionRow] from the [data] provided
  @override
  ProductImageDescriptionRow createRow(Map<String, dynamic> data) =>
      ProductImageDescriptionRow.fromJson(data);
}

/// Product Image Description Row
class ProductImageDescriptionRow extends SupabaseDataRow {
  /// Product Image Description Row
  ProductImageDescriptionRow({
    String? id,
    DateTime? createdAt,
    String? bucket,
    String? folderPath,
    String? fileName,
    String? product,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (bucket != null) 'bucket': supaSerialize(bucket),
         if (folderPath != null) 'folder_path': supaSerialize(folderPath),
         if (fileName != null) 'file_name': supaSerialize(fileName),
         if (product != null) 'product': supaSerialize(product),
       });

  /// Product Image Description Row
  const ProductImageDescriptionRow._(super.data);

  /// Create Product Image Description Row from a [data] map
  factory ProductImageDescriptionRow.fromJson(Map<String, dynamic> data) =>
      ProductImageDescriptionRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => ProductImageDescriptionTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Bucket field name
  static const String bucketField = 'bucket';

  /// Bucket
  String? get bucket => getField<String>(bucketField);
  set bucket(String? value) => setField<String>(bucketField, value);

  /// Folder Path field name
  static const String folderPathField = 'folder_path';

  /// Folder Path
  String? get folderPath => getField<String>(folderPathField);
  set folderPath(String? value) => setField<String>(folderPathField, value);

  /// File Name field name
  static const String fileNameField = 'file_name';

  /// File Name
  String? get fileName => getField<String>(fileNameField);
  set fileName(String? value) => setField<String>(fileNameField, value);

  /// Product field name
  static const String productField = 'product';

  /// Product
  String? get product => getField<String>(productField);
  set product(String? value) => setField<String>(productField, value);

  /// Make a copy of the current [ProductImageDescriptionRow]
  /// overriding the provided fields
  ProductImageDescriptionRow copyWith({
    String? id,
    DateTime? createdAt,
    String? bucket,
    String? folderPath,
    String? fileName,
    String? product,
  }) => ProductImageDescriptionRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'bucket': supaSerialize(bucket) ?? data['bucket'],
    'folder_path': supaSerialize(folderPath) ?? data['folder_path'],
    'file_name': supaSerialize(fileName) ?? data['file_name'],
    'product': supaSerialize(product) ?? data['product'],
  });
}

/// Tag: v2
/// Date: 2026-03-13 16:11:42.595941
