//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Product Table
class ProductTable extends SupabaseTable<ProductRow> {
  /// Table Name
  @override
  String get tableName => 'product';

  /// Create a [ProductRow] from the [data] provided
  @override
  ProductRow createRow(Map<String, dynamic> data) => ProductRow.fromJson(data);
}

/// Product Row
class ProductRow extends SupabaseDataRow {
  /// Product Row
  ProductRow({
    required ProductSaleStatus saleStatus,
    String? code,
    DateTime? createdAt,
    String? createdBy,
    String? productBy,
    String? category,
    double? regularPrice,
    double? minimumPriceMinusAwardPoints,
    double? stockQuantity,
    double? safeStockQuantity,
    String? mainImageBucket,
    String? mainImageFolderPath,
    String? mainImageFileName,
    String? description,
    ProductMaterial? type,
    ProductStyle? style,
    VendorAdminType? vendor,
    String? name,
    String? title,
  }) : super({
         'sale_status': supaSerialize(saleStatus),
         if (code != null) 'code': supaSerialize(code),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (createdBy != null) 'created_by': supaSerialize(createdBy),
         if (productBy != null) 'product_by': supaSerialize(productBy),
         if (category != null) 'category': supaSerialize(category),
         if (regularPrice != null) 'regular_price': supaSerialize(regularPrice),
         if (minimumPriceMinusAwardPoints != null)
           'minimum_price_minus_award_points': supaSerialize(
             minimumPriceMinusAwardPoints,
           ),
         if (stockQuantity != null)
           'stock_quantity': supaSerialize(stockQuantity),
         if (safeStockQuantity != null)
           'safe_stock_quantity': supaSerialize(safeStockQuantity),
         if (mainImageBucket != null)
           'main_image_bucket': supaSerialize(mainImageBucket),
         if (mainImageFolderPath != null)
           'main_image_folder_path': supaSerialize(mainImageFolderPath),
         if (mainImageFileName != null)
           'main_image_file_name': supaSerialize(mainImageFileName),
         if (description != null) 'description': supaSerialize(description),
         if (type != null) 'type': supaSerialize(type),
         if (style != null) 'style': supaSerialize(style),
         if (vendor != null) 'vendor': supaSerialize(vendor),
         if (name != null) 'name': supaSerialize(name),
         if (title != null) 'title': supaSerialize(title),
       });

  /// Product Row
  const ProductRow._(super.data);

  /// Create Product Row from a [data] map
  factory ProductRow.fromJson(Map<String, dynamic> data) =>
      ProductRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => ProductTable();

  /// Code field name
  static const String codeField = 'code';

  /// Code
  String get code => getField<String>(codeField, defaultValue: '()')!;
  set code(String value) => setField<String>(codeField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Created By field name
  static const String createdByField = 'created_by';

  /// Created By
  String get createdBy =>
      getField<String>(createdByField, defaultValue: 'auth.')!;
  set createdBy(String value) => setField<String>(createdByField, value);

  /// Product By field name
  static const String productByField = 'product_by';

  /// Product By
  String get productBy =>
      getField<String>(productByField, defaultValue: 'auth.')!;
  set productBy(String value) => setField<String>(productByField, value);

  /// Category field name
  static const String categoryField = 'category';

  /// Category
  String? get category => getField<String>(categoryField);
  set category(String? value) => setField<String>(categoryField, value);

  /// Sale Status field name
  static const String saleStatusField = 'sale_status';

  /// Sale Status
  ProductSaleStatus get saleStatus => getField<ProductSaleStatus>(
    saleStatusField,
    enumValues: ProductSaleStatus.values,
  )!;
  set saleStatus(ProductSaleStatus value) =>
      setField<ProductSaleStatus>(saleStatusField, value);

  /// Regular Price field name
  static const String regularPriceField = 'regular_price';

  /// Regular Price
  double? get regularPrice => getField<double>(regularPriceField);
  set regularPrice(double? value) => setField<double>(regularPriceField, value);

  /// Minimum Price Minus Award Points field name
  static const String minimumPriceMinusAwardPointsField =
      'minimum_price_minus_award_points';

  /// Minimum Price Minus Award Points
  double? get minimumPriceMinusAwardPoints =>
      getField<double>(minimumPriceMinusAwardPointsField);
  set minimumPriceMinusAwardPoints(double? value) =>
      setField<double>(minimumPriceMinusAwardPointsField, value);

  /// Stock Quantity field name
  static const String stockQuantityField = 'stock_quantity';

  /// Stock Quantity
  double get stockQuantity =>
      getField<double>(stockQuantityField, defaultValue: 0)!;
  set stockQuantity(double value) =>
      setField<double>(stockQuantityField, value);

  /// Safe Stock Quantity field name
  static const String safeStockQuantityField = 'safe_stock_quantity';

  /// Safe Stock Quantity
  double? get safeStockQuantity => getField<double>(safeStockQuantityField);
  set safeStockQuantity(double? value) =>
      setField<double>(safeStockQuantityField, value);

  /// Main Image Bucket field name
  static const String mainImageBucketField = 'main_image_bucket';

  /// Main Image Bucket
  String? get mainImageBucket => getField<String>(mainImageBucketField);
  set mainImageBucket(String? value) =>
      setField<String>(mainImageBucketField, value);

  /// Main Image Folder Path field name
  static const String mainImageFolderPathField = 'main_image_folder_path';

  /// Main Image Folder Path
  String? get mainImageFolderPath => getField<String>(mainImageFolderPathField);
  set mainImageFolderPath(String? value) =>
      setField<String>(mainImageFolderPathField, value);

  /// Main Image File Name field name
  static const String mainImageFileNameField = 'main_image_file_name';

  /// Main Image File Name
  String? get mainImageFileName => getField<String>(mainImageFileNameField);
  set mainImageFileName(String? value) =>
      setField<String>(mainImageFileNameField, value);

  /// Description field name
  static const String descriptionField = 'description';

  /// Description
  String? get description => getField<String>(descriptionField);
  set description(String? value) => setField<String>(descriptionField, value);

  /// Type field name
  static const String typeField = 'type';

  /// Type
  ProductMaterial? get type =>
      getField<ProductMaterial>(typeField, enumValues: ProductMaterial.values);
  set type(ProductMaterial? value) =>
      setField<ProductMaterial>(typeField, value);

  /// Style field name
  static const String styleField = 'style';

  /// Style
  ProductStyle? get style =>
      getField<ProductStyle>(styleField, enumValues: ProductStyle.values);
  set style(ProductStyle? value) => setField<ProductStyle>(styleField, value);

  /// Vendor field name
  static const String vendorField = 'vendor';

  /// Vendor
  VendorAdminType get vendor => getField<VendorAdminType>(
    vendorField,
    enumValues: VendorAdminType.values,
    defaultValue: VendorAdminType.retailer,
  )!;
  set vendor(VendorAdminType value) =>
      setField<VendorAdminType>(vendorField, value);

  /// Name field name
  static const String nameField = 'name';

  /// Name
  String? get name => getField<String>(nameField);
  set name(String? value) => setField<String>(nameField, value);

  /// Title field name
  static const String titleField = 'title';

  /// Title
  String? get title => getField<String>(titleField);
  set title(String? value) => setField<String>(titleField, value);

  /// Make a copy of the current [ProductRow]
  /// overriding the provided fields
  ProductRow copyWith({
    ProductSaleStatus? saleStatus,
    String? code,
    DateTime? createdAt,
    String? createdBy,
    String? productBy,
    String? category,
    double? regularPrice,
    double? minimumPriceMinusAwardPoints,
    double? stockQuantity,
    double? safeStockQuantity,
    String? mainImageBucket,
    String? mainImageFolderPath,
    String? mainImageFileName,
    String? description,
    ProductMaterial? type,
    ProductStyle? style,
    VendorAdminType? vendor,
    String? name,
    String? title,
  }) => ProductRow.fromJson({
    'sale_status': supaSerialize(saleStatus) ?? data['sale_status'],
    'code': supaSerialize(code) ?? data['code'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'created_by': supaSerialize(createdBy) ?? data['created_by'],
    'product_by': supaSerialize(productBy) ?? data['product_by'],
    'category': supaSerialize(category) ?? data['category'],
    'regular_price': supaSerialize(regularPrice) ?? data['regular_price'],
    'minimum_price_minus_award_points':
        supaSerialize(minimumPriceMinusAwardPoints) ??
        data['minimum_price_minus_award_points'],
    'stock_quantity': supaSerialize(stockQuantity) ?? data['stock_quantity'],
    'safe_stock_quantity':
        supaSerialize(safeStockQuantity) ?? data['safe_stock_quantity'],
    'main_image_bucket':
        supaSerialize(mainImageBucket) ?? data['main_image_bucket'],
    'main_image_folder_path':
        supaSerialize(mainImageFolderPath) ?? data['main_image_folder_path'],
    'main_image_file_name':
        supaSerialize(mainImageFileName) ?? data['main_image_file_name'],
    'description': supaSerialize(description) ?? data['description'],
    'type': supaSerialize(type) ?? data['type'],
    'style': supaSerialize(style) ?? data['style'],
    'vendor': supaSerialize(vendor) ?? data['vendor'],
    'name': supaSerialize(name) ?? data['name'],
    'title': supaSerialize(title) ?? data['title'],
  });
}

/// Tag: v2
/// Date: 2025-12-03 16:25:28.153861
