//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Product Table
class ProductTable extends SupabaseTable<ProductRow> {
  /// Table Name
  @override
  String get tableName => 'product';

  /// Create a [ProductRow] from the [data] provided
  @override
  ProductRow createRow(Map<String, dynamic> data) => ProductRow.fromJson(data);
}

/// Product Row
class ProductRow extends SupabaseDataRow {
  /// Product Row
  ProductRow({
    String? id,
    String? name,
    String? description,
    String? createdBy,
    DateTime? createdAt,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (name != null) 'name': supaSerialize(name),
         if (description != null) 'description': supaSerialize(description),
         if (createdBy != null) 'created_by': supaSerialize(createdBy),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
       });

  /// Product Row
  const ProductRow._(super.data);

  /// Create Product Row from a [data] map
  factory ProductRow.fromJson(Map<String, dynamic> data) =>
      ProductRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => ProductTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Name field name
  static const String nameField = 'name';

  /// Name
  String? get name => getField<String>(nameField);
  set name(String? value) => setField<String>(nameField, value);

  /// Description field name
  static const String descriptionField = 'description';

  /// Description
  String? get description => getField<String>(descriptionField);
  set description(String? value) => setField<String>(descriptionField, value);

  /// Created By field name
  static const String createdByField = 'created_by';

  /// Created By
  String get createdBy =>
      getField<String>(createdByField, defaultValue: 'auth.')!;
  set createdBy(String value) => setField<String>(createdByField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Make a copy of the current [ProductRow]
  /// overriding the provided fields
  ProductRow copyWith({
    String? id,
    String? name,
    String? description,
    String? createdBy,
    DateTime? createdAt,
  }) => ProductRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'name': supaSerialize(name) ?? data['name'],
    'description': supaSerialize(description) ?? data['description'],
    'created_by': supaSerialize(createdBy) ?? data['created_by'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
  });
}

/// Tag: v2
/// Date: 2025-11-28 10:14:23.491214
