//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Push Notification Trigger Table
class PushNotificationTriggerTable
    extends SupabaseTable<PushNotificationTriggerRow> {
  /// Table Name
  @override
  String get tableName => 'push_notification_trigger';

  /// Create a [PushNotificationTriggerRow] from the [data] provided
  @override
  PushNotificationTriggerRow createRow(Map<String, dynamic> data) =>
      PushNotificationTriggerRow.fromJson(data);
}

/// Push Notification Trigger Row
class PushNotificationTriggerRow extends SupabaseDataRow {
  /// Push Notification Trigger Row
  PushNotificationTriggerRow({
    String? id,
    List<String>? token,
    String? title,
    String? body,
    DateTime? createdAt,
    String? createdBy,
    String? imageUrl,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (token != null) 'token': supaSerialize(token),
         if (title != null) 'title': supaSerialize(title),
         if (body != null) 'body': supaSerialize(body),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (createdBy != null) 'created_by': supaSerialize(createdBy),
         if (imageUrl != null) 'image_url': supaSerialize(imageUrl),
       });

  /// Push Notification Trigger Row
  const PushNotificationTriggerRow._(super.data);

  /// Create Push Notification Trigger Row from a [data] map
  factory PushNotificationTriggerRow.fromJson(Map<String, dynamic> data) =>
      PushNotificationTriggerRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => PushNotificationTriggerTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Token field name
  static const String tokenField = 'token';

  /// Token
  List<String> get token => getListField<String>(tokenField);
  set token(List<String>? value) => setListField<String>(tokenField, value);

  /// Title field name
  static const String titleField = 'title';

  /// Title
  String? get title => getField<String>(titleField);
  set title(String? value) => setField<String>(titleField, value);

  /// Body field name
  static const String bodyField = 'body';

  /// Body
  String? get body => getField<String>(bodyField);
  set body(String? value) => setField<String>(bodyField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Created By field name
  static const String createdByField = 'created_by';

  /// Created By
  String? get createdBy => getField<String>(createdByField);
  set createdBy(String? value) => setField<String>(createdByField, value);

  /// Image Url field name
  static const String imageUrlField = 'image_url';

  /// Image Url
  String? get imageUrl => getField<String>(imageUrlField);
  set imageUrl(String? value) => setField<String>(imageUrlField, value);

  /// Make a copy of the current [PushNotificationTriggerRow]
  /// overriding the provided fields
  PushNotificationTriggerRow copyWith({
    String? id,
    List<String>? token,
    String? title,
    String? body,
    DateTime? createdAt,
    String? createdBy,
    String? imageUrl,
  }) => PushNotificationTriggerRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'token': supaSerialize(token) ?? data['token'],
    'title': supaSerialize(title) ?? data['title'],
    'body': supaSerialize(body) ?? data['body'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'created_by': supaSerialize(createdBy) ?? data['created_by'],
    'image_url': supaSerialize(imageUrl) ?? data['image_url'],
  });
}

/// Tag: v2
/// Date: 2026-03-13 15:28:25.401539
