//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Push Notification Campaign Log Table
class PushNotificationCampaignLogTable
    extends SupabaseTable<PushNotificationCampaignLogRow> {
  /// Table Name
  @override
  String get tableName => 'push_notification_campaign_log';

  /// Create a [PushNotificationCampaignLogRow] from the [data] provided
  @override
  PushNotificationCampaignLogRow createRow(Map<String, dynamic> data) =>
      PushNotificationCampaignLogRow.fromJson(data);
}

/// Push Notification Campaign Log Row
class PushNotificationCampaignLogRow extends SupabaseDataRow {
  /// Push Notification Campaign Log Row
  PushNotificationCampaignLogRow({
    required String categoryKey,
    required String notificationId,
    required String userId,
    String? id,
    DateTime? sentAt,
    String? status,
    String? errorMessage,
    int? tokenCount,
    String? companyId,
    DateTime? createdAt,
  }) : super({
         'category_key': supaSerialize(categoryKey),
         'notification_id': supaSerialize(notificationId),
         'user_id': supaSerialize(userId),
         if (id != null) 'id': supaSerialize(id),
         if (sentAt != null) 'sent_at': supaSerialize(sentAt),
         if (status != null) 'status': supaSerialize(status),
         if (errorMessage != null) 'error_message': supaSerialize(errorMessage),
         if (tokenCount != null) 'token_count': supaSerialize(tokenCount),
         if (companyId != null) 'company_id': supaSerialize(companyId),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
       });

  /// Push Notification Campaign Log Row
  const PushNotificationCampaignLogRow._(super.data);

  /// Create Push Notification Campaign Log Row from a [data] map
  factory PushNotificationCampaignLogRow.fromJson(Map<String, dynamic> data) =>
      PushNotificationCampaignLogRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => PushNotificationCampaignLogTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Category Key field name
  static const String categoryKeyField = 'category_key';

  /// Category Key
  String get categoryKey => getField<String>(categoryKeyField)!;
  set categoryKey(String value) => setField<String>(categoryKeyField, value);

  /// Notification Id field name
  static const String notificationIdField = 'notification_id';

  /// Notification Id
  String get notificationId => getField<String>(notificationIdField)!;
  set notificationId(String value) =>
      setField<String>(notificationIdField, value);

  /// User Id field name
  static const String userIdField = 'user_id';

  /// User Id
  String get userId => getField<String>(userIdField)!;
  set userId(String value) => setField<String>(userIdField, value);

  /// Sent At field name
  static const String sentAtField = 'sent_at';

  /// Sent At
  DateTime get sentAt =>
      getField<DateTime>(sentAtField, defaultValue: DateTime.now())!;
  set sentAt(DateTime value) => setField<DateTime>(sentAtField, value);

  /// Status field name
  static const String statusField = 'status';

  /// Status
  String get status => getField<String>(statusField, defaultValue: 'sent')!;
  set status(String value) => setField<String>(statusField, value);

  /// Error Message field name
  static const String errorMessageField = 'error_message';

  /// Error Message
  String? get errorMessage => getField<String>(errorMessageField);
  set errorMessage(String? value) => setField<String>(errorMessageField, value);

  /// Token Count field name
  static const String tokenCountField = 'token_count';

  /// Token Count
  int get tokenCount => getField<int>(tokenCountField, defaultValue: 0)!;
  set tokenCount(int value) => setField<int>(tokenCountField, value);

  /// Company Id field name
  static const String companyIdField = 'company_id';

  /// Company Id
  String? get companyId => getField<String>(companyIdField);
  set companyId(String? value) => setField<String>(companyIdField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Make a copy of the current [PushNotificationCampaignLogRow]
  /// overriding the provided fields
  PushNotificationCampaignLogRow copyWith({
    String? categoryKey,
    String? notificationId,
    String? userId,
    String? id,
    DateTime? sentAt,
    String? status,
    String? errorMessage,
    int? tokenCount,
    String? companyId,
    DateTime? createdAt,
  }) => PushNotificationCampaignLogRow.fromJson({
    'category_key': supaSerialize(categoryKey) ?? data['category_key'],
    'notification_id': supaSerialize(notificationId) ?? data['notification_id'],
    'user_id': supaSerialize(userId) ?? data['user_id'],
    'id': supaSerialize(id) ?? data['id'],
    'sent_at': supaSerialize(sentAt) ?? data['sent_at'],
    'status': supaSerialize(status) ?? data['status'],
    'error_message': supaSerialize(errorMessage) ?? data['error_message'],
    'token_count': supaSerialize(tokenCount) ?? data['token_count'],
    'company_id': supaSerialize(companyId) ?? data['company_id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
  });
}

/// Tag: v2
/// Date: 2026-03-20 19:41:33.402268
