//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Push Notification Table
class PushNotificationTable extends SupabaseTable<PushNotificationRow> {
  /// Table Name
  @override
  String get tableName => 'push_notification';

  /// Create a [PushNotificationRow] from the [data] provided
  @override
  PushNotificationRow createRow(Map<String, dynamic> data) =>
      PushNotificationRow.fromJson(data);
}

/// Push Notification Row
class PushNotificationRow extends SupabaseDataRow {
  /// Push Notification Row
  PushNotificationRow({
    String? id,
    DateTime? createdAt,
    String? createdBy,
    String? title,
    String? body,
    String? photoBucket,
    String? photoFolderPath,
    String? photoFileName,
    String? landingPageUrl,
    bool? isScheduled,
    String? scheduledDate,
    String? scheduledTimeKst,
    bool? isDraft,
    DateTime? lastSentAt,
    bool? isDeleted,
    String? companyId,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (createdBy != null) 'created_by': supaSerialize(createdBy),
         if (title != null) 'title': supaSerialize(title),
         if (body != null) 'body': supaSerialize(body),
         if (photoBucket != null) 'photo_bucket': supaSerialize(photoBucket),
         if (photoFolderPath != null)
           'photo_folder_path': supaSerialize(photoFolderPath),
         if (photoFileName != null)
           'photo_file_name': supaSerialize(photoFileName),
         if (landingPageUrl != null)
           'landing_page_url': supaSerialize(landingPageUrl),
         if (isScheduled != null) 'is_scheduled': supaSerialize(isScheduled),
         if (scheduledDate != null)
           'scheduled_date': supaSerialize(scheduledDate),
         if (scheduledTimeKst != null)
           'scheduled_time_kst': supaSerialize(scheduledTimeKst),
         if (isDraft != null) 'is_draft': supaSerialize(isDraft),
         if (lastSentAt != null) 'last_sent_at': supaSerialize(lastSentAt),
         if (isDeleted != null) 'is_deleted': supaSerialize(isDeleted),
         if (companyId != null) 'company_id': supaSerialize(companyId),
       });

  /// Push Notification Row
  const PushNotificationRow._(super.data);

  /// Create Push Notification Row from a [data] map
  factory PushNotificationRow.fromJson(Map<String, dynamic> data) =>
      PushNotificationRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => PushNotificationTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Created By field name
  static const String createdByField = 'created_by';

  /// Created By
  String get createdBy =>
      getField<String>(createdByField, defaultValue: 'auth.')!;
  set createdBy(String value) => setField<String>(createdByField, value);

  /// Title field name
  static const String titleField = 'title';

  /// Title
  String? get title => getField<String>(titleField);
  set title(String? value) => setField<String>(titleField, value);

  /// Body field name
  static const String bodyField = 'body';

  /// Body
  String? get body => getField<String>(bodyField);
  set body(String? value) => setField<String>(bodyField, value);

  /// Photo Bucket field name
  static const String photoBucketField = 'photo_bucket';

  /// Photo Bucket
  String? get photoBucket => getField<String>(photoBucketField);
  set photoBucket(String? value) => setField<String>(photoBucketField, value);

  /// Photo Folder Path field name
  static const String photoFolderPathField = 'photo_folder_path';

  /// Photo Folder Path
  String? get photoFolderPath => getField<String>(photoFolderPathField);
  set photoFolderPath(String? value) =>
      setField<String>(photoFolderPathField, value);

  /// Photo File Name field name
  static const String photoFileNameField = 'photo_file_name';

  /// Photo File Name
  String? get photoFileName => getField<String>(photoFileNameField);
  set photoFileName(String? value) =>
      setField<String>(photoFileNameField, value);

  /// Landing Page Url field name
  static const String landingPageUrlField = 'landing_page_url';

  /// Landing Page Url
  String? get landingPageUrl => getField<String>(landingPageUrlField);
  set landingPageUrl(String? value) =>
      setField<String>(landingPageUrlField, value);

  /// Is Scheduled field name
  static const String isScheduledField = 'is_scheduled';

  /// Is Scheduled
  bool get isScheduled =>
      getField<bool>(isScheduledField, defaultValue: false)!;
  set isScheduled(bool value) => setField<bool>(isScheduledField, value);

  /// Scheduled Date field name
  static const String scheduledDateField = 'scheduled_date';

  /// Scheduled Date
  String? get scheduledDate => getField<String>(scheduledDateField);
  set scheduledDate(String? value) =>
      setField<String>(scheduledDateField, value);

  /// Scheduled Time Kst field name
  static const String scheduledTimeKstField = 'scheduled_time_kst';

  /// Scheduled Time Kst
  String? get scheduledTimeKst => getField<String>(scheduledTimeKstField);
  set scheduledTimeKst(String? value) =>
      setField<String>(scheduledTimeKstField, value);

  /// Is Draft field name
  static const String isDraftField = 'is_draft';

  /// Is Draft
  bool get isDraft => getField<bool>(isDraftField, defaultValue: true)!;
  set isDraft(bool value) => setField<bool>(isDraftField, value);

  /// Last Sent At field name
  static const String lastSentAtField = 'last_sent_at';

  /// Last Sent At
  DateTime? get lastSentAt => getField<DateTime>(lastSentAtField);
  set lastSentAt(DateTime? value) => setField<DateTime>(lastSentAtField, value);

  /// Is Deleted field name
  static const String isDeletedField = 'is_deleted';

  /// Is Deleted
  bool get isDeleted => getField<bool>(isDeletedField, defaultValue: false)!;
  set isDeleted(bool value) => setField<bool>(isDeletedField, value);

  /// Company Id field name
  static const String companyIdField = 'company_id';

  /// Company Id
  String? get companyId => getField<String>(companyIdField);
  set companyId(String? value) => setField<String>(companyIdField, value);

  /// Make a copy of the current [PushNotificationRow]
  /// overriding the provided fields
  PushNotificationRow copyWith({
    String? id,
    DateTime? createdAt,
    String? createdBy,
    String? title,
    String? body,
    String? photoBucket,
    String? photoFolderPath,
    String? photoFileName,
    String? landingPageUrl,
    bool? isScheduled,
    String? scheduledDate,
    String? scheduledTimeKst,
    bool? isDraft,
    DateTime? lastSentAt,
    bool? isDeleted,
    String? companyId,
  }) => PushNotificationRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'created_by': supaSerialize(createdBy) ?? data['created_by'],
    'title': supaSerialize(title) ?? data['title'],
    'body': supaSerialize(body) ?? data['body'],
    'photo_bucket': supaSerialize(photoBucket) ?? data['photo_bucket'],
    'photo_folder_path':
        supaSerialize(photoFolderPath) ?? data['photo_folder_path'],
    'photo_file_name': supaSerialize(photoFileName) ?? data['photo_file_name'],
    'landing_page_url':
        supaSerialize(landingPageUrl) ?? data['landing_page_url'],
    'is_scheduled': supaSerialize(isScheduled) ?? data['is_scheduled'],
    'scheduled_date': supaSerialize(scheduledDate) ?? data['scheduled_date'],
    'scheduled_time_kst':
        supaSerialize(scheduledTimeKst) ?? data['scheduled_time_kst'],
    'is_draft': supaSerialize(isDraft) ?? data['is_draft'],
    'last_sent_at': supaSerialize(lastSentAt) ?? data['last_sent_at'],
    'is_deleted': supaSerialize(isDeleted) ?? data['is_deleted'],
    'company_id': supaSerialize(companyId) ?? data['company_id'],
  });
}

/// Tag: v2
/// Date: 2026-03-17 11:11:48.542520
