//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Push Notification Token Table
class PushNotificationTokenTable
    extends SupabaseTable<PushNotificationTokenRow> {
  /// Table Name
  @override
  String get tableName => 'push_notification_token';

  /// Create a [PushNotificationTokenRow] from the [data] provided
  @override
  PushNotificationTokenRow createRow(Map<String, dynamic> data) =>
      PushNotificationTokenRow.fromJson(data);
}

/// Push Notification Token Row
class PushNotificationTokenRow extends SupabaseDataRow {
  /// Push Notification Token Row
  PushNotificationTokenRow({
    required String token,
    String? id,
    String? user,
    DateTime? createdAt,
  }) : super({
         'token': supaSerialize(token),
         if (id != null) 'id': supaSerialize(id),
         if (user != null) 'user': supaSerialize(user),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
       });

  /// Push Notification Token Row
  const PushNotificationTokenRow._(super.data);

  /// Create Push Notification Token Row from a [data] map
  factory PushNotificationTokenRow.fromJson(Map<String, dynamic> data) =>
      PushNotificationTokenRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => PushNotificationTokenTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// User field name
  static const String userField = 'user';

  /// User
  String get user => getField<String>(userField, defaultValue: 'auth.')!;
  set user(String value) => setField<String>(userField, value);

  /// Token field name
  static const String tokenField = 'token';

  /// Token
  String get token => getField<String>(tokenField)!;
  set token(String value) => setField<String>(tokenField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Make a copy of the current [PushNotificationTokenRow]
  /// overriding the provided fields
  PushNotificationTokenRow copyWith({
    String? token,
    String? id,
    String? user,
    DateTime? createdAt,
  }) => PushNotificationTokenRow.fromJson({
    'token': supaSerialize(token) ?? data['token'],
    'id': supaSerialize(id) ?? data['id'],
    'user': supaSerialize(user) ?? data['user'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
  });
}

/// Tag: v2
/// Date: 2026-01-15 14:21:42.926442
