//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Report Table
class ReportTable extends SupabaseTable<ReportRow> {
  /// Table Name
  @override
  String get tableName => 'report';

  /// Create a [ReportRow] from the [data] provided
  @override
  ReportRow createRow(Map<String, dynamic> data) => ReportRow.fromJson(data);
}

/// Report Row
class ReportRow extends SupabaseDataRow {
  /// Report Row
  ReportRow({
    String? id,
    DateTime? createdAt,
    String? reporter,
    String? storyReported,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (reporter != null) 'reporter': supaSerialize(reporter),
         if (storyReported != null)
           'story_reported': supaSerialize(storyReported),
       });

  /// Report Row
  const ReportRow._(super.data);

  /// Create Report Row from a [data] map
  factory ReportRow.fromJson(Map<String, dynamic> data) =>
      ReportRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => ReportTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Reporter field name
  static const String reporterField = 'reporter';

  /// Reporter
  String? get reporter => getField<String>(reporterField);
  set reporter(String? value) => setField<String>(reporterField, value);

  /// Story Reported field name
  static const String storyReportedField = 'story_reported';

  /// Story Reported
  String? get storyReported => getField<String>(storyReportedField);
  set storyReported(String? value) =>
      setField<String>(storyReportedField, value);

  /// Make a copy of the current [ReportRow]
  /// overriding the provided fields
  ReportRow copyWith({
    String? id,
    DateTime? createdAt,
    String? reporter,
    String? storyReported,
  }) => ReportRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'reporter': supaSerialize(reporter) ?? data['reporter'],
    'story_reported': supaSerialize(storyReported) ?? data['story_reported'],
  });
}

/// Tag: v2
/// Date: 2026-01-30 17:50:32.130631
