//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Setting Table
class SettingTable extends SupabaseTable<SettingRow> {
  /// Table Name
  @override
  String get tableName => 'setting';

  /// Create a [SettingRow] from the [data] provided
  @override
  SettingRow createRow(Map<String, dynamic> data) => SettingRow.fromJson(data);
}

/// Setting Row
class SettingRow extends SupabaseDataRow {
  /// Setting Row
  SettingRow({
    required String id,
    DateTime? createdAt,
    String? name,
    String? valueText,
    double? valueNum,
  }) : super({
         'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (name != null) 'name': supaSerialize(name),
         if (valueText != null) 'value_text': supaSerialize(valueText),
         if (valueNum != null) 'value_num': supaSerialize(valueNum),
       });

  /// Setting Row
  const SettingRow._(super.data);

  /// Create Setting Row from a [data] map
  factory SettingRow.fromJson(Map<String, dynamic> data) =>
      SettingRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => SettingTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField)!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Name field name
  static const String nameField = 'name';

  /// Name
  String? get name => getField<String>(nameField);
  set name(String? value) => setField<String>(nameField, value);

  /// Value Text field name
  static const String valueTextField = 'value_text';

  /// Value Text
  String? get valueText => getField<String>(valueTextField);
  set valueText(String? value) => setField<String>(valueTextField, value);

  /// Value Num field name
  static const String valueNumField = 'value_num';

  /// Value Num
  double? get valueNum => getField<double>(valueNumField);
  set valueNum(double? value) => setField<double>(valueNumField, value);

  /// Make a copy of the current [SettingRow]
  /// overriding the provided fields
  SettingRow copyWith({
    String? id,
    DateTime? createdAt,
    String? name,
    String? valueText,
    double? valueNum,
  }) => SettingRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'name': supaSerialize(name) ?? data['name'],
    'value_text': supaSerialize(valueText) ?? data['value_text'],
    'value_num': supaSerialize(valueNum) ?? data['value_num'],
  });
}

/// Tag: v2
/// Date: 2026-03-13 09:30:01.778392
