//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Shipping Address Table
class ShippingAddressTable extends SupabaseTable<ShippingAddressRow> {
  /// Table Name
  @override
  String get tableName => 'shipping_address';

  /// Create a [ShippingAddressRow] from the [data] provided
  @override
  ShippingAddressRow createRow(Map<String, dynamic> data) =>
      ShippingAddressRow.fromJson(data);
}

/// Shipping Address Row
class ShippingAddressRow extends SupabaseDataRow {
  /// Shipping Address Row
  ShippingAddressRow({
    String? id,
    DateTime? createdAt,
    String? fullAddress,
    String? user,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (fullAddress != null) 'full_address': supaSerialize(fullAddress),
         if (user != null) 'user': supaSerialize(user),
       });

  /// Shipping Address Row
  const ShippingAddressRow._(super.data);

  /// Create Shipping Address Row from a [data] map
  factory ShippingAddressRow.fromJson(Map<String, dynamic> data) =>
      ShippingAddressRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => ShippingAddressTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Full Address field name
  static const String fullAddressField = 'full_address';

  /// Full Address
  String? get fullAddress => getField<String>(fullAddressField);
  set fullAddress(String? value) => setField<String>(fullAddressField, value);

  /// User field name
  static const String userField = 'user';

  /// User
  String? get user => getField<String>(userField);
  set user(String? value) => setField<String>(userField, value);

  /// Make a copy of the current [ShippingAddressRow]
  /// overriding the provided fields
  ShippingAddressRow copyWith({
    String? id,
    DateTime? createdAt,
    String? fullAddress,
    String? user,
  }) => ShippingAddressRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'full_address': supaSerialize(fullAddress) ?? data['full_address'],
    'user': supaSerialize(user) ?? data['user'],
  });
}

/// Tag: v2
/// Date: 2025-11-28 10:14:23.493093
