//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Stamp Table
class StampTable extends SupabaseTable<StampRow> {
  /// Table Name
  @override
  String get tableName => 'stamp';

  /// Create a [StampRow] from the [data] provided
  @override
  StampRow createRow(Map<String, dynamic> data) => StampRow.fromJson(data);
}

/// Stamp Row
class StampRow extends SupabaseDataRow {
  /// Stamp Row
  StampRow({
    String? id,
    DateTime? createdAt,
    String? name,
    String? bucket,
    String? fileName,
    String? folderPath,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (name != null) 'name': supaSerialize(name),
         if (bucket != null) 'bucket': supaSerialize(bucket),
         if (fileName != null) 'file_name': supaSerialize(fileName),
         if (folderPath != null) 'folder_path': supaSerialize(folderPath),
       });

  /// Stamp Row
  const StampRow._(super.data);

  /// Create Stamp Row from a [data] map
  factory StampRow.fromJson(Map<String, dynamic> data) =>
      StampRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => StampTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Name field name
  static const String nameField = 'name';

  /// Name
  String? get name => getField<String>(nameField);
  set name(String? value) => setField<String>(nameField, value);

  /// Bucket field name
  static const String bucketField = 'bucket';

  /// Bucket
  String? get bucket => getField<String>(bucketField);
  set bucket(String? value) => setField<String>(bucketField, value);

  /// File Name field name
  static const String fileNameField = 'file_name';

  /// File Name
  String? get fileName => getField<String>(fileNameField);
  set fileName(String? value) => setField<String>(fileNameField, value);

  /// Folder Path field name
  static const String folderPathField = 'folder_path';

  /// Folder Path
  String? get folderPath => getField<String>(folderPathField);
  set folderPath(String? value) => setField<String>(folderPathField, value);

  /// Make a copy of the current [StampRow]
  /// overriding the provided fields
  StampRow copyWith({
    String? id,
    DateTime? createdAt,
    String? name,
    String? bucket,
    String? fileName,
    String? folderPath,
  }) => StampRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'name': supaSerialize(name) ?? data['name'],
    'bucket': supaSerialize(bucket) ?? data['bucket'],
    'file_name': supaSerialize(fileName) ?? data['file_name'],
    'folder_path': supaSerialize(folderPath) ?? data['folder_path'],
  });
}

/// Tag: v2
/// Date: 2026-01-16 16:22:11.182041
