//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Stamp Table
class StampTable extends SupabaseTable<StampRow> {
  /// Table Name
  @override
  String get tableName => 'stamp';

  /// Create a [StampRow] from the [data] provided
  @override
  StampRow createRow(Map<String, dynamic> data) => StampRow.fromJson(data);
}

/// Stamp Row
class StampRow extends SupabaseDataRow {
  /// Stamp Row
  StampRow({
    String? id,
    DateTime? createdAt,
    String? name,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (name != null) 'name': supaSerialize(name),
       });

  /// Stamp Row
  const StampRow._(super.data);

  /// Create Stamp Row from a [data] map
  factory StampRow.fromJson(Map<String, dynamic> data) =>
      StampRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => StampTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Name field name
  static const String nameField = 'name';

  /// Name
  String? get name => getField<String>(nameField);
  set name(String? value) => setField<String>(nameField, value);

  /// Make a copy of the current [StampRow]
  /// overriding the provided fields
  StampRow copyWith({
    String? id,
    DateTime? createdAt,
    String? name,
  }) => StampRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'name': supaSerialize(name) ?? data['name'],
  });
}

/// Tag: v2
/// Date: 2025-11-25 09:28:17.062851
