//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Story Table
class StoryTable extends SupabaseTable<StoryRow> {
  /// Table Name
  @override
  String get tableName => 'story';

  /// Create a [StoryRow] from the [data] provided
  @override
  StoryRow createRow(Map<String, dynamic> data) => StoryRow.fromJson(data);
}

/// Story Row
class StoryRow extends SupabaseDataRow {
  /// Story Row
  StoryRow({
    String? id,
    DateTime? createdAt,
    String? createdBy,
    String? title,
    String? subtitle,
    String? thumbnailBucket,
    String? thumbnailFolderPath,
    String? thumbnailFileName,
    String? content,
    String? placeName,
    String? detailedAddress,
    String? seoTitle,
    String? seoKeywords,
    String? seoDescription,
    String? seoUrl,
    bool? isPublished,
    bool? isDeleted,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (createdBy != null) 'created_by': supaSerialize(createdBy),
         if (title != null) 'title': supaSerialize(title),
         if (subtitle != null) 'subtitle': supaSerialize(subtitle),
         if (thumbnailBucket != null)
           'thumbnail_bucket': supaSerialize(thumbnailBucket),
         if (thumbnailFolderPath != null)
           'thumbnail_folder_path': supaSerialize(thumbnailFolderPath),
         if (thumbnailFileName != null)
           'thumbnail_file_name': supaSerialize(thumbnailFileName),
         if (content != null) 'content': supaSerialize(content),
         if (placeName != null) 'place_name': supaSerialize(placeName),
         if (detailedAddress != null)
           'detailed_address': supaSerialize(detailedAddress),
         if (seoTitle != null) 'seo_title': supaSerialize(seoTitle),
         if (seoKeywords != null) 'seo_keywords': supaSerialize(seoKeywords),
         if (seoDescription != null)
           'seo_description': supaSerialize(seoDescription),
         if (seoUrl != null) 'seo_url': supaSerialize(seoUrl),
         if (isPublished != null) 'is_published': supaSerialize(isPublished),
         if (isDeleted != null) 'is_deleted': supaSerialize(isDeleted),
       });

  /// Story Row
  const StoryRow._(super.data);

  /// Create Story Row from a [data] map
  factory StoryRow.fromJson(Map<String, dynamic> data) =>
      StoryRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => StoryTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Created By field name
  static const String createdByField = 'created_by';

  /// Created By
  String get createdBy =>
      getField<String>(createdByField, defaultValue: 'auth.')!;
  set createdBy(String value) => setField<String>(createdByField, value);

  /// Title field name
  static const String titleField = 'title';

  /// Title
  String? get title => getField<String>(titleField);
  set title(String? value) => setField<String>(titleField, value);

  /// Subtitle field name
  static const String subtitleField = 'subtitle';

  /// Subtitle
  String? get subtitle => getField<String>(subtitleField);
  set subtitle(String? value) => setField<String>(subtitleField, value);

  /// Thumbnail Bucket field name
  static const String thumbnailBucketField = 'thumbnail_bucket';

  /// Thumbnail Bucket
  String? get thumbnailBucket => getField<String>(thumbnailBucketField);
  set thumbnailBucket(String? value) =>
      setField<String>(thumbnailBucketField, value);

  /// Thumbnail Folder Path field name
  static const String thumbnailFolderPathField = 'thumbnail_folder_path';

  /// Thumbnail Folder Path
  String? get thumbnailFolderPath => getField<String>(thumbnailFolderPathField);
  set thumbnailFolderPath(String? value) =>
      setField<String>(thumbnailFolderPathField, value);

  /// Thumbnail File Name field name
  static const String thumbnailFileNameField = 'thumbnail_file_name';

  /// Thumbnail File Name
  String? get thumbnailFileName => getField<String>(thumbnailFileNameField);
  set thumbnailFileName(String? value) =>
      setField<String>(thumbnailFileNameField, value);

  /// Content field name
  static const String contentField = 'content';

  /// Content
  String? get content => getField<String>(contentField);
  set content(String? value) => setField<String>(contentField, value);

  /// Place Name field name
  static const String placeNameField = 'place_name';

  /// Place Name
  String? get placeName => getField<String>(placeNameField);
  set placeName(String? value) => setField<String>(placeNameField, value);

  /// Detailed Address field name
  static const String detailedAddressField = 'detailed_address';

  /// Detailed Address
  String? get detailedAddress => getField<String>(detailedAddressField);
  set detailedAddress(String? value) =>
      setField<String>(detailedAddressField, value);

  /// Seo Title field name
  static const String seoTitleField = 'seo_title';

  /// Seo Title
  String? get seoTitle => getField<String>(seoTitleField);
  set seoTitle(String? value) => setField<String>(seoTitleField, value);

  /// Seo Keywords field name
  static const String seoKeywordsField = 'seo_keywords';

  /// Seo Keywords
  String? get seoKeywords => getField<String>(seoKeywordsField);
  set seoKeywords(String? value) => setField<String>(seoKeywordsField, value);

  /// Seo Description field name
  static const String seoDescriptionField = 'seo_description';

  /// Seo Description
  String? get seoDescription => getField<String>(seoDescriptionField);
  set seoDescription(String? value) =>
      setField<String>(seoDescriptionField, value);

  /// Seo Url field name
  static const String seoUrlField = 'seo_url';

  /// Seo Url
  String? get seoUrl => getField<String>(seoUrlField);
  set seoUrl(String? value) => setField<String>(seoUrlField, value);

  /// Is Published field name
  static const String isPublishedField = 'is_published';

  /// Is Published
  bool get isPublished =>
      getField<bool>(isPublishedField, defaultValue: false)!;
  set isPublished(bool value) => setField<bool>(isPublishedField, value);

  /// Is Deleted field name
  static const String isDeletedField = 'is_deleted';

  /// Is Deleted
  bool get isDeleted => getField<bool>(isDeletedField, defaultValue: false)!;
  set isDeleted(bool value) => setField<bool>(isDeletedField, value);

  /// Make a copy of the current [StoryRow]
  /// overriding the provided fields
  StoryRow copyWith({
    String? id,
    DateTime? createdAt,
    String? createdBy,
    String? title,
    String? subtitle,
    String? thumbnailBucket,
    String? thumbnailFolderPath,
    String? thumbnailFileName,
    String? content,
    String? placeName,
    String? detailedAddress,
    String? seoTitle,
    String? seoKeywords,
    String? seoDescription,
    String? seoUrl,
    bool? isPublished,
    bool? isDeleted,
  }) => StoryRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'created_by': supaSerialize(createdBy) ?? data['created_by'],
    'title': supaSerialize(title) ?? data['title'],
    'subtitle': supaSerialize(subtitle) ?? data['subtitle'],
    'thumbnail_bucket':
        supaSerialize(thumbnailBucket) ?? data['thumbnail_bucket'],
    'thumbnail_folder_path':
        supaSerialize(thumbnailFolderPath) ?? data['thumbnail_folder_path'],
    'thumbnail_file_name':
        supaSerialize(thumbnailFileName) ?? data['thumbnail_file_name'],
    'content': supaSerialize(content) ?? data['content'],
    'place_name': supaSerialize(placeName) ?? data['place_name'],
    'detailed_address':
        supaSerialize(detailedAddress) ?? data['detailed_address'],
    'seo_title': supaSerialize(seoTitle) ?? data['seo_title'],
    'seo_keywords': supaSerialize(seoKeywords) ?? data['seo_keywords'],
    'seo_description': supaSerialize(seoDescription) ?? data['seo_description'],
    'seo_url': supaSerialize(seoUrl) ?? data['seo_url'],
    'is_published': supaSerialize(isPublished) ?? data['is_published'],
    'is_deleted': supaSerialize(isDeleted) ?? data['is_deleted'],
  });
}

/// Tag: v2
/// Date: 2026-02-04 11:46:32.479202
