//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Story Blocked Table
class StoryBlockedTable extends SupabaseTable<StoryBlockedRow> {
  /// Table Name
  @override
  String get tableName => 'story_blocked';

  /// Create a [StoryBlockedRow] from the [data] provided
  @override
  StoryBlockedRow createRow(Map<String, dynamic> data) =>
      StoryBlockedRow.fromJson(data);
}

/// Story Blocked Row
class StoryBlockedRow extends SupabaseDataRow {
  /// Story Blocked Row
  StoryBlockedRow({
    required String story,
    String? blocker,
    DateTime? createdAt,
  }) : super({
         'story': supaSerialize(story),
         if (blocker != null) 'blocker': supaSerialize(blocker),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
       });

  /// Story Blocked Row
  const StoryBlockedRow._(super.data);

  /// Create Story Blocked Row from a [data] map
  factory StoryBlockedRow.fromJson(Map<String, dynamic> data) =>
      StoryBlockedRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => StoryBlockedTable();

  /// Blocker field name
  static const String blockerField = 'blocker';

  /// Blocker
  String get blocker => getField<String>(blockerField, defaultValue: 'auth.')!;
  set blocker(String value) => setField<String>(blockerField, value);

  /// Story field name
  static const String storyField = 'story';

  /// Story
  String get story => getField<String>(storyField)!;
  set story(String value) => setField<String>(storyField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Make a copy of the current [StoryBlockedRow]
  /// overriding the provided fields
  StoryBlockedRow copyWith({
    String? story,
    String? blocker,
    DateTime? createdAt,
  }) => StoryBlockedRow.fromJson({
    'story': supaSerialize(story) ?? data['story'],
    'blocker': supaSerialize(blocker) ?? data['blocker'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
  });
}

/// Tag: v2
/// Date: 2026-03-13 15:28:25.404409
