//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Story Like Table
class StoryLikeTable extends SupabaseTable<StoryLikeRow> {
  /// Table Name
  @override
  String get tableName => 'story_like';

  /// Create a [StoryLikeRow] from the [data] provided
  @override
  StoryLikeRow createRow(Map<String, dynamic> data) =>
      StoryLikeRow.fromJson(data);
}

/// Story Like Row
class StoryLikeRow extends SupabaseDataRow {
  /// Story Like Row
  StoryLikeRow({
    String? id,
    DateTime? createdAt,
    String? story,
    String? likedBy,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (story != null) 'story': supaSerialize(story),
         if (likedBy != null) 'liked_by': supaSerialize(likedBy),
       });

  /// Story Like Row
  const StoryLikeRow._(super.data);

  /// Create Story Like Row from a [data] map
  factory StoryLikeRow.fromJson(Map<String, dynamic> data) =>
      StoryLikeRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => StoryLikeTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Story field name
  static const String storyField = 'story';

  /// Story
  String? get story => getField<String>(storyField);
  set story(String? value) => setField<String>(storyField, value);

  /// Liked By field name
  static const String likedByField = 'liked_by';

  /// Liked By
  String get likedBy => getField<String>(likedByField, defaultValue: 'auth.')!;
  set likedBy(String value) => setField<String>(likedByField, value);

  /// Make a copy of the current [StoryLikeRow]
  /// overriding the provided fields
  StoryLikeRow copyWith({
    String? id,
    DateTime? createdAt,
    String? story,
    String? likedBy,
  }) => StoryLikeRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'story': supaSerialize(story) ?? data['story'],
    'liked_by': supaSerialize(likedBy) ?? data['liked_by'],
  });
}

/// Tag: v2
/// Date: 2026-03-12 10:37:49.674431
