//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Story Related Mission Table
class StoryRelatedMissionTable extends SupabaseTable<StoryRelatedMissionRow> {
  /// Table Name
  @override
  String get tableName => 'story_related_mission';

  /// Create a [StoryRelatedMissionRow] from the [data] provided
  @override
  StoryRelatedMissionRow createRow(Map<String, dynamic> data) =>
      StoryRelatedMissionRow.fromJson(data);
}

/// Story Related Mission Row
class StoryRelatedMissionRow extends SupabaseDataRow {
  /// Story Related Mission Row
  StoryRelatedMissionRow({
    required String story,
    required String mission,
    String? id,
    DateTime? createdAt,
    String? createdBy,
  }) : super({
         'story': supaSerialize(story),
         'mission': supaSerialize(mission),
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (createdBy != null) 'created_by': supaSerialize(createdBy),
       });

  /// Story Related Mission Row
  const StoryRelatedMissionRow._(super.data);

  /// Create Story Related Mission Row from a [data] map
  factory StoryRelatedMissionRow.fromJson(Map<String, dynamic> data) =>
      StoryRelatedMissionRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => StoryRelatedMissionTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Created By field name
  static const String createdByField = 'created_by';

  /// Created By
  String get createdBy =>
      getField<String>(createdByField, defaultValue: 'auth.')!;
  set createdBy(String value) => setField<String>(createdByField, value);

  /// Story field name
  static const String storyField = 'story';

  /// Story
  String get story => getField<String>(storyField)!;
  set story(String value) => setField<String>(storyField, value);

  /// Mission field name
  static const String missionField = 'mission';

  /// Mission
  String get mission => getField<String>(missionField)!;
  set mission(String value) => setField<String>(missionField, value);

  /// Make a copy of the current [StoryRelatedMissionRow]
  /// overriding the provided fields
  StoryRelatedMissionRow copyWith({
    String? story,
    String? mission,
    String? id,
    DateTime? createdAt,
    String? createdBy,
  }) => StoryRelatedMissionRow.fromJson({
    'story': supaSerialize(story) ?? data['story'],
    'mission': supaSerialize(mission) ?? data['mission'],
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'created_by': supaSerialize(createdBy) ?? data['created_by'],
  });
}

/// Tag: v2
/// Date: 2026-01-05 16:52:08.915593
