//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Story Comment Table
class StoryCommentTable extends SupabaseTable<StoryCommentRow> {
  /// Table Name
  @override
  String get tableName => 'story_comment';

  /// Create a [StoryCommentRow] from the [data] provided
  @override
  StoryCommentRow createRow(Map<String, dynamic> data) =>
      StoryCommentRow.fromJson(data);
}

/// Story Comment Row
class StoryCommentRow extends SupabaseDataRow {
  /// Story Comment Row
  StoryCommentRow({
    String? id,
    DateTime? createdAt,
    String? story,
    String? comment,
    String? commentBy,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (story != null) 'story': supaSerialize(story),
         if (comment != null) 'comment': supaSerialize(comment),
         if (commentBy != null) 'comment_by': supaSerialize(commentBy),
       });

  /// Story Comment Row
  const StoryCommentRow._(super.data);

  /// Create Story Comment Row from a [data] map
  factory StoryCommentRow.fromJson(Map<String, dynamic> data) =>
      StoryCommentRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => StoryCommentTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Story field name
  static const String storyField = 'story';

  /// Story
  String? get story => getField<String>(storyField);
  set story(String? value) => setField<String>(storyField, value);

  /// Comment field name
  static const String commentField = 'comment';

  /// Comment
  String? get comment => getField<String>(commentField);
  set comment(String? value) => setField<String>(commentField, value);

  /// Comment By field name
  static const String commentByField = 'comment_by';

  /// Comment By
  String get commentBy =>
      getField<String>(commentByField, defaultValue: 'auth.')!;
  set commentBy(String value) => setField<String>(commentByField, value);

  /// Make a copy of the current [StoryCommentRow]
  /// overriding the provided fields
  StoryCommentRow copyWith({
    String? id,
    DateTime? createdAt,
    String? story,
    String? comment,
    String? commentBy,
  }) => StoryCommentRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'story': supaSerialize(story) ?? data['story'],
    'comment': supaSerialize(comment) ?? data['comment'],
    'comment_by': supaSerialize(commentBy) ?? data['comment_by'],
  });
}

/// Tag: v2
/// Date: 2026-03-10 17:29:12.964957
