//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Story Tag Table
class StoryTagTable extends SupabaseTable<StoryTagRow> {
  /// Table Name
  @override
  String get tableName => 'story_tag';

  /// Create a [StoryTagRow] from the [data] provided
  @override
  StoryTagRow createRow(Map<String, dynamic> data) =>
      StoryTagRow.fromJson(data);
}

/// Story Tag Row
class StoryTagRow extends SupabaseDataRow {
  /// Story Tag Row
  StoryTagRow({
    String? id,
    DateTime? createdAt,
    String? createdBy,
    String? story,
    String? tag,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (createdBy != null) 'created_by': supaSerialize(createdBy),
         if (story != null) 'story': supaSerialize(story),
         if (tag != null) 'tag': supaSerialize(tag),
       });

  /// Story Tag Row
  const StoryTagRow._(super.data);

  /// Create Story Tag Row from a [data] map
  factory StoryTagRow.fromJson(Map<String, dynamic> data) =>
      StoryTagRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => StoryTagTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Created By field name
  static const String createdByField = 'created_by';

  /// Created By
  String get createdBy =>
      getField<String>(createdByField, defaultValue: 'auth.')!;
  set createdBy(String value) => setField<String>(createdByField, value);

  /// Story field name
  static const String storyField = 'story';

  /// Story
  String? get story => getField<String>(storyField);
  set story(String? value) => setField<String>(storyField, value);

  /// Tag field name
  static const String tagField = 'tag';

  /// Tag
  String? get tag => getField<String>(tagField);
  set tag(String? value) => setField<String>(tagField, value);

  /// Make a copy of the current [StoryTagRow]
  /// overriding the provided fields
  StoryTagRow copyWith({
    String? id,
    DateTime? createdAt,
    String? createdBy,
    String? story,
    String? tag,
  }) => StoryTagRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'created_by': supaSerialize(createdBy) ?? data['created_by'],
    'story': supaSerialize(story) ?? data['story'],
    'tag': supaSerialize(tag) ?? data['tag'],
  });
}

/// Tag: v2
/// Date: 2025-12-03 16:25:28.160053
