//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Story Related Product Table
class StoryRelatedProductTable extends SupabaseTable<StoryRelatedProductRow> {
  /// Table Name
  @override
  String get tableName => 'story_related_product';

  /// Create a [StoryRelatedProductRow] from the [data] provided
  @override
  StoryRelatedProductRow createRow(Map<String, dynamic> data) =>
      StoryRelatedProductRow.fromJson(data);
}

/// Story Related Product Row
class StoryRelatedProductRow extends SupabaseDataRow {
  /// Story Related Product Row
  StoryRelatedProductRow({
    required String story,
    required String product,
    String? id,
    DateTime? createdAt,
    String? createdBy,
  }) : super({
         'story': supaSerialize(story),
         'product': supaSerialize(product),
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (createdBy != null) 'created_by': supaSerialize(createdBy),
       });

  /// Story Related Product Row
  const StoryRelatedProductRow._(super.data);

  /// Create Story Related Product Row from a [data] map
  factory StoryRelatedProductRow.fromJson(Map<String, dynamic> data) =>
      StoryRelatedProductRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => StoryRelatedProductTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Created By field name
  static const String createdByField = 'created_by';

  /// Created By
  String get createdBy =>
      getField<String>(createdByField, defaultValue: 'auth.')!;
  set createdBy(String value) => setField<String>(createdByField, value);

  /// Story field name
  static const String storyField = 'story';

  /// Story
  String get story => getField<String>(storyField)!;
  set story(String value) => setField<String>(storyField, value);

  /// Product field name
  static const String productField = 'product';

  /// Product
  String get product => getField<String>(productField)!;
  set product(String value) => setField<String>(productField, value);

  /// Make a copy of the current [StoryRelatedProductRow]
  /// overriding the provided fields
  StoryRelatedProductRow copyWith({
    String? story,
    String? product,
    String? id,
    DateTime? createdAt,
    String? createdBy,
  }) => StoryRelatedProductRow.fromJson({
    'story': supaSerialize(story) ?? data['story'],
    'product': supaSerialize(product) ?? data['product'],
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'created_by': supaSerialize(createdBy) ?? data['created_by'],
  });
}

/// Tag: v2
/// Date: 2026-01-21 21:59:57.945229
