//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Story Photo Table
class StoryPhotoTable extends SupabaseTable<StoryPhotoRow> {
  /// Table Name
  @override
  String get tableName => 'story_photo';

  /// Create a [StoryPhotoRow] from the [data] provided
  @override
  StoryPhotoRow createRow(Map<String, dynamic> data) =>
      StoryPhotoRow.fromJson(data);
}

/// Story Photo Row
class StoryPhotoRow extends SupabaseDataRow {
  /// Story Photo Row
  StoryPhotoRow({
    String? id,
    DateTime? createdAt,
    String? createdBy,
    String? story,
    String? bucket,
    String? folderPath,
    String? fileName,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (createdBy != null) 'created_by': supaSerialize(createdBy),
         if (story != null) 'story': supaSerialize(story),
         if (bucket != null) 'bucket': supaSerialize(bucket),
         if (folderPath != null) 'folder_path': supaSerialize(folderPath),
         if (fileName != null) 'file_name': supaSerialize(fileName),
       });

  /// Story Photo Row
  const StoryPhotoRow._(super.data);

  /// Create Story Photo Row from a [data] map
  factory StoryPhotoRow.fromJson(Map<String, dynamic> data) =>
      StoryPhotoRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => StoryPhotoTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Created By field name
  static const String createdByField = 'created_by';

  /// Created By
  String get createdBy =>
      getField<String>(createdByField, defaultValue: 'auth.')!;
  set createdBy(String value) => setField<String>(createdByField, value);

  /// Story field name
  static const String storyField = 'story';

  /// Story
  String? get story => getField<String>(storyField);
  set story(String? value) => setField<String>(storyField, value);

  /// Bucket field name
  static const String bucketField = 'bucket';

  /// Bucket
  String? get bucket => getField<String>(bucketField);
  set bucket(String? value) => setField<String>(bucketField, value);

  /// Folder Path field name
  static const String folderPathField = 'folder_path';

  /// Folder Path
  String? get folderPath => getField<String>(folderPathField);
  set folderPath(String? value) => setField<String>(folderPathField, value);

  /// File Name field name
  static const String fileNameField = 'file_name';

  /// File Name
  String? get fileName => getField<String>(fileNameField);
  set fileName(String? value) => setField<String>(fileNameField, value);

  /// Make a copy of the current [StoryPhotoRow]
  /// overriding the provided fields
  StoryPhotoRow copyWith({
    String? id,
    DateTime? createdAt,
    String? createdBy,
    String? story,
    String? bucket,
    String? folderPath,
    String? fileName,
  }) => StoryPhotoRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'created_by': supaSerialize(createdBy) ?? data['created_by'],
    'story': supaSerialize(story) ?? data['story'],
    'bucket': supaSerialize(bucket) ?? data['bucket'],
    'folder_path': supaSerialize(folderPath) ?? data['folder_path'],
    'file_name': supaSerialize(fileName) ?? data['file_name'],
  });
}

/// Tag: v2
/// Date: 2026-02-04 11:46:32.480920
