//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Sub Department Table
class SubDepartmentTable extends SupabaseTable<SubDepartmentRow> {
  /// Table Name
  @override
  String get tableName => 'sub_department';

  /// Create a [SubDepartmentRow] from the [data] provided
  @override
  SubDepartmentRow createRow(Map<String, dynamic> data) =>
      SubDepartmentRow.fromJson(data);
}

/// Sub Department Row
class SubDepartmentRow extends SupabaseDataRow {
  /// Sub Department Row
  SubDepartmentRow({
    String? id,
    String? name,
    String? department,
    DateTime? createdAt,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (name != null) 'name': supaSerialize(name),
         if (department != null) 'department': supaSerialize(department),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
       });

  /// Sub Department Row
  const SubDepartmentRow._(super.data);

  /// Create Sub Department Row from a [data] map
  factory SubDepartmentRow.fromJson(Map<String, dynamic> data) =>
      SubDepartmentRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => SubDepartmentTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Name field name
  static const String nameField = 'name';

  /// Name
  String? get name => getField<String>(nameField);
  set name(String? value) => setField<String>(nameField, value);

  /// Department field name
  static const String departmentField = 'department';

  /// Department
  String? get department => getField<String>(departmentField);
  set department(String? value) => setField<String>(departmentField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Make a copy of the current [SubDepartmentRow]
  /// overriding the provided fields
  SubDepartmentRow copyWith({
    String? id,
    String? name,
    String? department,
    DateTime? createdAt,
  }) => SubDepartmentRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'name': supaSerialize(name) ?? data['name'],
    'department': supaSerialize(department) ?? data['department'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
  });
}

/// Tag: v2
/// Date: 2026-03-12 16:36:10.638272
