//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Trigger Event Log Table
class TriggerEventLogTable extends SupabaseTable<TriggerEventLogRow> {
  /// Table Name
  @override
  String get tableName => 'trigger_event_log';

  /// Create a [TriggerEventLogRow] from the [data] provided
  @override
  TriggerEventLogRow createRow(Map<String, dynamic> data) =>
      TriggerEventLogRow.fromJson(data);
}

/// Trigger Event Log Row
class TriggerEventLogRow extends SupabaseDataRow {
  /// Trigger Event Log Row
  TriggerEventLogRow({
    required String functionName,
    required String operation,
    int? id,
    DateTime? occurredAt,
    String? errorMessage,
    String? errorDetail,
    String? errorHint,
    dynamic newRow,
    dynamic oldRow,
  }) : super({
         'function_name': supaSerialize(functionName),
         'operation': supaSerialize(operation),
         if (id != null) 'id': supaSerialize(id),
         if (occurredAt != null) 'occurred_at': supaSerialize(occurredAt),
         if (errorMessage != null) 'error_message': supaSerialize(errorMessage),
         if (errorDetail != null) 'error_detail': supaSerialize(errorDetail),
         if (errorHint != null) 'error_hint': supaSerialize(errorHint),
         if (newRow != null) 'new_row': supaSerialize(newRow),
         if (oldRow != null) 'old_row': supaSerialize(oldRow),
       });

  /// Trigger Event Log Row
  const TriggerEventLogRow._(super.data);

  /// Create Trigger Event Log Row from a [data] map
  factory TriggerEventLogRow.fromJson(Map<String, dynamic> data) =>
      TriggerEventLogRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => TriggerEventLogTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  int get id => getField<int>(idField, defaultValue: 1)!;
  set id(int value) => setField<int>(idField, value);

  /// Occurred At field name
  static const String occurredAtField = 'occurred_at';

  /// Occurred At
  DateTime get occurredAt =>
      getField<DateTime>(occurredAtField, defaultValue: DateTime.now())!;
  set occurredAt(DateTime value) => setField<DateTime>(occurredAtField, value);

  /// Function Name field name
  static const String functionNameField = 'function_name';

  /// Function Name
  String get functionName => getField<String>(functionNameField)!;
  set functionName(String value) => setField<String>(functionNameField, value);

  /// Operation field name
  static const String operationField = 'operation';

  /// Operation
  String get operation => getField<String>(operationField)!;
  set operation(String value) => setField<String>(operationField, value);

  /// Error Message field name
  static const String errorMessageField = 'error_message';

  /// Error Message
  String? get errorMessage => getField<String>(errorMessageField);
  set errorMessage(String? value) => setField<String>(errorMessageField, value);

  /// Error Detail field name
  static const String errorDetailField = 'error_detail';

  /// Error Detail
  String? get errorDetail => getField<String>(errorDetailField);
  set errorDetail(String? value) => setField<String>(errorDetailField, value);

  /// Error Hint field name
  static const String errorHintField = 'error_hint';

  /// Error Hint
  String? get errorHint => getField<String>(errorHintField);
  set errorHint(String? value) => setField<String>(errorHintField, value);

  /// New Row field name
  static const String newRowField = 'new_row';

  /// New Row
  dynamic get newRow => getField<dynamic>(newRowField);
  set newRow(dynamic value) => setField<dynamic>(newRowField, value);

  /// Old Row field name
  static const String oldRowField = 'old_row';

  /// Old Row
  dynamic get oldRow => getField<dynamic>(oldRowField);
  set oldRow(dynamic value) => setField<dynamic>(oldRowField, value);

  /// Make a copy of the current [TriggerEventLogRow]
  /// overriding the provided fields
  TriggerEventLogRow copyWith({
    String? functionName,
    String? operation,
    int? id,
    DateTime? occurredAt,
    String? errorMessage,
    String? errorDetail,
    String? errorHint,
    dynamic newRow,
    dynamic oldRow,
  }) => TriggerEventLogRow.fromJson({
    'function_name': supaSerialize(functionName) ?? data['function_name'],
    'operation': supaSerialize(operation) ?? data['operation'],
    'id': supaSerialize(id) ?? data['id'],
    'occurred_at': supaSerialize(occurredAt) ?? data['occurred_at'],
    'error_message': supaSerialize(errorMessage) ?? data['error_message'],
    'error_detail': supaSerialize(errorDetail) ?? data['error_detail'],
    'error_hint': supaSerialize(errorHint) ?? data['error_hint'],
    'new_row': supaSerialize(newRow) ?? data['new_row'],
    'old_row': supaSerialize(oldRow) ?? data['old_row'],
  });
}

/// Tag: v2
/// Date: 2026-03-24 15:11:23.950688
