//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// User Organization Table
class UserOrganizationTable extends SupabaseTable<UserOrganizationRow> {
  /// Table Name
  @override
  String get tableName => 'user_organization';

  /// Create a [UserOrganizationRow] from the [data] provided
  @override
  UserOrganizationRow createRow(Map<String, dynamic> data) =>
      UserOrganizationRow.fromJson(data);
}

/// User Organization Row
class UserOrganizationRow extends SupabaseDataRow {
  /// User Organization Row
  UserOrganizationRow({
    required String organization,
    String? user,
    DateTime? createdAt,
  }) : super({
         'organization': supaSerialize(organization),
         if (user != null) 'user': supaSerialize(user),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
       });

  /// User Organization Row
  const UserOrganizationRow._(super.data);

  /// Create User Organization Row from a [data] map
  factory UserOrganizationRow.fromJson(Map<String, dynamic> data) =>
      UserOrganizationRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => UserOrganizationTable();

  /// User field name
  static const String userField = 'user';

  /// User
  String get user => getField<String>(userField, defaultValue: '')!;
  set user(String value) => setField<String>(userField, value);

  /// Organization field name
  static const String organizationField = 'organization';

  /// Organization
  String get organization => getField<String>(organizationField)!;
  set organization(String value) => setField<String>(organizationField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Make a copy of the current [UserOrganizationRow]
  /// overriding the provided fields
  UserOrganizationRow copyWith({
    String? organization,
    String? user,
    DateTime? createdAt,
  }) => UserOrganizationRow.fromJson({
    'organization': supaSerialize(organization) ?? data['organization'],
    'user': supaSerialize(user) ?? data['user'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
  });
}

/// Tag: v2
/// Date: 2025-12-17 09:43:01.660879
