//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// User Guardian Table
class UserGuardianTable extends SupabaseTable<UserGuardianRow> {
  /// Table Name
  @override
  String get tableName => 'user_guardian';

  /// Create a [UserGuardianRow] from the [data] provided
  @override
  UserGuardianRow createRow(Map<String, dynamic> data) =>
      UserGuardianRow.fromJson(data);
}

/// User Guardian Row
class UserGuardianRow extends SupabaseDataRow {
  /// User Guardian Row
  UserGuardianRow({
    required String userId,
    required String name,
    String? id,
    String? birthdate,
    String? gender,
    String? phone,
    DateTime? createdAt,
  }) : super({
         'user_id': supaSerialize(userId),
         'name': supaSerialize(name),
         if (id != null) 'id': supaSerialize(id),
         if (birthdate != null) 'birthdate': supaSerialize(birthdate),
         if (gender != null) 'gender': supaSerialize(gender),
         if (phone != null) 'phone': supaSerialize(phone),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
       });

  /// User Guardian Row
  const UserGuardianRow._(super.data);

  /// Create User Guardian Row from a [data] map
  factory UserGuardianRow.fromJson(Map<String, dynamic> data) =>
      UserGuardianRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => UserGuardianTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// User Id field name
  static const String userIdField = 'user_id';

  /// User Id
  String get userId => getField<String>(userIdField)!;
  set userId(String value) => setField<String>(userIdField, value);

  /// Name field name
  static const String nameField = 'name';

  /// Name
  String get name => getField<String>(nameField)!;
  set name(String value) => setField<String>(nameField, value);

  /// Birthdate field name
  static const String birthdateField = 'birthdate';

  /// Birthdate
  String? get birthdate => getField<String>(birthdateField);
  set birthdate(String? value) => setField<String>(birthdateField, value);

  /// Gender field name
  static const String genderField = 'gender';

  /// Gender
  String? get gender => getField<String>(genderField);
  set gender(String? value) => setField<String>(genderField, value);

  /// Phone field name
  static const String phoneField = 'phone';

  /// Phone
  String? get phone => getField<String>(phoneField);
  set phone(String? value) => setField<String>(phoneField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Make a copy of the current [UserGuardianRow]
  /// overriding the provided fields
  UserGuardianRow copyWith({
    String? userId,
    String? name,
    String? id,
    String? birthdate,
    String? gender,
    String? phone,
    DateTime? createdAt,
  }) => UserGuardianRow.fromJson({
    'user_id': supaSerialize(userId) ?? data['user_id'],
    'name': supaSerialize(name) ?? data['name'],
    'id': supaSerialize(id) ?? data['id'],
    'birthdate': supaSerialize(birthdate) ?? data['birthdate'],
    'gender': supaSerialize(gender) ?? data['gender'],
    'phone': supaSerialize(phone) ?? data['phone'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
  });
}

/// Tag: v2
/// Date: 2026-03-13 09:30:01.808052
