//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// User Table
class UserTable extends SupabaseTable<UserRow> {
  /// Table Name
  @override
  String get tableName => 'user';

  /// Create a [UserRow] from the [data] provided
  @override
  UserRow createRow(Map<String, dynamic> data) => UserRow.fromJson(data);
}

/// User Row
class UserRow extends SupabaseDataRow {
  /// User Row
  UserRow({
    String? id,
    String? username,
    DateTime? createdAt,
    UserType? type,
    String? birthdate,
    String? email,
    String? phone,
    bool? emailVerified,
    DateTime? adminApprovalDate,
    String? adminApprovedBy,
    String? defaultShippingAddress,
    VendorAdminType? vendorAdminType,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (username != null) 'username': supaSerialize(username),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (type != null) 'type': supaSerialize(type),
         if (birthdate != null) 'birthdate': supaSerialize(birthdate),
         if (email != null) 'email': supaSerialize(email),
         if (phone != null) 'phone': supaSerialize(phone),
         if (emailVerified != null)
           'email_verified': supaSerialize(emailVerified),
         if (adminApprovalDate != null)
           'admin_approval_date': supaSerialize(adminApprovalDate),
         if (adminApprovedBy != null)
           'admin_approved_by': supaSerialize(adminApprovedBy),
         if (defaultShippingAddress != null)
           'default_shipping_address': supaSerialize(defaultShippingAddress),
         if (vendorAdminType != null)
           'vendor_admin_type': supaSerialize(vendorAdminType),
       });

  /// User Row
  const UserRow._(super.data);

  /// Create User Row from a [data] map
  factory UserRow.fromJson(Map<String, dynamic> data) =>
      UserRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => UserTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: 'auth.')!;
  set id(String value) => setField<String>(idField, value);

  /// Username field name
  static const String usernameField = 'username';

  /// Username
  String? get username => getField<String>(usernameField);
  set username(String? value) => setField<String>(usernameField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Type field name
  static const String typeField = 'type';

  /// Type
  UserType get type => getField<UserType>(
    typeField,
    enumValues: UserType.values,
    defaultValue: UserType.user,
  )!;
  set type(UserType value) => setField<UserType>(typeField, value);

  /// Birthdate field name
  static const String birthdateField = 'birthdate';

  /// Birthdate
  String? get birthdate => getField<String>(birthdateField);
  set birthdate(String? value) => setField<String>(birthdateField, value);

  /// Email field name
  static const String emailField = 'email';

  /// Email
  String? get email => getField<String>(emailField);
  set email(String? value) => setField<String>(emailField, value);

  /// Phone field name
  static const String phoneField = 'phone';

  /// Phone
  String? get phone => getField<String>(phoneField);
  set phone(String? value) => setField<String>(phoneField, value);

  /// Email Verified field name
  static const String emailVerifiedField = 'email_verified';

  /// Email Verified
  bool get emailVerified =>
      getField<bool>(emailVerifiedField, defaultValue: false)!;
  set emailVerified(bool value) => setField<bool>(emailVerifiedField, value);

  /// Admin Approval Date field name
  static const String adminApprovalDateField = 'admin_approval_date';

  /// Admin Approval Date
  DateTime? get adminApprovalDate => getField<DateTime>(adminApprovalDateField);
  set adminApprovalDate(DateTime? value) =>
      setField<DateTime>(adminApprovalDateField, value);

  /// Admin Approved By field name
  static const String adminApprovedByField = 'admin_approved_by';

  /// Admin Approved By
  String? get adminApprovedBy => getField<String>(adminApprovedByField);
  set adminApprovedBy(String? value) =>
      setField<String>(adminApprovedByField, value);

  /// Default Shipping Address field name
  static const String defaultShippingAddressField = 'default_shipping_address';

  /// Default Shipping Address
  String? get defaultShippingAddress =>
      getField<String>(defaultShippingAddressField);
  set defaultShippingAddress(String? value) =>
      setField<String>(defaultShippingAddressField, value);

  /// Vendor Admin Type field name
  static const String vendorAdminTypeField = 'vendor_admin_type';

  /// Vendor Admin Type
  VendorAdminType? get vendorAdminType => getField<VendorAdminType>(
    vendorAdminTypeField,
    enumValues: VendorAdminType.values,
  );
  set vendorAdminType(VendorAdminType? value) =>
      setField<VendorAdminType>(vendorAdminTypeField, value);

  /// Make a copy of the current [UserRow]
  /// overriding the provided fields
  UserRow copyWith({
    String? id,
    String? username,
    DateTime? createdAt,
    UserType? type,
    String? birthdate,
    String? email,
    String? phone,
    bool? emailVerified,
    DateTime? adminApprovalDate,
    String? adminApprovedBy,
    String? defaultShippingAddress,
    VendorAdminType? vendorAdminType,
  }) => UserRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'username': supaSerialize(username) ?? data['username'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'type': supaSerialize(type) ?? data['type'],
    'birthdate': supaSerialize(birthdate) ?? data['birthdate'],
    'email': supaSerialize(email) ?? data['email'],
    'phone': supaSerialize(phone) ?? data['phone'],
    'email_verified': supaSerialize(emailVerified) ?? data['email_verified'],
    'admin_approval_date':
        supaSerialize(adminApprovalDate) ?? data['admin_approval_date'],
    'admin_approved_by':
        supaSerialize(adminApprovedBy) ?? data['admin_approved_by'],
    'default_shipping_address':
        supaSerialize(defaultShippingAddress) ??
        data['default_shipping_address'],
    'vendor_admin_type':
        supaSerialize(vendorAdminType) ?? data['vendor_admin_type'],
  });
}

/// Tag: v2
/// Date: 2025-12-03 16:25:28.161331
