//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// User Profile Table
class UserProfileTable extends SupabaseTable<UserProfileRow> {
  /// Table Name
  @override
  String get tableName => 'user_profile';

  /// Create a [UserProfileRow] from the [data] provided
  @override
  UserProfileRow createRow(Map<String, dynamic> data) =>
      UserProfileRow.fromJson(data);
}

/// User Profile Row
class UserProfileRow extends SupabaseDataRow {
  /// User Profile Row
  UserProfileRow({
    required String user,
    String? id,
    DateTime? createdAt,
    String? name,
    DateTime? deletedAt,
  }) : super({
         'user': supaSerialize(user),
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (name != null) 'name': supaSerialize(name),
         if (deletedAt != null) 'deleted_at': supaSerialize(deletedAt),
       });

  /// User Profile Row
  const UserProfileRow._(super.data);

  /// Create User Profile Row from a [data] map
  factory UserProfileRow.fromJson(Map<String, dynamic> data) =>
      UserProfileRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => UserProfileTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// User field name
  static const String userField = 'user';

  /// User
  String get user => getField<String>(userField)!;
  set user(String value) => setField<String>(userField, value);

  /// Name field name
  static const String nameField = 'name';

  /// Name
  String? get name => getField<String>(nameField);
  set name(String? value) => setField<String>(nameField, value);

  /// Deleted At field name
  static const String deletedAtField = 'deleted_at';

  /// Deleted At
  DateTime? get deletedAt => getField<DateTime>(deletedAtField);
  set deletedAt(DateTime? value) => setField<DateTime>(deletedAtField, value);

  /// Make a copy of the current [UserProfileRow]
  /// overriding the provided fields
  UserProfileRow copyWith({
    String? user,
    String? id,
    DateTime? createdAt,
    String? name,
    DateTime? deletedAt,
  }) => UserProfileRow.fromJson({
    'user': supaSerialize(user) ?? data['user'],
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'name': supaSerialize(name) ?? data['name'],
    'deleted_at': supaSerialize(deletedAt) ?? data['deleted_at'],
  });
}

/// Tag: v2
/// Date: 2026-03-18 15:17:25.900473
