//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// User Settings Table
class UserSettingsTable extends SupabaseTable<UserSettingsRow> {
  /// Table Name
  @override
  String get tableName => 'user_settings';

  /// Create a [UserSettingsRow] from the [data] provided
  @override
  UserSettingsRow createRow(Map<String, dynamic> data) =>
      UserSettingsRow.fromJson(data);
}

/// User Settings Row
class UserSettingsRow extends SupabaseDataRow {
  /// User Settings Row
  UserSettingsRow({
    required UserSetting setting,
    String? user,
    DateTime? createdAt,
    bool? value,
  }) : super({
         'setting': supaSerialize(setting),
         if (user != null) 'user': supaSerialize(user),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (value != null) 'value': supaSerialize(value),
       });

  /// User Settings Row
  const UserSettingsRow._(super.data);

  /// Create User Settings Row from a [data] map
  factory UserSettingsRow.fromJson(Map<String, dynamic> data) =>
      UserSettingsRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => UserSettingsTable();

  /// User field name
  static const String userField = 'user';

  /// User
  String get user => getField<String>(userField, defaultValue: 'auth.')!;
  set user(String value) => setField<String>(userField, value);

  /// Setting field name
  static const String settingField = 'setting';

  /// Setting
  UserSetting get setting =>
      getField<UserSetting>(settingField, enumValues: UserSetting.values)!;
  set setting(UserSetting value) => setField<UserSetting>(settingField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Value field name
  static const String valueField = 'value';

  /// Value
  bool get value => getField<bool>(valueField, defaultValue: true)!;
  set value(bool value) => setField<bool>(valueField, value);

  /// Make a copy of the current [UserSettingsRow]
  /// overriding the provided fields
  UserSettingsRow copyWith({
    UserSetting? setting,
    String? user,
    DateTime? createdAt,
    bool? value,
  }) => UserSettingsRow.fromJson({
    'setting': supaSerialize(setting) ?? data['setting'],
    'user': supaSerialize(user) ?? data['user'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'value': supaSerialize(value) ?? data['value'],
  });
}

/// Tag: v2
/// Date: 2026-03-17 11:11:48.578123
