//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// User Shipping Address Table
class UserShippingAddressTable extends SupabaseTable<UserShippingAddressRow> {
  /// Table Name
  @override
  String get tableName => 'user_shipping_address';

  /// Create a [UserShippingAddressRow] from the [data] provided
  @override
  UserShippingAddressRow createRow(Map<String, dynamic> data) =>
      UserShippingAddressRow.fromJson(data);
}

/// User Shipping Address Row
class UserShippingAddressRow extends SupabaseDataRow {
  /// User Shipping Address Row
  UserShippingAddressRow({
    String? id,
    DateTime? createdAt,
    String? addressBy,
    String? name,
    String? recipientName,
    String? phoneNumber,
    String? address,
    String? detailedAddress,
    String? requestsForDelivery,
    bool? reusableBoxesAreOkay,
    String? postalCode,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (addressBy != null) 'address_by': supaSerialize(addressBy),
         if (name != null) 'name': supaSerialize(name),
         if (recipientName != null)
           'recipient_name': supaSerialize(recipientName),
         if (phoneNumber != null) 'phone_number': supaSerialize(phoneNumber),
         if (address != null) 'address': supaSerialize(address),
         if (detailedAddress != null)
           'detailed_address': supaSerialize(detailedAddress),
         if (requestsForDelivery != null)
           'requests_for_delivery': supaSerialize(requestsForDelivery),
         if (reusableBoxesAreOkay != null)
           'reusable_boxes_are_okay': supaSerialize(reusableBoxesAreOkay),
         if (postalCode != null) 'postal_code': supaSerialize(postalCode),
       });

  /// User Shipping Address Row
  const UserShippingAddressRow._(super.data);

  /// Create User Shipping Address Row from a [data] map
  factory UserShippingAddressRow.fromJson(Map<String, dynamic> data) =>
      UserShippingAddressRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => UserShippingAddressTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Address By field name
  static const String addressByField = 'address_by';

  /// Address By
  String? get addressBy => getField<String>(addressByField);
  set addressBy(String? value) => setField<String>(addressByField, value);

  /// Name field name
  static const String nameField = 'name';

  /// Name
  String? get name => getField<String>(nameField);
  set name(String? value) => setField<String>(nameField, value);

  /// Recipient Name field name
  static const String recipientNameField = 'recipient_name';

  /// Recipient Name
  String? get recipientName => getField<String>(recipientNameField);
  set recipientName(String? value) =>
      setField<String>(recipientNameField, value);

  /// Phone Number field name
  static const String phoneNumberField = 'phone_number';

  /// Phone Number
  String? get phoneNumber => getField<String>(phoneNumberField);
  set phoneNumber(String? value) => setField<String>(phoneNumberField, value);

  /// Address field name
  static const String addressField = 'address';

  /// Address
  String? get address => getField<String>(addressField);
  set address(String? value) => setField<String>(addressField, value);

  /// Detailed Address field name
  static const String detailedAddressField = 'detailed_address';

  /// Detailed Address
  String? get detailedAddress => getField<String>(detailedAddressField);
  set detailedAddress(String? value) =>
      setField<String>(detailedAddressField, value);

  /// Requests For Delivery field name
  static const String requestsForDeliveryField = 'requests_for_delivery';

  /// Requests For Delivery
  String? get requestsForDelivery => getField<String>(requestsForDeliveryField);
  set requestsForDelivery(String? value) =>
      setField<String>(requestsForDeliveryField, value);

  /// Reusable Boxes Are Okay field name
  static const String reusableBoxesAreOkayField = 'reusable_boxes_are_okay';

  /// Reusable Boxes Are Okay
  bool get reusableBoxesAreOkay =>
      getField<bool>(reusableBoxesAreOkayField, defaultValue: false)!;
  set reusableBoxesAreOkay(bool value) =>
      setField<bool>(reusableBoxesAreOkayField, value);

  /// Postal Code field name
  static const String postalCodeField = 'postal_code';

  /// Postal Code
  String? get postalCode => getField<String>(postalCodeField);
  set postalCode(String? value) => setField<String>(postalCodeField, value);

  /// Make a copy of the current [UserShippingAddressRow]
  /// overriding the provided fields
  UserShippingAddressRow copyWith({
    String? id,
    DateTime? createdAt,
    String? addressBy,
    String? name,
    String? recipientName,
    String? phoneNumber,
    String? address,
    String? detailedAddress,
    String? requestsForDelivery,
    bool? reusableBoxesAreOkay,
    String? postalCode,
  }) => UserShippingAddressRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'address_by': supaSerialize(addressBy) ?? data['address_by'],
    'name': supaSerialize(name) ?? data['name'],
    'recipient_name': supaSerialize(recipientName) ?? data['recipient_name'],
    'phone_number': supaSerialize(phoneNumber) ?? data['phone_number'],
    'address': supaSerialize(address) ?? data['address'],
    'detailed_address':
        supaSerialize(detailedAddress) ?? data['detailed_address'],
    'requests_for_delivery':
        supaSerialize(requestsForDelivery) ?? data['requests_for_delivery'],
    'reusable_boxes_are_okay':
        supaSerialize(reusableBoxesAreOkay) ?? data['reusable_boxes_are_okay'],
    'postal_code': supaSerialize(postalCode) ?? data['postal_code'],
  });
}

/// Tag: v2
/// Date: 2026-03-10 15:21:09.884546
