//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

export 'enums/_enums.dart';
export 'tables/_tables.dart';

/// Tag: v2
/// Date: 2026-03-20 19:41:33.414437
