//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

export 'enums/_enums.dart';
export 'tables/_tables.dart';

/// Tag: v2
/// Date: 2025-12-23 14:25:57.824249
