//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

/// Automatic Push Type enum
enum AutomaticPushType {
  /// user_behavior
  user_behavior,

  /// campaign
  campaign,
}

/// Tag: v2
/// Date: 2026-03-20 19:41:33.312095
