//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

/// Client Admin Type enum
enum ClientAdminType {
  /// super (DB value: super)
  super_,
  /// mid
  mid,
  /// general
  general,
}

/// Tag: v2
/// Date: 2026-03-12 10:33:15.556287
