//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

/// Client Admin Type enum
enum ClientAdminType {
  /// super_admin
  super_admin,

  /// mid_admin
  mid_admin,

  /// general_admin
  general_admin,
}

/// Tag: v2
/// Date: 2026-03-17 16:20:05.923142
