//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

/// Client Admin Notification Type enum
enum ClientAdminNotificationType {
  /// mission_approved
  mission_approved,

  /// mission_rejected
  mission_rejected,

  /// inquiry_response
  inquiry_response,

  /// inquiry_comment
  inquiry_comment,
}

/// Tag: v2
/// Date: 2026-03-12 16:36:10.560195
