//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

/// Cost Change Request Type enum
enum CostChangeRequestType {
  /// company_budget
  company_budget,

  /// department_discount
  department_discount,

  /// mission_cost
  mission_cost,
}

/// Tag: v2
/// Date: 2026-03-12 16:36:10.560793
