//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

/// Interval Unit enum
enum IntervalUnit {
  /// day
  day,

  /// hour
  hour,

  /// minute
  minute,
}

/// Tag: v2
/// Date: 2026-01-05 16:52:08.854701
