//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

/// Mission Type enum
enum MissionType {
  /// general
  general,

  /// banner_exposed
  banner_exposed,
}

/// Tag: v2
/// Date: 2026-03-11 13:30:59.611763
