//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

/// Mission Publicity enum
enum MissionPublicity {
  /// public
  public,

  /// all_staff
  all_staff,
}

/// Tag: v2
/// Date: 2026-02-20 11:42:15.108926
