//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

/// Mission Type enum
enum MissionType {
  /// general
  general,

  /// banner_exposed
  banner_exposed,
}

/// Tag: v2
/// Date: 2025-12-17 09:43:01.599421
