//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

/// Product Sale Status enum
enum ProductSaleStatus {
  /// on_sale
  on_sale,

  /// discontinued
  discontinued,

  /// sold_out
  sold_out,
}

/// Tag: v2
/// Date: 2026-03-11 13:30:59.612583
