//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

/// Product Style enum
enum ProductStyle {
  /// tote
  tote,

  /// cross
  cross,

  /// shoulder
  shoulder,

  /// accessories
  accessories,
}

/// Tag: v2
/// Date: 2026-02-03 09:35:09.182805
