//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

/// Product Material enum
enum ProductMaterial {
  /// nature_oriented
  nature_oriented,

  /// vegan
  vegan,

  /// biodegradable
  biodegradable,
}

/// Tag: v2
/// Date: 2026-03-11 13:30:59.611965
