//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

/// User Type enum
enum UserType {
  /// user
  user,

  /// standard_client_admin
  standard_client_admin,

  /// integrated_admin
  integrated_admin,

  /// vendor_admin
  vendor_admin,

  /// platform_admin
  platform_admin,

  /// super_client_admin
  super_client_admin,
}

/// Tag: v2
/// Date: 2025-12-17 14:31:24.955457
