//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

/// User Type enum
enum UserType {
  /// user
  user,

  /// client_admin
  client_admin,

  /// integrated_admin
  integrated_admin,

  /// vendor_admin
  vendor_admin,

  /// platform_admin
  platform_admin,

  /// super_client_admin
  super_client_admin,

  /// client_viewer
  client_viewer,

  /// super_integrated_admin
  super_integrated_admin,

  /// integrated_viewer
  integrated_viewer,
}

/// Tag: v2
/// Date: 2025-12-30 17:23:48.725850
