//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

/// User Type enum
enum UserType {
  /// user
  user,

  /// client_admin
  client_admin,

  /// integrated_admin
  integrated_admin,

  /// vendor_admin
  vendor_admin,

  /// platform_admin
  platform_admin,
}

/// Tag: v2
/// Date: 2025-11-25 17:06:15.044922
