//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

/// User Setting enum
enum UserSetting {
  /// receive_marketing_information_consent
  receive_marketing_information_consent,

  /// provide_personal_information_to_third_parties_consent
  provide_personal_information_to_third_parties_consent,

  /// missions_notification
  missions_notification,

  /// award_points_notification
  award_points_notification,

  /// stories_notification
  stories_notification,

  /// notices
  notices,
}

/// Tag: v2
/// Date: 2026-03-18 15:17:25.730948
