//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (3.0.1)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

/// Vendor Admin Type enum
enum VendorAdminType {
  /// retailer
  retailer,

  /// lgs
  lgs,
}

/// Tag: v2
/// Date: 2026-03-17 16:20:05.934089
