// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvaqV8Bu4odf9OoJgYwkeKRkxmKZuYMLY',
    appId: '1:885232472112:web:76bf46454081f5828eddf5',
    messagingSenderId: '885232472112',
    projectId: 'esg-main-8e4bd',
    authDomain: 'esg-main-8e4bd.firebaseapp.com',
    storageBucket: 'esg-main-8e4bd.firebasestorage.app',
    measurementId: 'G-56YNJ9K1G6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACxJCpUlhBc5AIUxqUAGbT0sU-HamSIcE',
    appId: '1:885232472112:android:eca9bd9446a2547c8eddf5',
    messagingSenderId: '885232472112',
    projectId: 'esg-main-8e4bd',
    storageBucket: 'esg-main-8e4bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1hnWnqLqk_H_GSg3cS2V5x_42xSLMIaA',
    appId: '1:885232472112:ios:e29ddd00cbf73a148eddf5',
    messagingSenderId: '885232472112',
    projectId: 'esg-main-8e4bd',
    storageBucket: 'esg-main-8e4bd.firebasestorage.app',
    iosBundleId: 'com.example.esgMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1hnWnqLqk_H_GSg3cS2V5x_42xSLMIaA',
    appId: '1:885232472112:ios:e29ddd00cbf73a148eddf5',
    messagingSenderId: '885232472112',
    projectId: 'esg-main-8e4bd',
    storageBucket: 'esg-main-8e4bd.firebasestorage.app',
    iosBundleId: 'com.example.esgMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvaqV8Bu4odf9OoJgYwkeKRkxmKZuYMLY',
    appId: '1:885232472112:web:cf42a06e24ce51ea8eddf5',
    messagingSenderId: '885232472112',
    projectId: 'esg-main-8e4bd',
    authDomain: 'esg-main-8e4bd.firebaseapp.com',
    storageBucket: 'esg-main-8e4bd.firebasestorage.app',
    measurementId: 'G-SLSQS0EQWP',
  );

}