const asset = (
  // EB Garamond
  ebGaramondItalic: 'EBGaramond-Italic-VariableFont_wght.ttf',
  ebGaramond: 'EBGaramond-VariableFont_wght.ttf',
  ebGaramondBold: 'EBGaramond-Bold.ttf',
  ebGaramondBoldItalic: 'EBGaramond-BoldItalic.ttf',
  ebGaramondExtraBold: 'EBGaramond-ExtraBold.ttf',
  ebGaramondExtraBoldItalic: 'EBGaramond-ExtraBoldItalic.ttf',
  ebGaramondItalicStatic: 'EBGaramond-Italic.ttf',
  ebGaramondMedium: 'EBGaramond-Medium.ttf',
  ebGaramondMediumItalic: 'EBGaramond-MediumItalic.ttf',
  ebGaramondRegular: 'EBGaramond-Regular.ttf',
  ebGaramondSemiBold: 'EBGaramond-SemiBold.ttf',
  ebGaramondSemiBoldItalic: 'EBGaramond-SemiBoldItalic.ttf',
  // Noto Sans KR
  notoSansKr: 'NotoSansKR-VariableFont_wght.ttf',
  notoSansKrBlack: 'NotoSansKR-Black.ttf',
  notoSansKrBold: 'NotoSansKR-Bold.ttf',
  notoSansKrExtraBold: 'NotoSansKR-ExtraBold.ttf',
  notoSansKrExtraLight: 'NotoSansKR-ExtraLight.ttf',
  notoSansKrLight: 'NotoSansKR-Light.ttf',
  notoSansKrMedium: 'NotoSansKR-Medium.ttf',
  notoSansKrRegular: 'NotoSansKR-Regular.ttf',
  notoSansKrSemiBold: 'NotoSansKR-SemiBold.ttf',
  notoSansKrThin: 'NotoSansKR-Thin.ttf',
  // Source Han Kr
  sourceHanSerifKBold: 'SourceHanSerifK-Bold.otf',
  sourceHanSerifKExtraLight: 'SourceHanSerifK-ExtraLight.otf',
  sourceHanSerifKHeavy: 'SourceHanSerifK-Heavy.otf',
  sourceHanSerifKLight: 'SourceHanSerifK-Light.otf',
  sourceHanSerifKMedium: 'SourceHanSerifK-Medium.otf',
  sourceHanSerifKRegular: 'SourceHanSerifK-Regular.otf',
  sourceHanSerifKSemiBold: 'SourceHanSerifK-SemiBold.otf',
  // Source Han Serif
  sourceHanSerifBold: 'SourceHanSerif-Bold.ttc',
  sourceHanSerifExtraLight: 'SourceHanSerif-ExtraLight.ttc',
  sourceHanSerifHeavy: 'SourceHanSerif-Heavy.ttc',
  sourceHanSerifLight: 'SourceHanSerif-Light.ttc',
  sourceHanSerifMedium: 'SourceHanSerif-Medium.ttc',
  sourceHanSerifRegular: 'SourceHanSerif-Regular.ttc',
  sourceHanSerifSemiBold: 'SourceHanSerif-SemiBold.ttc',
);

const Map<String, String> assetFolderPath = {
  // EB Garamond
  'EBGaramond-Italic-VariableFont_wght.ttf': 'fonts/EB_Garamond',
  'EBGaramond-VariableFont_wght.ttf': 'fonts/EB_Garamond',
  'EBGaramond-Bold.ttf': 'fonts/EB_Garamond/static',
  'EBGaramond-BoldItalic.ttf': 'fonts/EB_Garamond/static',
  'EBGaramond-ExtraBold.ttf': 'fonts/EB_Garamond/static',
  'EBGaramond-ExtraBoldItalic.ttf': 'fonts/EB_Garamond/static',
  'EBGaramond-Italic.ttf': 'fonts/EB_Garamond/static',
  'EBGaramond-Medium.ttf': 'fonts/EB_Garamond/static',
  'EBGaramond-MediumItalic.ttf': 'fonts/EB_Garamond/static',
  'EBGaramond-Regular.ttf': 'fonts/EB_Garamond/static',
  'EBGaramond-SemiBold.ttf': 'fonts/EB_Garamond/static',
  'EBGaramond-SemiBoldItalic.ttf': 'fonts/EB_Garamond/static',
  // Noto Sans KR
  'NotoSansKR-VariableFont_wght.ttf': 'fonts/Noto_Sans_KR',
  'NotoSansKR-Black.ttf': 'fonts/Noto_Sans_KR/static',
  'NotoSansKR-Bold.ttf': 'fonts/Noto_Sans_KR/static',
  'NotoSansKR-ExtraBold.ttf': 'fonts/Noto_Sans_KR/static',
  'NotoSansKR-ExtraLight.ttf': 'fonts/Noto_Sans_KR/static',
  'NotoSansKR-Light.ttf': 'fonts/Noto_Sans_KR/static',
  'NotoSansKR-Medium.ttf': 'fonts/Noto_Sans_KR/static',
  'NotoSansKR-Regular.ttf': 'fonts/Noto_Sans_KR/static',
  'NotoSansKR-SemiBold.ttf': 'fonts/Noto_Sans_KR/static',
  'NotoSansKR-Thin.ttf': 'fonts/Noto_Sans_KR/static',
  // Source Han Kr
  'SourceHanSerifK-Bold.otf': 'fonts/Source_Han_Kr',
  'SourceHanSerifK-ExtraLight.otf': 'fonts/Source_Han_Kr',
  'SourceHanSerifK-Heavy.otf': 'fonts/Source_Han_Kr',
  'SourceHanSerifK-Light.otf': 'fonts/Source_Han_Kr',
  'SourceHanSerifK-Medium.otf': 'fonts/Source_Han_Kr',
  'SourceHanSerifK-Regular.otf': 'fonts/Source_Han_Kr',
  'SourceHanSerifK-SemiBold.otf': 'fonts/Source_Han_Kr',
  // Source Han Serif
  'SourceHanSerif-Bold.ttc': 'fonts/Source_Hans_Serif',
  'SourceHanSerif-ExtraLight.ttc': 'fonts/Source_Hans_Serif',
  'SourceHanSerif-Heavy.ttc': 'fonts/Source_Hans_Serif',
  'SourceHanSerif-Light.ttc': 'fonts/Source_Hans_Serif',
  'SourceHanSerif-Medium.ttc': 'fonts/Source_Hans_Serif',
  'SourceHanSerif-Regular.ttc': 'fonts/Source_Hans_Serif',
  'SourceHanSerif-SemiBold.ttc': 'fonts/Source_Hans_Serif',
};
